### ISSUE TITLE
V0.09 輸入後無法接著輸入"空白"

### ISSUE THREAD

**Issue by Chinan** [EasyIME/PIME#10]
使用環境是Windows 10 64Bits PIME Ver. 0.09
在中文輸入的狀態下輸入後(按下enter) 無法接著輸入"空白" ，切換至英文輸入便可以。

**Comment by PCMan** [comment]
Fixed in v0.10.

**Comment by KenLuo** [comment]
0.09 未刪除狀態下，直接安裝 0.10 ，還是會有此狀況。
解除安裝後，重新安裝 0.10 ，也還是會有這個狀況。
謝謝你的付出，感恩～～

作業系統資訊：
![image](https://cloud.githubusercontent.com/assets/2156112/13415843/2fa158a8-df99-11e5-91fb-ab14ce80b062.png)

**Comment by KenLuo** [comment]
剛剛試出來問題了。。
我設定了 「按空白鍵叫出選字視窗」，結果就讓中文輸入完後按了 enter，之後按空白鍵也沒作用了。

**Comment by PCMan** [comment]
Fixed in git.
