### ISSUE TITLE
Win7 64bit IE11瀏覽器無法使用

### ISSUE THREAD

**Issue by kalapontsai** [EasyIME/PIME#105]
在IE11切換輸入法時,無法像其他視窗(ex:記事本), 在工具列顯示正常的圖示
試過firefox, chrome皆正常.
擷取螢幕畫面請參考, 謝謝
http://imgur.com/a/kUBLh

**Comment by PCMan** [comment]
請使用最新 v0.13 版本，並且在安裝時選擇
關閉 IE 受保護模式
即可使用
