### ISSUE TITLE
全形標點符號輸入問題

### ISSUE THREAD

**Issue by ottokang** [EasyIME/PIME#107]
升級0.13版之後，全形符號輸入發現這樣的問題

中文模式下，打= [ ] ' \ 會出現半形（之前是全形）

但是打了任意一個注音之後，打＝「」、＼會出現全形

PIME的設定是Shift大寫跟Shift全形符號都開啟，這個Bug跟#48有關，但是是升級0.13版才出現，是因為libchewing升級的關係嗎？

**Comment by ottokang** [comment]
測試了一下，可能是新增的 isBopomofo() 沒有過濾到這幾個按鍵的Virtual Key Code，發了一個Pull requests暫時修改 chewing.py，看看這樣OK不OK。

**Comment by PCMan** [comment]
Fixed.
