### ISSUE TITLE
漢語拼音

### ISSUE THREAD

**Issue by littlesoda** [EasyIME/PIME#109]
請問前面有找到無法使用漢語拼音的問題
下載V0.13之後還是無法使用?
另外line選字有時上下左右會直接跳到另外一個視窗，按下不會出現選字視窗
然後打字未按下enter, 移到別的視窗再回到原本視窗字串會重複
最後想請問，設定的視窗一定每次開啟都是全螢幕嗎XD

**Comment by KenLuoTW** [comment]
漢語拼音的問題已修正於 https://github.com/EasyIME/PIME/commit/f57752131c8d301b95dbb5b1c89c48ae2409ed6b ,後面的問題同 #18 。
設定視窗看 @PCMan  最後決定如何,基本上不是 bug。
如有疑問或建議,請至 [PIME 討論區](https://github.com/EasyIME/forum) 討論。
