### ISSUE TITLE
倉頡輸入法按下「,」、「.」、「'」後要不要加空白鍵？

### ISSUE THREAD

**Issue by lyenliang** [EasyIME/PIME#110]
我發現 newcj3.cin 底下符號開頭是「,」、「.」及「'」的會打不出來

![pime_suggestion2](https://cloud.githubusercontent.com/assets/3468329/16408210/3fbe18ac-3d4a-11e6-930a-6fb9b6e3b53f.png)

打不出來是因為這三個鍵按下後不必按空白鍵就會輸出「，」、「。」及「、」

如果讓使用者能自行選擇「,」、「.」、「'」按下後是否需加空白鍵才能輸出字，會不會比較好？

這樣比較忠於原本輸入法的設計。

**Comment by KenLuoTW** [comment]
請參考:
https://github.com/EasyIME/PIME/issues/64#issuecomment-202762575

僅有以「'」編碼的符號會被取代掉,因為這部份已經挪為「多功能前導字元」所使用。
不過可以自訂義符號輸入的地方很多,真得有須用到以「'」編碼的符號的話,設在別的地方即可。

**Comment by lyenliang** [comment]
了解了     感謝 KenLuoTW 的回答
