### ISSUE TITLE
win 10移除後會跳出錯誤視窗

### ISSUE THREAD

**Issue by littlesoda** [EasyIME/PIME#112]
win 10移除重開機後會一直跳出 「找不到 C:\..........\PIME\Python\pythonw.exe 請確定您輸入正確的名稱，請重試」視窗

**Comment by KenLuoTW** [comment]
安裝新版後再移除看看,應該先前移除沒有完成。

**Comment by KenLuoTW** [comment]
Win10 目前版本的登錄檔似乎有些 bug,某些對於登錄檔的操作可能會失敗,
如果再次重裝並移除後還有相同情況,請靜待 Win10 RS1 版本釋出(7月底左右)再來試看看。
因為目前移除程式這部份的處理是正確的。

另外請注意管理員權限問題,不論是安裝程式或移除程式,都須以管理員身份執行。
