### ISSUE TITLE
自行產生的 PIME-0.13.1-setup.exe 安裝後輸入法沒有圖示

### ISSUE THREAD

**Issue by lyenliang** [EasyIME/PIME#113]
今天我想試著自己用 installer.nsi 產生安裝檔，我操作的方式如下：

1. 安裝 https://github.com/EasyIME/PIME/releases 抓下來的 `PIME-0.13.1-setup.exe`
2. git clone https://github.com/EasyIME/PIME.git
3. cd PIME
4. 在 PIME 底下建立以下資料夾及檔案
```
build
├─libpipe
│  └─Release
│          libpipe.dll （C:\Program Files (x86)\PIME 複製來的）
│
├─pime
│  └─Release
│          PIMETextService.dll （C:\Program Files (x86)\PIME\x86 複製來的）
│
└─PIMELauncher
    └─Release
            PIMELauncher.exe （C:\Program Files (x86)\PIME 複製來的）
build64
└─pime
    └─Release
            PIMETextService.dll （C:\Program Files (x86)\PIME\x64 複製來的）
```
5. 開啟 [NSIS 3.0rc1](http://nsis.sourceforge.net/Download)
6. 選 Compile NSI scripts -> 選 PIME\installer\installer.nsi
7. PIME-0.13.1-setup.exe 被產生在 PIME\installer\ 下
8. 移除原本的 PIME 輸入平台
9. 用剛剛產生的 `PIME-0.13.1-setup.exe` 安裝 PIME

結果最後裝好的輸入法沒有圖示，無法輸入中文。

![installer_issue](https://cloud.githubusercontent.com/assets/3468329/16447381/e8129bf2-3e1e-11e6-8ce5-904812f4fe17.png)

我是在 Windows 7 專業版環境執行，不曉得有沒有人有類似的情況？

還是我某個步驟有問題？

**Comment by u3350829** [comment]
在下使用包裝好的setup.exe也會有這種問題，而且最奇怪的是
Win7 pro 64bit下OS內建的程式(筆記本之類)輸入法都能正常
work,一但是使用別的程式(Firefox,Line等等)輸入法怎樣都無
法使用....只能退回1.2版

**Comment by KenLuoTW** [comment]
我要晚點才能試,因為現在無法重新開機。

**Comment by KenLuoTW** [comment]
@u3350829 
我剛也試了 0.13.1 版本,在 Win7 x64 的 Firefox 下,可以正常打字。
![2016-06-30 1](https://cloud.githubusercontent.com/assets/12954277/16487435/838d369e-3efd-11e6-9150-afc080995212.png)
![2016-06-30 2](https://cloud.githubusercontent.com/assets/12954277/16487439/896ed19e-3efd-11e6-8947-edec929b6a75.png)

**Comment by KenLuoTW** [comment]
@lyenliang 你的問題是 PIMETextService 要自己編譯，
不然 Server 資料夾裡的檔案，請套用 0.13.1 版的檔案。

**Comment by lyenliang** [comment]
感謝 @KenLuoTW，我晚點試試看
