### ISSUE TITLE
安裝程式若需 reboot 才能繼續，沒有 reboot 仍能強制安裝但會出錯

### ISSUE THREAD

**Issue by PCMan** [EasyIME/PIME#116]
現有機制是先呼叫舊版解安裝，但若有檔案刪除失敗，會要求重新開機 (nsis 的 delete /reboot ok 功能)
但不會讓後續的安裝程式失敗，仍然可以繼續安裝，但安裝後的檔案，會在重開機後被先前排定的 reboot 時移除舊版檔案給刪除。
解法:
1. 如果需要重開機移除部份檔案，在還沒重開以前安裝程式拒絕繼續執行。
可以透過新增一個暫存檔，安排在 reboot 後刪除，偵測該檔案存在與否，則可保證使用者是否已經有重開機過。
2. 不要執行舊版解安裝程式，而將解安裝的程序直接整合進新版的安裝程式，由新版安裝程式負責刪除舊檔案，如此可以確保所有刪除都成功，才可以繼續安裝。

**Comment by PCMan** [comment]
@KenLuoTW 感覺你很熟 NSIS, 這部份需要你的建議. Thanks!

**Comment by KenLuoTW** [comment]
有的喔,之前改安裝腳本時,就已經針對此狀況做了修改,
只要沒有重開機,PIMETextService.dll 檔案沒有刪掉,就不會讓用戶安裝。

PIME 安裝測試 (安裝前檢查舊版測試) :
https://youtu.be/AAJhWwoEh30

另外影片中,可以看到刪除檔案時會卡一陣子,主要是 PIMELauncher.exe 無法結束 python 程序。
NSIS 有個 nsProcess 插件,可以強制終結處理程序,我在輸入法模組的獨立安裝程式下測過,
效果還不錯,可以徹底解決 PIMELauncher.exe 無法結束 python 程序而卡在那的問題。

用法非常簡單,如下:
```
	; Try to terminate running PIMELauncher and the server process
	; terminate pythonw process
	${nsProcess::FindProcess} "PIMELauncher.exe" $R0
	StrCmp $R0 0 0 +2
	${nsProcess::KillProcess} "PIMELauncher.exe" $R0

	${nsProcess::FindProcess} "pythonw.exe" $R0
	StrCmp $R0 0 0 +2
	${nsProcess::KillProcess} "pythonw.exe" $R0
	
	ExecWait '"$INSTDIR\PIMELauncher.exe" /quit'
	${nsProcess::Unload}
```

不過有缺點,如果系統中還有別的程式以 pythonw.exe 執行其它的程式,可能會誤殺。

**Comment by KenLuoTW** [comment]
感覺解除安裝還是有點問題,我再看看哪邊須要強化。

**Comment by KenLuoTW** [comment]
改良後的安裝腳本 #118

**Comment by HongJheLi** [comment]
辛苦了，在面對不斷更新的情況下，需要重開機再安裝的確是麻煩了些。
感謝作者們。
