### ISSUE TITLE
是否要新增「英數輸入法」模組?

### ISSUE THREAD

**Issue by KenLuoTW** [EasyIME/PIME#119]
常在網路上,看到有人提到 Win8 ~ Win10 以後,中英切換上的問題,雖然這僅是一個習慣上的問題,
但是如果在 PIME 新增一個「英數輸入法」模組,或許能夠解決網友們的問題,也能增加 PIME 的
使用率,進而吸引更多同好,一起來改進這個輸入法平台。

微剋多: [慣用的中英文輸入切換模式Ctrl+Shift](http://www.microduo.tw/thread-29877-1-1.html)
Mobile01: [將Windows 10注音輸入法改回傳統切換方式與快速鍵教學](http://www.mobile01.com/topicdetail.php?f=300&t=4806866)

一個簡單的英數輸入法,其實什麼鍵都不要處理,就是英數輸入法了...

英數輸入法模組 (一樣採用 #98 的方式包裝,僅供測試使用):
https://drive.google.com/file/d/0B0FygkS7MtvXdWdjd1NCUDdOQ2s/view?usp=sharing

**Comment by InSb** [comment]
這恐怕是使用習慣的問題。
我這邊都是添加一個「英語(美國) 美式鍵盤」放在首位，再進入`控制面板\所有控制面板项\语言`，進入「高级设置」，把替代語言選成中文就好。

考慮到以上那套操作實在不算友好，新增「英數輸入法」模組的方法起碼很照顧普通用戶。

**Comment by InSb** [comment]
@KenLuoTW 剛測了一下，行為與美式鍵盤一致。

無論如何，這個佔位用的「中英文切換」是一定要有的才好，以便與其他輸入法統一風格。
建議默認是黯淡的「英」，按下 Caps lock 後可顯示為黯淡的「A」。

**Comment by KenLuoTW** [comment]
圖檔我不太會修,故弄不出好看的圖示,如果有人願意幫忙的話,才有辦法。

**Comment by InSb** [comment]
@KenLuoTW 現在風格統一，這樣已經很棒了。
![eng eng](https://cloud.githubusercontent.com/assets/8103265/16575533/a4eb012e-42bb-11e6-9225-d427d4315cc8.png)
個人感覺暫且不用改變。

**Comment by KenLuoTW** [comment]
已新增於 https://github.com/EasyIME/PIME/commit/9fb5317066895cdf76a8fe202606ac78bf1d6acb。
僅在 Win8 以後的系統,在安裝時才會出現英數輸入法模組,預設為不安裝。
