### ISSUE TITLE
檢查 PIMETextService.dll 的 md5，若新版檔案沒變更，安裝程式不要替換

### ISSUE THREAD

**Issue by PCMan** [EasyIME/PIME#120]
主要造成安裝程式需要重開機是因為 PIMETextService.dll 使用中
但其實不是每次改版都有改 dll 的部份，未來可以考慮加上 md5 檢查
http://nsis.sourceforge.net/MD5_plugin
比對新舊版本 dll 是否相同，若相同，只要停止 PIMELauncher 即可
至於輸入法 dll 則不用替換，就不必重新開機即可升級

**Comment by PCMan** [comment]
另一個方法是比對 dll 的版本號碼，只是感覺比對 md5 比較簡單可靠

**Comment by KenLuoTW** [comment]
用 MD5 好，不過可能要晚點弄，目前正在修改 CIN 輸入法的共用核心，
基本上現在應該也能夠支援使用到上方數字鍵的輸入法了，不過還沒有弄一個出來測試。

我比較有疑問的是在 https://github.com/chinese-opendesktop 裡的無蝦米
有沒有專利或版權上的問題，同理大新倉頡也是有點疑問?

我有用新的 CIN 核心去弄一個無蝦米出來，雖然我打不快，但目前測試上沒什麼問題。
![2016-07-05](https://cloud.githubusercontent.com/assets/12954277/16575291/ac2040a0-42b9-11e6-8a8b-aea2af8aec8e.png)

**Comment by PCMan** [comment]
太強了！
@KenLuoTW  無蝦米的問題，就我的理解是有點灰色地帶。
1. 專利已經過期，所以使用該技術目前「我猜應該」不會侵犯專利
2. 碼表本身必須是 clean room 重新製作，若是直接轉檔自無蝦米公司官方表格，這是侵犯著作權
著作權和專利權是兩回事，專利是過期了，但是原表格仍然有著作權
如果有依照無蝦米原理重新自行製作的表格，有可能會是合法的，但是我不是法律專家
這只是之前查詢過相關資料的初步了解，應該可以和法律人士或是無蝦米公司確認。

**Comment by PCMan** [comment]
另一方面，對於擁有無蝦米合法授權的使用者，拿合法購買的表格出來轉檔成 cin，這有可能是合法的... 至少目前某些同類軟體是這樣做，不過... 我們不是學法律的 XD

**Comment by PCMan** [comment]
@KenLuoTW 這或許可以請教林誠夏或是葛冬梅，這兩位之前是中研院自由軟體鑄造場，專門研究授權法律問題的專家，圈內有名

**Comment by PCMan** [comment]
@KenLuoTW 有通用 cin 支援的好處是，可以支援大易和行列輸入法。這兩個是微軟自己官方都沒有做TSF 支援....使用者完全被放生 = =

**Comment by KenLuoTW** [comment]
大易及行列,我晚點修完 BUG 後再看看,我會將之優先弄出來。

**Comment by InSb** [comment]
行列的碼表應是沒問題的，大易不清楚。
另，現在的 Windows 10 中自帶的行列和大易，似乎自從某次更新起，都有了 TSF 支援，唯使用前需按 Shift 先切到中文輸入，用起來也不算順手。

若要試的話，行列30（逗號、句號、分號及斜線都是碼元）與行列40（另外有上排數字鍵作為碼元）都可以試著簡單實作基本功能，如此則在免去法律問題之虞的同時，又很可以測試 CIN 核心。

當然大易才是最高形態……

**Comment by KenLuoTW** [comment]
行列應該沒問題了,接下來換大易~~
![2016-07-05 2](https://cloud.githubusercontent.com/assets/12954277/16581035/05e1f226-42da-11e6-97e0-c4a90acce4f1.png)
