### ISSUE TITLE
0.13.1 版本安裝，會被新的 windows defender 認做病毒。

### ISSUE THREAD

**Issue by KenLuo** [EasyIME/PIME#121]
![10](https://cloud.githubusercontent.com/assets/2156112/16577387/88083d2c-42c7-11e6-8b22-6430b43ebcc2.png)
![9](https://cloud.githubusercontent.com/assets/2156112/16577388/89152b8a-42c7-11e6-9355-54c739807e81.png)

**Comment by KenLuoTW** [comment]
剛才有用 Win10 的 Windows Defender 掃過,沒發現有此問題。

**Comment by KenLuo** [comment]
先下載 0.13 來安裝，是沒問題的，然後再安裝 0.13.1，就又可以。。。
可能是我自己的電腦問題。。
