### ISSUE TITLE
新的 Cin 通用核心輸入法測試 (酷倉、行列、大易、拼音、速成)

### ISSUE THREAD

**Issue by KenLuoTW** [EasyIME/PIME#122]
### 這裡的輸入法模組僅適用 PIME v0.13.1 及先前之版本,下個 PIME 正式版本,因為一些檔案存放路徑有變更,所以將無法再支援這裡所提供的輸入法模組測試版。

如果您希望 PIME 加入新的輸入法,可以在此建議,因為我也不知道還須新增什麼輸入法。

酷倉: PIME-CheCJ-1.11-setup.exe
行列: PIME-CheArray-1.00-setup.exe
大易: PIME-CheDayi-1.00-setup.exe
拼音: PIME-ChePinyin-1.00-setup.exe
速成: PIME-CheSimplex-1.00-setup.exe

https://drive.google.com/folderview?id=0B0FygkS7MtvXbWxCc2NzczRuSEE&usp=sharing

安裝檔採用 #98 的輸入法模組安裝腳本所製作:
```
使用此輸入法模組安裝程式的好處是不須解除安裝 PIME 輸入法主程式,
也不須解除安裝先前版本的輸入法模組,即可直接安裝新版或是測試版的輸入法模組。
安裝完後也不用重新開機,只須以「CTRL + SHIFT」切換一下輸入法,即可開始使用。
```

測試版難免有不完善的地方,有時改版可能會因為疏忽,而照成輸入法當掉、卡程式的問題。
在測試輸入法前,你可以建立一個批次檔放在桌面上,當程式無回應時,就執行這個批次檔,
即可釋放掉輸入法,以下為批次檔所要寫入的內容:

KillPIME.cmd
```
TASKKILL /F /IM PIMELauncher.exe
TASKKILL /F /IM pythonw.exe
```

要再次啟動輸入法,你只須要在開始功能表裡的「執行」輸入:
```
"C:\Program Files (x86)\PIME\PIMELauncher.exe"
```
即可再次啟動 PIME 輸入法。

新的架構有個好處,只要改一個 Cin 通用核心,就能修正或改進每個輸入法的功能或問題。
如果想要開發自己的輸入法,你可以去比較酷倉與其它輸入法之間的不同,會發現只須很小的工作量,
就能新增一個輸入法模組。在酷倉的部份檔案裡,我也有註明要改哪些地方,相信要自己修改已不是問題。

示例: checj_ime.py 與 cheliu_ime.py 不同之處
![2016-07-05 4](https://cloud.githubusercontent.com/assets/12954277/16589895/ccfcdc68-4307-11e6-9daa-7d81f2def829.png)

行列及大易,我本身不會輸入,所以我僅就它的碼表去想像可能會有的狀況來修改。
如果有問題請提出,因為我平常不會去使用它們,所以沒有想法去改進它,也很難發現會有什麼問題。

這些輸入法中,有用到上方數字鍵作為字根的輸入法碼表,程式會自動禁用`直接顯示候選字清單 (不須按空白鍵)`。

目前不啟用`直接顯示候選字清單 (不須按空白鍵)`打字時:
```
當候選字不只一個字,須要按空白鍵或↓鍵才會顯示出候選清單,
這時你可以用`方向鍵 + 空白/ENTER鍵`或是`數字鍵`選取候選字。
```
```
當候選字只有一個字,按下空白鍵時,程式會直接出字。
按↓鍵會顯示出候選清單,這時你可以用`方向鍵 + 空白/ENTER鍵`或是`數字鍵`選取候選字。
```

英數: PIME-CheEng-1.00-setup.exe
這個不是 CIN 核心架構的輸入法。

PIME-0.12-setup.exe
舊版的 PIME 測試版,請直接下載官方的正式版,不要下載這個了。

**Comment by InSb** [comment]
@KenLuoTW 剛才測了一下，效果不錯。
「`鍵選單」中的「注音符號」還是要加上「˙」「ˉ」「ˊ」「ˇ」「ˋ」這些注音符號聲調才好。

自己不太懂行列，僅發表個人看法：

使用「行列30大字集」時，在選擇「`直接顯示候選字清單 (不須按空白鍵)`」時，不能使用上方數字鍵選字。
看了一下「行列30大字集」的對照表，發現數字也是碼元。應是在按 w 之後（可見第 95150 行至第 95560 行），再按下的一次數字鍵是作為碼元的，如按「w1」就羅列出標點符號，按「w3」就羅列出特殊符號，諸如此類；之後再按數字鍵就是用來選字的。
這應是行列的特殊功能，是特性之一。還是要對照一下微軟的行列30比較好（不過微軟的把符號輸入時的空白鍵作為翻頁用，這讓人有些迷惑）。

使用「行列40」時，看對照表（第 77 行至第 85 行）發現了選字鍵，實在把我驚到了。雖說不建議選擇「`直接顯示候選字清單 (不須按空白鍵)`」，不過由於有了選字鍵，那麼如果實現了選字鍵的功能，「直接顯示候選字」這個選項也可以選上了──右小指還能受得住的話。
對照表（第 14445 行至第 14824 行）也有符號輸入功能，姑且認為也是按 h 或 8 之後的第一個選字鍵作為碼元參與編碼，之後的選字鍵就用來選字了。

**Comment by KenLuoTW** [comment]
keyname 中含有 1234567890,就是有使用鍵盤上方數字鍵作為字根的輸入法,
「行列30大字集」也算是其中一種,這之後會註明。

將「直接顯示候選字清單 (不須按空白鍵)」啟用後,在「行列30大字集」
就可以按「w1」就羅列出標點符號，按「w3」就羅列出特殊符號。
之後以空白鍵或↓鍵叫出候選清單,再以方向鍵 + 空白/ENTER鍵或是數字鍵選取候選字。

微軟行列的作法用得很複雜,一下子數字鍵選字,一下子又要 SHIFT+數字鍵選字。
各輸入法的選字鍵,並不打算支援,因為微軟也是統一由數字來選字的。

**Comment by InSb** [comment]
@KenLuoTW 其實還是要看使用者的常用習慣而定。我也只是了解一點行列而已，還是要找日常使用行列的使用者來進一步測試才比較好，這樣也可順便將 PIME 稍加宣傳。

**Comment by KenLuoTW** [comment]
輸入法全數更新,目前 CIN 通用核心包含在每一個輸入法模組的安裝檔裡,
所以有更新的話,全部的輸入法皆要重新下載,未來正式釋出時,就僅須更新 CIN 通用核心即可。

此次更新內容:
* 新增大易輸入法
* 所有輸入法模組,名稱後面註明 (PIME)
![2016-07-06](https://cloud.githubusercontent.com/assets/12954277/16608215/1b721f56-437c-11e6-8267-0d29443499d6.png)
* 修正行列輸入法模組使用「行列30」碼表時不能輸入「w + 數字鍵」輸入符號的問題
* 一律禁用「直接顯示候選字清單 (不須按空白鍵)」在有使用鍵盤上方數字鍵作為字根的輸入法碼表

**Comment by InSb** [comment]
試了一下，發現關閉「`直接顯示候選字清單 (不須按空白鍵)`」時，若出字唯一，直接出字（這邊稱為「`候選唯一空格上屏`」，常作為可選項存在）之後，用萬用字元不出正確編碼的提示，比如大易的「牛工＊」（2r\*）直接出「牴」，而沒有正確編碼提示；同理，倉頡的「竹手竹心＊」（hqhp\*）也如此。

另外，除倉頡以外，其他的很多輸入法都不能（也不應該）以「z」鍵作為萬用鍵。所以在除倉頡以外的模組中，使用「z」鍵作為萬用鍵時是不能的。
不過「*」鍵作為萬用鍵則處處可用，這是很好的，保留是必要的。
至於其他輸入法的萬用鍵一般是什麼，還要問問使用者或查查官方輸入法軟體的 manual 才好。

「`鍵選單」中「注音符號」中沒有「˙」「ˉ」「ˊ」「ˇ」「ˋ」，需要加一下，這個以前提過。

我寫得可能有些凌亂。
暫時先發現這麼多問題，其他的還要繼續測試。

**Comment by KenLuoTW** [comment]
1. 是 bug,已確認

2. 除酷倉外,其它輸入法預設值都是用「*」鍵作萬用字元,
這個不須要問用戶,光看碼表就可以知道要以什麼鍵作萬用字元了。

3. 這個下個測試版加入,包括你提過的快倉也是。

**Comment by KenLuoTW** [comment]
輸入法全數更新,此次更新內容:
* 修正關閉「直接顯示候選字清單 (不須按空白鍵)」時,不會顯示萬用字元編碼提示及簡繁轉換失效的問題。 (CinBase)
* 「`」鍵選單中的注音符號項目,加入聲調符號字元。 (CinBase)
* 酷倉輸入法模組加入「快倉六代」碼表。

**Comment by InSb** [comment]
@KenLuoTW 剛才有人提醒，「行列30大字集」的最長碼長是5，因為有些罕用字末尾要補`i`鍵。

**Comment by KenLuoTW** [comment]
「行列30大字集」的最大編碼數目問題,下個測試版本會修正。
另外收到泰瑞倉頡作者洪泰瑞先生的回信,所以酷倉的碼表整理過後會換成新的。

```
我整理的碼表取之於網路，自然就應該用之於網路。

所以任何人只要採取免費、開放的方式，

重新整理（我的碼表）後再提供給大眾使用，我是非常歡迎的！

 

剛才有下載並安裝PIME，發現您（們）可能用到我已經多年沒有維護的碼表了！

這個問題也不是只有發生在您這個案例，

看來我要在部落格的相關文章上補充一段特別聲明了！就是：

「泰瑞倉頡輸入法對照表」已經是6、7年前的產物，

因為我當時寫了很多篇舊文章都是根據此對照表而發表的，

所以更新此對照表的話，我擔心有網友下載回去研究後，會發現這些舊文章的數據失準。

如果由我一一檢視、修改這些舊文章的內容，又非常耗時、耗力，所以一直擱著沒去處理。

「泰瑞倉頡輸入法對照表」並不支援CJK Ext-C、CJK Ext-D的字元集，符號的編碼也沒改良過，

因此，請網友不要再下載回去改作！請有心改作的網友，下載「泰瑞版小小輸入法」回去使用。

 

下載完「泰瑞版小小輸入法」，解壓縮後，找到「mb」資料夾裡的「Chajei.txt」，

用文字編輯器開啟後，搜尋「##」就會明白我將字元集、符號集分為哪些段落，

「直通車」這個段落只有配合「小小輸入法平台」才能使用，您可以將之去除。

其餘的部分，應該是符號集還有改良的空間，最近我可能會再重新發布新的版本。
```

**Comment by InSb** [comment]
泰瑞作者也來試用，實在令人欣喜。PIME 現有的泰瑞碼表儘管較舊，但至今也受我們喜愛，這足以看出泰瑞碼表之設計精良。
與時俱進是必要的。出於通用性，要先做出新的 cin 檔，不過更新的難度和複雜度需要評估。
在做出新的 cin 檔之前，還是暫且維持現狀比較好。

另，「泰瑞版小小輸入法」應該有其特殊功能，但實現特殊功能可能要使 checj 的架構複雜化。

**Comment by KenLuoTW** [comment]
輸入法模組全數更新,此次更新內容:
* TextService 所有事件已全部轉移至「CinBase」處理。 (CinBase)
* 修正行列輸入法模組使用「行列30大字集」碼表的最大編碼數目不正確的問題。
* 酷倉輸入法模組更新「酷倉」、「泰瑞倉頡」碼表。 (資料取自最新版的泰瑞版小小輸入法)

目前如果沒 bug 的話,應該可以暫時告一段落,並整合進 PIME 裡了。

**Comment by InSb** [comment]
試了一下最新的泰瑞對照表，感覺很好，尤其是對 CJK 的支援已到了 Ext-D（現今很多字體也只支援到此），打罕用字得心應手。酷倉對照表也是由最新的泰瑞客製而得，很實用。
泰瑞對照表其中有些以符號開頭的編碼，開啟設定中的「`支援 CIN 碼表中以符號字元所定義的編碼`」即可使用。

暫且未發現問題。

**Comment by KenLuoTW** [comment]
因尚未弄清楚蝦米授權問題,所以即日起不再提供蝦米模組的測試版本。

**Comment by KenLuoTW** [comment]
新增了詞庫功能,須要進行測試,故再開啟。

CINBASE 輸入法全數更新,以下為此次更新內容:
* 新增拼音輸入法
* 新增拆錯字碼時自動清除輸入字串功能 (可選)
* 拆錯字碼時發出警告嗶聲提示 (可選)
* 優先以聯想字詞排序候選清單 (可選)
* 輸出字串後顯示聯想字詞 (可選)
* 程式有內建聯想詞庫,資料由泰瑞版小小輸入法提供
* 使用者可另外自訂聯想詞庫並且會優先套用

**Comment by InSb** [comment]
* **拆錯字碼時發出警告嗶聲提示 (可選)**
對於習慣微軟的輸入法的使用者來說，合適。

* **輸出字串後顯示聯想字詞 (可選)**
這個，很多輸入法在選聯想字詞時用的是`Shift+數字鍵`，不過現在這樣也不差。

* **拼音輸入法**
這個拼音輸入法的風格，與注音輸入法的漢語拼音模式類似，且還需要聲調。
還需要進一步商討其功能。


以下可能是不太合用的功能和行為：
* **優先以聯想字詞排序候選清單 (可選)**<br />
其實就個人來講，用形碼很怕候選次序改變。「以聯想字詞排序候選清單」，這也只需要暫時改變一次即可，下一次再打還是碼表中正常的排序。<br />
想法：<br />
打「歌」之後，打`廿田`的第一候選是「曲」，這就是按聯想字詞排序了；不過下一次再打`廿田`則出的還是按照原來碼表的排序。<br />
不知這樣會否更好用。

**Comment by KenLuoTW** [comment]
```
輸出字串後顯示聯想字詞 (可選)
這個，很多輸入法在選聯想字詞時用的是`Shift+數字鍵`，不過現在這樣也不差。
```
其它輸入法幾乎都是使用`Shift+數字鍵`,不過我是覺得能夠少押著 Shift 鍵的話,會更方便點。

```
拼音輸入法
這個拼音輸入法的風格，與注音輸入法的漢語拼音模式類似，且還需要聲調。
還需要進一步商討其功能。
```
拼音有點類似注音,最後是以聲調鍵來結束,不過拼音我不太會拼。
但是其實可以先在 CIN-BASE 下新增一個注音模組來調整,
只要注音在 CIN-BASE 下能夠不難用,那拼音也不會有什麼問題。

我昨天最後有修改拼音,讓它支援 End-Key,而 End-Key 實際上就是聲調鍵。
今天晚點我再釋出一個新版,會包括大易及拼音那兩個新增的功能。

```
以下可能是不太合用的功能和行為：
優先以聯想字詞排序候選清單 (可選)
其實就個人來講，用形碼很怕候選次序改變。「以聯想字詞排序候選清單」，這也只需要暫時改變一次即可，下一次再打還是碼表中正常的排序。

想法：
打「歌」之後，打`廿田`的第一候選是「曲」，這就是按聯想字詞排序了；不過下一次再打`廿田`則出的還是按照原來碼表的排序。
不知這樣會否更好用。
```
這個其實是 bug,昨天我有進行第二次更新,所以已經沒這 bug 了。

**Comment by KenLuoTW** [comment]
輸入法模組全數更新,此次更新內容:

* 新增速成輸入法模組。
* 支援拼音輸入法的 End-Key,現在已可以在輸入 End-Key 後自動顯示候選清單。
* 大易輸入法現已支援字根滿時自動顯示候選清單。

已知問題:
各輸入法首次安裝使用時,一定要進設定裡去按確定,才會套用輸入法預設的設定。

**Comment by InSb** [comment]
以前我也有把速成掛進酷倉模組中來試用，現在有專門的速成模組，方便多了。`優先以聯想字詞排序候選清單 (可選)`這個是幾乎一定要選中的，除非背住了選項位置。

拼音輸入法因 End-Key 支援而好用了很多，可以少打一個`Space`。現在打第一聲的字時要按`Space`，這是碼表的編法，可以接受。

另，不太清楚現在 CinBase 對 cin 檔的支援程度如何，而且 cin 檔本身的規範又不甚好找。

**Comment by KenLuoTW** [comment]
拼音碼表中有泰瑞拼音,它的碼表有將一聲的字,都補上1。

CIN 碼表主要有下面幾個規範:
```
%gen_inp: 主要用來讓輸入法辨識是否為 CIN 碼表。
%ename: 輸入法碼表的英文名稱。
%cname: 輸入法碼表的中文名稱。
%selkey: 輸入法的選擇鍵。
%endkey 輸入法的結束鍵。
%keyname begin & end: 輸入法的字根對照定義。
%chardef begin & end: 輸入法的字元對照定義。
```
CinBase 目前僅支援:
```
%keyname begin & end: 輸入法的字根對照定義。
%chardef begin & end: 輸入法的字元對照定義。
```
CinBase 不支援的原因:
```
%gen_inp: 主要用來讓輸入法辨識是否為 CIN 碼表。
目前並非設計可讓用戶自行套用 CIN 碼表的輸入法,碼表皆由模組作者放置,所以不須辨識。

%ename: 輸入法碼表的英文名稱。
目前並非設計可讓用戶自行套用 CIN 碼表的輸入法,無須辨識及使用此資料。

%cname: 輸入法碼表的中文名稱。
目前並非設計可讓用戶自行套用 CIN 碼表的輸入法,無須辨識及使用此資料。

%selkey: 輸入法的選擇鍵。
輸入法統一使用 0~9 作各種輸入法碼表的選擇鍵。

%endkey 輸入法的結束鍵。
僅有一些碼表有此項目,例如: 注音、拼音,拼音已直接在模組裡處理。
```
簡單來說,如果是設計一款可使用各種 CIN 輸入法碼表的輸入法,
才有須要完整去支援 CIN 裡頭各種資料的定義,因為它資料是由碼表裡取得的。

**Comment by KenLuoTW** [comment]
泰瑞作者已更新了其系列碼表:
http://terryhung.pixnet.net/blog/post/34297035

```
## 大五碼-常用漢字
## 大五碼-次常用漢字
## 大五碼-其他漢字
## 大五碼-符號
## 中日韓統一表意文字-大五碼外字
## 中日韓統一表意文字-符號
## 中日韓統一表意文字-擴展A區
## 中日韓統一表意文字-擴展B區
## 中日韓統一表意文字-擴展C區
## 中日韓統一表意文字-擴展D區
```

新的碼表採用了以上的段落來排序編碼,這是一個非常棒的特色。
以這種方式來排序,代表的是常用字永遠都會優先列出來,
很多大字集的碼表都沒有做到這點,這可免除去翻頁找字的困擾,
尤其是對那些重字率較高的輸入法來說。

我會儘快將其新碼表,更新在現有的輸入法模組裡。

**Comment by KenLuoTW** [comment]
測試版已更新,此次更新內容:

* 修正各輸入法首次安裝使用時,一定要進設定裡去按確定,才會套用輸入法預設的設定。
* 更新酷倉、行列、大易、拼音碼表至泰瑞新版的碼表。

**Comment by HPEACE** [comment]
請問大易的全型標點符號輸入有辦法改回原本大易的方式嗎？  PIM的大易是用 `+鍵盤上的符號 去打
而原始大易是用 =+鍵盤上的符號 去打，有另一種被延用很久的是 '+鍵盤上的符號 去打，PIM的方式是第一次在大易上出現，變得很不習慣，另外選字也是，但用數字鍵選蠻直覺的，要是能改回大易的方式也更好

**Comment by KenLuoTW** [comment]
@HPEACE 下個測試版會變更這些內容,個人本身沒有使用大易,
故一些大易的行為模式比較不清楚,如果有不好用的地方請回報。

另外請參考 #132,未來有關測試版的討論將移至新的地方去討論。

**Comment by HPEACE** [comment]
@KenLuoTW  感謝您的回覆，個人從學生時代就用大易至今，一直以來都是用奇摩輸入法掛大易的碼表，原因就是因為它會依使用者習慣去變更侯選字的位置，希望PIM能有機會把這功能加入就完美了

**Comment by KenLuoTW** [comment]
@HPEACE 
「依使用者習慣去變更侯選字的位置」這個功能有計劃加入,
不過不會這麼快加入,目前著重於已有功能的完善及除錯。
