### ISSUE TITLE
請教關於自由(大新)倉頡覆蓋到酷倉使用的問題！

### ISSUE THREAD

**Issue by sirius95** [EasyIME/PIME#123]
各位朋友好：
          由於自由(大新)倉頡在使用上，有一點點小小的問題，因此在將自由倉頡中的【newcj.cin】檔

copy複製，覆蓋到了酷倉checj資料夾中的cin資料夾裡面的【checj.cin】檔，如此一來果然酷倉也可

以輸出自由（大新）倉頡輸入法，但是由於我很希望自由（大新）倉頡，能夠自定義按鍵，輸出自己

欲輸出的文字或符號等等之類的東西...於是我在自由（大新）倉頡輸入法中的【newcj.cin】檔，以

記事本開啟，在裡面進行編輯，果然是可以自行定義欲輸出的文字或符號，但是欲定義的按鍵英文

必須要小寫英文，不能使用大寫英文，例如說：

rar →

我定義了三個按鍵【rar】（小寫），便會輸出符號【→】

當我發現可以這樣子定義按鍵後，很高興打算如法泡製，想在酷倉輸入法中，去修改【checj.cin】這

個檔案，一樣在裡面自定義按鍵及欲輸出文字或符號，結果測試了幾次都失敗

不知是該在哪個檔案進行修改，才可以如我所要的那樣，可以自定義按鍵來輸出文字或符號呢？

再麻煩各位朋友為我解惑，謝謝～感激不盡～

**Comment by lyenliang** [comment]
輸入法程式重新讀一次 *.cin 檔，自定義的字才會生效。

自由大新倉頡要切換到其它輸入法再切回來才能重讀 newcj.cin，酷倉似乎要到「設定」切成其它種倉頡，然後再切回酷倉才行。

![cj_setting](https://cloud.githubusercontent.com/assets/3468329/16606190/784ec8a0-4368-11e6-9df0-9fee4bd38c7d.png)

**Comment by KenLuoTW** [comment]
@lyenliang 說的方法是正確的,變更輸入法碼表後,酷倉才會重新載入新的碼表。
會這樣做的原因很簡單,只為了效率及資源占用,繁複地載入碼表至記憶體,會嚴重影響輸入時效率。

**Comment by sirius95** [comment]
@lyenliang @KenLuoTW 
太感激你們二位的幫忙，果然重新載入輸入法碼表時，已可以很順利的使用自定義的輸出文字或符號了

其實我會想這樣子用是因為，我一部電腦是win7，在這部我曾有裝大新倉頡輸入法，它本身可以自定義

按鍵來輸出文字或符號，那時我大概建立了十幾個與預設的按鍵不一樣的自定義按鍵來輸出一些文字或

符號，這算是我滿常使用的幾串文字與符號，但在另一部電腦是win10系統，則無法正常使用我原本的

大新倉頡輸入法，在尋找了很久之後，聽網友的告知才知道原來pime也有大新倉頡，可以正常在win10

使用，現在也可以自定義過去常用的一些按鍵文字串或符號，真是幫了我很大很大的忙～

再次感謝你們的大力幫助，萬分感激～謝謝你們～^^

**Comment by KenLuoTW** [comment]
提醒一下大新倉頡要啟用「支援 CIN 碼表中以符號字元所定義的編碼」項目,
才能完整支援以符號字根編碼的資料。

下個正式版本,大新倉頡會直接整合進酷倉模組,
並且 CIN 內的編碼資料,也可以不區分大小寫撰寫。

**Comment by KenLuoTW** [comment]
因尚未弄清楚蝦米授權問題,所以即日起不再提供蝦米模組的測試版本。
