### ISSUE TITLE
請教關於倉頡拆錯碼時所產生的問題

### ISSUE THREAD

**Issue by sirius95** [EasyIME/PIME#124]
各位朋友好：

不好意思，又有一個小問題想要請教大家一下，就是當我使用自由（大新）倉頡時，

若我在拆碼的過程中，字碼若打錯的話，它是會顯示（查無字根）

但是之後，還得必須按**【backspace】**鍵來消除拆錯的字碼，因此在想，是否有辦

法可以在拆錯字碼（查無字根）之後，可以自動清空字碼，如此一來只要自己再重

新輸入正確字碼即可呢？

謝謝大家

**Comment by InSb** [comment]
按 Esc 鍵就可以了。

**Comment by KenLuoTW** [comment]
已更新於 https://github.com/EasyIME/PIME/commit/3121f721b491bf5be94073b253772ca780ba97d7, 請等待下個 PIME 正式版:

新增2個選項設定:
* 拆錯字碼時自動清除輸入字串
* 拆錯字碼時發出警告嗶聲提示
各 CinBase 輸入法模組皆會有這兩個可選功能。

**Comment by sirius95** [comment]
非常感謝你們的幫忙～
