### ISSUE TITLE
Debug in Linux python

### ISSUE THREAD

**Issue by osfans** [EasyIME/PIME#125]
除了UI，有沒有可能在Linux中debug candidate之類的？
習慣了Linux的開發環境。

**Comment by PCMan** [comment]
目前無法支援，因為底層 IPC 使用 Windows 專有的 APIs

**Comment by yanganto** [comment]
好希望有linux的版本

**Comment by PCMan** [comment]
@yanganto @osfans 隨著最近的 ipc 架構改變，移植 Linux 現在變成技術上可行了。
只不過是否值得這樣做，就有待商榷。Linux 上的輸入法開發環境多如牛毛，fcitx, ibus, scim, ...都支援自己寫模組擴充，何況功能都非常完整，而 ibus 本身就是用 python 開發，完整度也勝過 PIME。
雖然技術上做得到，但多套上一層 PIME 在這些框架之上，不見得符合效益。

**Comment by osfans** [comment]
對哦 我看看有沒有可能弄個linux的cmdline

**Comment by PCMan** [comment]
現在 python 部份ipc是透過 stdio，所以在 linux 下除錯可以實現了
