### ISSUE TITLE
有時無法選字

### ISSUE THREAD

**Issue by J4X0N** [EasyIME/PIME#127]
目前使用0.13.1版，有時按「下方向鍵」要選字卻沒反應，無法選字，有其他人有同樣狀況嗎？

由於之前是使用微軟新注音輸入法

所以設定裡的「空白鍵選字」功能沒有打勾，不太習慣用空白鍵選字

**Comment by J4X0N** [comment]
最近又遇到好以次這種狀況

我異想天開按了一下空白(當然我沒開選項所以無法選字，會多一格空白)

但是發現好像這樣就可以按「下方向鍵」選字了

會不會是按鍵有衝突到呢？

再研究看看

**Comment by PCMan** [comment]
目前版本已經無此問題。
