### ISSUE TITLE
V0.09 + Win10 系統快速鍵失效

### ISSUE THREAD

**Issue by cwchiu** [EasyIME/PIME#13]
原本想複製一段文字到 notepad++ 編輯, 發現

1. Ctrl+C 失效
2. Ctrl+V 失效
3. Ctrl+N 失效
...

切回微軟注音就正常

**Comment by jessy1092** [comment]
@lyenliang 之前那個 issue #8 狀況如何?

**Comment by lyenliang** [comment]
@jessy1092 我剛剛在[issue 8](https://github.com/EasyIME/PIME/issues/8)回應了

**Comment by chchwy** [comment]
V0.09 + Windows 8 
提供一些線索
1. 安裝後第一次輸入法時，沒辦法使用 Ctrl+C, Ctrl+V  複製貼上
2. 打開「設定新酷音輸入法」，此時「按住 Ctrl 輸入快速符號」並沒有勾選，打勾並保存。
3. 再打開一次「設定新酷音輸入法」，取消勾選「按住 Ctrl 輸入快速符號」並保存
4. Ctrl+C, Ctrl+V  複製貼上恢復正常

**Comment by cwchiu** [comment]
@chchwy 的操作在 Windows10 同樣有效, 應該是相同問題

**Comment by lyenliang** [comment]
我在windows7把C:\Users\user_name\PIME刪掉並反安裝PIME後，一樣能重現這個問題

**Comment by lyenliang** [comment]
我發現這是因為`PIME\server\input_methods\chewing\chewing_config.py`的`self.easySymbolsWithCtrl`是`True`，但`PIME\server\input_methods\chewing\config\js\config.js`裡的`easySymbolsWithCtrl`是`false`的關係，把兩個調整到一樣就可以解決問題。

**Comment by PCMan** [comment]
Fixed in v0.10.
