### ISSUE TITLE
開發討論移到專區，PIME issue tracker 留作 bug report 用

### ISSUE THREAD

**Issue by PCMan** [EasyIME/PIME#132]
有鑑於本專案開發者和使用者開始增加，經常有互相溝通討論的需求
但 issue tracker 本來是用作追蹤 bug/issues 用途
較不適合用於當作 forum or mailing list 使用，容易造成 bug 管理困難
剛成立了 PIME Development 用的 google groups 用來討論
https://groups.google.com/forum/#!forum/pime-develop
@KenLuoTW @jessy1092 @timtan @lyenliang 
建議接下來可以用 groups 討論，協調新點子和 release schedule 等等
Thanks!

**Comment by jessy1092** [comment]
@PCMan 我是覺得討論移到 google groups 有時兩個平台難以做相關連，比如跨 issue 討論，就無法互相連結。

可以仿造 nodejs 社群的做法，開個 repo 專門做討論、roadmap、release schedule ?

ex.
https://github.com/nodejs/LTS : release 的討論
https://github.com/nodejs/help : 一般使用者的使用上的疑問

這樣也可以使用 github relative 的功能方便指出 commit , issue, pr 等等，這樣如何呢? 可以切開 bug tracking ，又可以有 googlue groups 的功能

**Comment by PCMan** [comment]
@jessy1092 這主意不錯耶，單純只是覺得討論不要跟 bug tracking 混在一起，這樣管理上很困難，而且很多事情其實是需要協調，例如我們大家在做不同部份，到底什麼時候是大家都覺得可以發新版，各自部份又測試得怎樣了，需要有個地方可以討論。
雖然開 repo 來「討論」其實是濫用 github 的方法，但是聽起來確實很方便
如果其他開發者都贊成，那麻煩你幫開一個，我去把 google groups 刪掉

**Comment by jessy1092** [comment]
@KenLuoTW @timtan @lyenliang 覺得如何呢?  

如果決定 github ，我就先開一個 EasyIME/forum ，就可以開 issue 討論各個事項 
(各個輸入法討論、使用者需求、未來發展、開發時程等等。)

其實 github 也沒限制不能這樣用 XD 
目前想到好處是
- 討論後也可以把事項寫在 README 或是其他檔案，供使用者參考。
- `討論` 有版本控制的功能。
- 把 `討論` 當成 issue tracker 方便事後追蹤。
- 可以對 `討論` 做 標籤、負責人、相關 commit 等等

**Comment by KenLuoTW** [comment]
Github 方案好~ 贊成+1

**Comment by PCMan** [comment]
目前開發者過半贊成，我剛先把 google groups 刪了，@jessy1092 請開 github 吧

**Comment by jessy1092** [comment]
開了 https://github.com/EasyIME/forum
