### ISSUE TITLE
 建議增加輸入法

### ISSUE THREAD

**Issue by winnieking** [EasyIME/PIME#136]
可以增加輕鬆輸入法嗎？謝謝

**Comment by KenLuoTW** [comment]
下個正式版本會加入。

**Comment by winnieking** [comment]
謝謝你，我可以提供cin檔案
https://www.dropbox.com/s/ropleupy23k7170/ezyahoo.cin?dl=0

**Comment by KenLuoTW** [comment]
已新增輕鬆輸入法模組於 https://github.com/EasyIME/PIME/commit/2d8e84bbcc3f2c6696cabce7286aebf448830f15 。
