### ISSUE TITLE
是否可以不附cin表格的方式支援無蝦米？

### ISSUE THREAD

**Issue by focusime** [EasyIME/PIME#137]
使用版本：0.14
如題，PIME目前顯然有一定的成熟度
如果因為板權的問題不能支援無蝦米實在太可惜了
所以不知道有沒有可能出一個無蝦米的模組但不附cin表格
對於有購買的人可以自行轉成cin表格放入，如此可以避免法律問題，又可服務有需要的人，應是比較權宜的作法
偷偷說：其實我現在就是套用酷倉的模組在使用無蝦米@@，不過看到明明是無蝦米卻叫做酷倉，圖示也是個「倉」字，感覺就是怪怪的= =

**Comment by KenLuoTW** [comment]
暫時還沒有確認有沒有版權上的問題,等確認之後,才會決定新的解決方案。

另外目前蝦米模組源碼是存在的,只是沒有附表格,如果你會自行修改並加入的話,可以看看:
https://github.com/EasyIME/PIME/tree/master/python/input_methods/cheliu

蝦米碼表直接用在酷倉模組上,不會有什麼大問題,就是名稱和圖示不同而已。
