### ISSUE TITLE
升級到0.14版之後，大新倉頡無法自定義字的問題！

### ISSUE THREAD

**Issue by sirius95** [EasyIME/PIME#138]
朋友們好：
          先前還在用0.13版時，我有提問一個問題是【請教關於自由(大新)倉頡覆蓋到酷倉使用的問題！ 】

那個問題現在已在（close）那邊了，當初內容是提到，就是把大新倉頡位在：

Program Files (x86)\PIME\server\input_methods\newcj 裡的《newcj.cin》檔，copy下來，然後改檔名成

《checj.cin》，然後覆蓋到：Program Files (x86)\PIME\server\input_methods\checj\cin 資料夾之中～

然後到【設定法輸入模組】之中，將【輸入法碼表】，先隨便切換到其它輸入法，確定完成後，再重覆

上述步驟，然後再將輸入法切換回【酷倉】，如此一來，輸入法狀態就算是酷倉，亦可打出大新倉頡的

拆碼方式，並且在cin檔之中，我當初也有自定義按鍵，可以打出我想要的文字或符號之類的～

可是問題來了～就在升了0.14版之後，如先前朋友們有提到說，新的版本將會把大新倉頡整合到輸入法

碼表之中，由於我有備份先前在用0.13版時的【checj.cin】跟【newcj.cin】這兩個檔，因為這兩個檔案裡

面有我自定義的資料，本來我想說，升級到0.14版之後，將這兩個檔，覆蓋到上述那兩個路徑之中，但

是似乎是失效了，自定義的文字或符號也都無法出現。因此不知問題是出在哪裡～再麻煩各位朋友指導

我一下解決方法，麻煩你們了，感激不盡！謝謝～

**Comment by sirius95** [comment]
不好意思，我剛發現了一個情況，就是

在【設定輸入法模組】之中，我將《支援cin碼表中以符號字元所定義的編碼》這一個選項打勾的話，

就可以打出我自己定義的文字或符號了，可是也發生了一個情況

那就是，當我在拆碼時，輸入了（，）或（。）符號時，變成還得再按一下空白鍵才行輸出逗號或句

號。因此希望除了可以輸出自定義文字或符號外，在輸入（， ）或（。 ）之類的符號時，不用再按

空白鍵即可，再麻煩你們了，感激不盡，謝謝！

**Comment by KenLuoTW** [comment]
大新倉頡其實是要啟用「支援cin碼表中以符號字元所定義的編碼」才能完全支援其所有定義,
沒有強制讓大新倉頡啟用,主要是想讓用戶有選擇的權利。

至於要直接打「,」出「，」,或打「.」出「。」,
這個要以後支援組字編輯區時才會支援直接出字,目前不可能為此去除對 CIN 碼表的原本定義。

如果你要在目前版本,直接打「,」出「，」,或打「.」出「。」,
請自行從大新倉頡碼表裡去除以下資料:
```
,, ！
,,e Ⅲ
,,i Ⅷ
,,o Ⅸ
,,p Ⅹ
,,q Ⅰ
,,r Ⅳ
,,t Ⅴ
,,u Ⅶ
,,w Ⅱ
,,y Ⅵ
```
```
.. ．
.. ‧
.. ﹒
.. ·
.. ﹕
.. ‥
.. …
... …
..; ‧
..;; ﹒
..;;; ·
..[ ○
```

至於要怎麼輸入這些資料裡的符號,請自行另外定義。
因為都已經選擇要直接出字了,也就不可能有辦法以這些編碼去輸出那些符號。

**Comment by sirius95** [comment]
謝謝你，我了解了，感激不盡！

**Comment by KenLuoTW** [comment]
這部份的功能沒有問題,如果要討論應用上的問題請移至 PIME 討論區討論,
[https://github.com/EasyIME/forum](https://github.com/EasyIME/forum)

並且提供更多資訊,因為上面你也沒提出詳細的操作步䮕。
