### ISSUE TITLE
在Acrobat reader DC中無法使用

### ISSUE THREAD

**Issue by storyofwind** [EasyIME/PIME#139]
在Acrobat Reader DC中搜尋或新增註解時，無法使用新酷音輸入中文
已安裝之其他輸入法：google日文輸入法
新酷音版本：PIME 0.14
Acrobat Reader DC版本：15.017.20050
OS: Windows 10
謝謝

**Comment by zongxinbo** [comment]
win7 下也无法使用

**Comment by PCMan** [comment]
從設定關閉 Adobe Reader 保護模式即可。
相關的 registry
[HKEY_CURRENT_USER\SOFTWARE\Adobe\Acrobat Reader\10.0\Privileged]
"bProtectedMode"=dword:00000000

@KenLuoTW 你覺得我們有需要在安裝程式也提供關閉 Adobe Reader 保護模式嗎? 跟 IE 同一頁

**Comment by PCMan** [comment]
duplicate
