### ISSUE TITLE
0.14 大易問題

### ISSUE THREAD

**Issue by HPEACE** [EasyIME/PIME#140]
更新 0.14後，有幾個問題...
1. 搞不太懂cin檔吃的是 \server路徑下的 還是 \python路徑下的
2. 我另有替換 \python路徑下cin檔，但cin檔內明明就只有一個編碼，但卻出現二個候選字，如 /s，就會出現二個卑的候選字
3. 改了cin檔內的編碼後，TASKKILL /F /IM PIMELauncher.exe TASKKILL /F /IM pythonw.exe 並重啟PIMELauncher.exe 結果新加入的字還是沒辦法打出來

附上我修改後的大易碼表供測試
https://drive.google.com/file/d/0B9O-npkeHuleMFFIbTJxNVdEX28/view?usp=sharing

**Comment by KenLuoTW** [comment]
１. 下面這個路徑是舊版才有用到的資料夾,新版的安裝程式解除安裝時不會去移除它。  
新版已完全沒有利用到這個資料夾,可以直接將它整個刪掉。
```
C:\Program Files (x86)\PIME\server\
```

---

２. 我套用你的碼表後,沒發現有這問題喔。
![2016-07-19](https://cloud.githubusercontent.com/assets/12954277/16938712/52a4c628-4dad-11e6-9ae9-f0f93bc683ce.png)

---

３. 你是指下面那段裡`~~~略`裡所定義的編碼嗎?
```
##====下面是我自己加的====
~~~略
##	大易四碼-大五碼-常用漢字：
```
如果是那段裡頭的自訂編碼,要核取「支援 CIN 碼表中以符號字元所定義的編碼」才能輸入。
大易的話,請不要將此項目取消核取,因為大易是有以符號字元作為組字字元的。
你自訂的編碼中,僅有「` 巷」無法套用,因為已被多功能前導字元功能取代了。

**Comment by HPEACE** [comment]
1. 了解
2. 原來 TASKKILL /F /IM PIMELauncher.exe TASKKILL /F /IM pythonw.exe 並重啟PIMELauncher.exe 這個部份要用系統管理員執行
3. 了解

**Comment by KenLuoTW** [comment]
若還有使用上的問題,歡迎至 [PIME 討論區](https://github.com/EasyIME/forum) 討論。
