### ISSUE TITLE
0.14版，「特殊符號」和「簡易符號輸入」的功能仍「不穩定」

### ISSUE THREAD

**Issue by ilovepcYan** [EasyIME/PIME#144]
家中電腦，這兩個功能一直是正常的（全新安裝Win10中文版）
公司電腦，這兩個功能從0.13版之後失效（升級版Win10中文版），只能使用預設的設定，自行改的設定在「設定新酷音輸入法中」看到時是正常的，但是套用或是按下確定後，還是使用原始的安裝設定。
但是「簡易符號輸入」的左邊改小寫，則功能卻又完全失效

**Comment by KenLuoTW** [comment]
同 #143

**Comment by storyofwind** [comment]
0.16.1也遇到這問題
「設定新酷音輸入法」中，只有「特殊符號」和「簡易符號輸入」無法修改設定。
OS: windows 10 版本1511 組建 10586.753

**Comment by KenLuoTW** [comment]
無法修改設定的問題已修復。
大小寫的問題請關注 #143。
