### ISSUE TITLE
「`」特殊符號的最後一個，呼叫時會當掉

### ISSUE THREAD

**Issue by cyping** [EasyIME/PIME#147]
特殊符號的使用，其他項的符號呼叫都正常，
但就是在最後一項(內定為[線段]，如果手動更改或新增的，則就是改過的最後一項)
呼叫時會當掉

**Comment by KenLuoTW** [comment]
已確認是 bug,好像是最後一定須要斷行才會正常,
到時在儲存設定時自動多加一空白行,看看能不能修正。

**Comment by KenLuoTW** [comment]
已修正此問題。
