### ISSUE TITLE
逗號輸入問題

### ISSUE THREAD

**Issue by atxps2** [EasyIME/PIME#148]
請問逗號0.14版要怎麼打?之前使要按SHIFT+<就可以打出來,現在都沒有辦法打了.....還要先切換到英文輸入才可以打，感覺很麻煩....

**Comment by KenLuoTW** [comment]
這要請以前就有用的新酷音的用戶來回答,因為我個人是覺得現在新酷音的處理方式是沒錯的。

**Comment by ottokang** [comment]
中文模式下預設全形，按SHIFT+<是輸出"，"，預設半形是輸出"<"，這是新酷音本來的設定，微軟新注音也是如此

**Comment by J4X0N** [comment]
我這邊也有一樣問題
全形輸入是＜
半形輸入是<

但「設定」>「打字行為」>「按住SHIFT輸入全形標點符號」打勾後變成
全形輸入，
半形輸入也是，

**Comment by ottokang** [comment]
新增選項 #306
