### ISSUE TITLE
自由大新選字欄位空白過大

### ISSUE THREAD

**Issue by callinner** [EasyIME/PIME#150]
使用自由大新，當輸入的字根有較長的詞時，其他詞的欄位會跟著變大，
造成空白過多，這點能夠修正嗎？
![default](https://cloud.githubusercontent.com/assets/20582557/17032247/d5a2cdc8-4faa-11e6-9c49-54a470659333.png)
正常如下
![1](https://cloud.githubusercontent.com/assets/20582557/17032328/3c1dc012-4fab-11e6-9075-132bfc899e22.png)

**Comment by KenLuoTW** [comment]
這個間隔空間,不是由模組這邊控制,加上 PIME 下的候選清單可以調整為直式或橫式,
所以依每字去調整間隔空間可能會比較麻煩或是根本不能改變。

不過我倒是可以在模組加入一功能,例如說「自動隱藏大於1字的候選清單字串」.
然後看是要用什麼方法,再將這些被隱藏的字串顯示出來。

方法我目前沒想到,歡迎大家提供建議,如果有好方法,那這個功能將可以很快做出。

**Comment by shunmx** [comment]
建议参考搜狗输入法输入长词的做法：
1、其他候选字直接根据自己字长选定范围
2、主候选字超过多少字符时，用..省略。比如“方法我目前沒想到,歡迎大家提供建議,如果有好方法,那這個功能將可以很快做出”
仅仅显示："方法我目前沒想到......"这个应该好解决。
第一个做法也希望可以试试，只在横盘做这个调整

**Comment by osfans** [comment]
只有一排的話，各個詞語的寬度可以不相等。
