### ISSUE TITLE
在注音的倚天鍵盤下，打出ㄘ和ㄦ有困難

### ISSUE THREAD

**Issue by xcrewdriver** [EasyIME/PIME#153]
版本：PIME 0.14

在注音的倚天鍵盤排列下，若輸入第一個按鍵是「'」（要打出ㄘ，例如：存在），則不會出現注音ㄘ，只會在螢幕上出現'
同樣，若輸入第一個按鍵是「=」（要打出ㄦ，例如：兒童），也不會出現注音ㄦ，只會在螢幕上出現=

提供給開發者參考。
謝謝。

**Comment by KenLuoTW** [comment]
這功能與「支援 CIN 碼表中以符號字元所定義的編碼」有關,注音輸入法請不要停用此項目,
新的測試版本 https://github.com/EasyIME/forum/issues/3 有將這功能反白,不讓用戶變更,並且預設啟用。

**Comment by xcrewdriver** [comment]
收到，謝謝你的說明。
