### ISSUE TITLE
有關定制輸入法行為問題

### ISSUE THREAD

**Issue by KennethWong355** [EasyIME/PIME#155]
[版本：0.14]

KenLuoTW ，你好：

我想把輸入法的候選字輸出個人化， 例如酷倉輸入法，現在打 “日”字， 只會出現 ‘’日‘’ 跟 ‘’曰‘’ 這
兩個字，但我想打 ‘’日‘’字的時候， 所有 “日" 字開頭的 字都會出現在候選字選單， 就如 (aaa 的 “晶") 和
 (aitc 的“曠”) 。
---------------------------------------------checj.cin --------------------------------------------------
a 日
a 曰
aa 昌
aaa 晶
aamh 暘
...
aitc 曠
---------------------------------------------checj.cin END ---------------------------------------------

我嘗試過對  “cin.py” 的  ”def getCharDef(self, key)”  作不同的修改，可是修改完打字就當機，
請問可以怎樣修改？

原本的 def getCharDef(self, key)：
def getCharDef(self, key): 
      return self.chardefs[key]

修改版本A：
def getCharDef(self, key):
return next( v for k,v in self.chardefs.items() if k.startswith(key))

修改版本B：
result=[]

def getCharDef(self, key):
        for d in self.chardefs.keys():
            if key == d[0]:
               result.extend(self.chardefs[d])
return result

修改版本C：
aCharDefTempList =[]
bCharDefTempList =[]
cCharDefTempList =[]
dCharDefTempList =[]
eCharDefTempList =[]

def getCharDef(self, key):
aCharDefTempList = self.chardefs[key]
bCharDefTempList = self.chardefs[key+key]   
cCharDefTempList = self.chardefs[key+key+key]
dCharDefTempList = self.chardefs[key+key+key+key]
eCharDefTempList = self.chardefs[key+key+key+key+key]
return list(itertools.chain(aCharDefTempList, bCharDefTempList, cCharDefTempList, dCharDefTempList, eCharDefTempList))

**Comment by KenLuoTW** [comment]
在酷倉的 “cin.py” 的 ”def getCharDef(self, key)”,每行我都做了註解,應該不難看懂:
```
    def getCharDef(self, key, candMaxItems):
        keylength = len(key) # 先取得目前 key 的長度
        chardefslist = [] # 先定義一個 list,作為之後返回結果使用
        chardefslist.extend(self.chardefs[key]) # 優先加入完全符合目前字根的對照字元
        for chardef in self.chardefs: # 遍尋 self.chardefs 裡的 key
            if key == chardef[:keylength]: # 如果遍尋中的 key, 前幾個字元符合目前字根
                for char in self.chardefs[chardef]: # 遍尋符合目前字根裡的對照字元
                    if not char in chardefslist: # 如果對照字元不在返回的 list 裡
                        chardefslist.append(char) # 加入對照字元
                    if len(chardefslist) >= candMaxItems: # 如果返回的 list 項目大於「最大候選字個數」
                        return chardefslist # 直接返回結果
        return chardefslist # 遍尋結束,返回結果
```
無註解版:
```
    def getCharDef(self, key, candMaxItems):
        keylength = len(key)
        chardefslist = []
        chardefslist.extend(self.chardefs[key])
        for chardef in self.chardefs:
            if key == chardef[:keylength]:
                for char in self.chardefs[chardef]:
                    if not char in chardefslist:
                        chardefslist.append(char)
                    if len(chardefslist) >= candMaxItems:
                        return chardefslist
        return chardefslist
```
* candMaxItems 就是功能設定裡的「最大候選字個數」。
 * 因為 PIME 的候選清單項目數量太多時,會顯示得很慢,所以要限制。

以這個函式取得的字元,沒有照 CJK 常用字排序,所以可以參考後方的 getWildcardCharDefs 函式裡對 CJK 字元區段的處理,將之加進這個函式裡,或是另外寫一個共用函式,讓這兩個功能共用一個CJK常用字處理函式即可。

cinbase 下的 __init__.py 要改成:
```
candidates = CinBaseTextService.cin.getCharDef(CinBaseTextService.compositionChar, CinBaseTextService.candMaxItems)
```

**Comment by KennethWong355** [comment]
_看懂了，謝謝。_

**Comment by KennethWong355** [comment]
還有一個問題我想問問，這個project 是不是沒法運行 “Debug 模式” ？（如果能運行Debug 模式的話， 應該怎麼運行？）


我試過在 （cinbase 下的 __init__.py）  和 （cin.py）加  logging，在任何一個加logging， 運行輸入法就會當機， 想寫 logging 來 Debug要怎麼辦？

#  __init__.py 加  logging

import winsound
**import logging** 
from .swkb import swkb

....

class CinBase:
    def __init__(self):
        self.cinbasecurdir = os.path.abspath(os.path.dirname(__file__))


  # 初始化輸入行為設定
    def initTextService(self, CinBaseTextService):
        # 使用 OpenCC 繁體中文轉簡體
        CinBaseTextService.opencc = None
        CinBaseTextService.langMode = -1
.
.
.       
        **LOG_FILENAME = 'tsfLog.log' 
        logging.basicConfig(filename=LOG_FILENAME,level=logging.DEBUG)**
.
.
.
            # 組字字根超過最大值
            if len(CinBaseTextService.compositionChar) > CinBaseTextService.maxCharLength:
                if CinBaseTextService.cin.isInKeyName(CinBaseTextService.compositionChar[len(CinBaseTextService.compositionChar)-1:]):
                    keyLength = len(CinBaseTextService.cin.getKeyName(CinBaseTextService.compositionChar[len(CinBaseTextService.compositionChar)-1:]))
                else:
                    keyLength = 1
                CinBaseTextService.setCompositionString(CinBaseTextService.compositionString[:-keyLength])
                CinBaseTextService.compositionChar = CinBaseTextService.compositionChar[:-1]
                if CinBaseTextService.cin.isInCharDef(CinBaseTextService.compositionChar) and CinBaseTextService.closemenu:

**logging.debug('Before enter function')**	
candidates = CinBaseTextService.cin.getCharDef(CinBaseTextService.compositionChar, CinBaseTextService.candMaxItems)


---------------------------------------------------------------------------------------------------------------

#  cin.py 加 logging

from __future__ import print_function
from __future__ import unicode_literals
import re
**import logging** 

def __init__(self, fs):
    state = PARSING_HEAD_STATE
    **LOG_FILENAME = 'tsfLog.log' 
    logging.basicConfig(filename=LOG_FILENAME,level=logging.DEBUG)**
.
.
.

def getCharDef(self, key): 
**logging.debug('Enter function getCharDef()')**
return self.chardefs[key]

**Comment by KenLuoTW** [comment]
其實 Python,我是接觸了 PIME 後才開始學的,之前沒碰過,所以很多功能我還沒完全了解。
我開發及除錯基本上就只用 [Notepad++](https://notepad-plus-plus.org/) 及 [ConEmu](https://conemu.github.io/)。
因為 Python 出錯後,其 Console 裡,就會顯示出錯的函式及行數了,所以幾乎不用多寫一些用來除錯的代碼。

![2016-07-28](https://cloud.githubusercontent.com/assets/12954277/17208769/97b9441e-54ec-11e6-82e0-bdced6fd04f8.png)
