### ISSUE TITLE
一裝好只要碰到任何需輸入的地方就出現錯誤, 差點讓電腦無法使用必須重灌 Windows 

### ISSUE THREAD

**Issue by jimmychao** [EasyIME/PIME#161]
機器: Toshiba R30-A
Windows 10 Home
PIME 0.14版  只裝 新酷音 酷倉 速成
都是原始設定, 因為還來不及進去做任何設定

剛下載一裝好, 還沒來得及設定, 一點瀏覽器就出現錯誤視窗

視窗標題: pythonw.exe - 無法找到輸入點
視窗內容: 無法找到程式輸入點 _except1 (在動態連結程式庫 C:\Program Files(x86)\PIME\python\opencc\opencc.dll)

然後就必須關閉瀏覽器

接下來無論滑鼠點到哪, 都會出現上面的錯誤
後來連點"設定"都不行, 重開了兩三次一進入 Windows 就開始當住, 幾秒後出現上面錯誤
點設定都沒有反應
重開都是靠硬體電源鍵, 不然連重新啟動都無法點

看起來是只要有 trigger 到輸入法的地方, 就會這樣
(不過很奇怪的是 login 畫面正常  可以輸入密碼)

因為電腦什麼事都不能做了, 點什麼都會當, 差點打算用修復光碟做系統的復原或重灌

最後想說點'控制台'好像控制台不需要輸入, 之後等很久終於突然出現控制台了, 就很快進去移除輸入法,
雖然剛移除完還是會, 但再重開之後, 我馬上解除安裝 PIME 輸入法 再重開, 才恢復正常

我在另一台 Windows 7 用得很順, 才灌到我的新筆電 Windows 10
希望能解決這個問題,
(下次安裝前我要先備份)

謝謝!

**Comment by jimmychao** [comment]
忘了說  是 64-bit Windows 10 Home

**Comment by jimmychao** [comment]
有需要任何資訊或協助debug可以跟我說, 謝謝!

**Comment by PCMan** [comment]
這其實不是我們的 bug
你的系統應該不明原因，缺少某些特定版本的 VC++ runtime
http://stackoverflow.com/questions/21617529/procedure-entry-point-except1-could-not-be-located-in-msvcr120d-dll
https://www.reddit.com/r/Rodina/comments/4dtl6h/procedure_entry_point_error/
_except1 找不到，似乎是常見問題

**Comment by osfans** [comment]
所以應該提示下依賴哪些VC++庫？

**Comment by jimmychao** [comment]
我的筆電剛買沒多久, 買了就從乾淨的 Win8 升到 Win10, 後來就只有灌少數自己用的程式,

想說如果乾淨的電腦反而不行, 是否輸入法安裝程式能提供訊息讓使用者知道還需要安裝什麼?
不然乾淨的電腦一裝就幾乎整台電腦無法使用, 感覺蠻嚴重的.

不然可否麻煩您提供需要哪個版本的 VC++ runtime, 或是你們是用哪個VC版本發展/編譯的?

剛剛交叉比對了一下, 利用下面網址提供的檢查版本方法
http://stackoverflow.com/questions/12206314/detect-if-visual-c-redistributable-for-visual-studio-2012-is-installed

我可以的  Windows 7 公司筆電, 裝了 2005 x64, 2010 x64
出問題的 Windows 10 家用筆電, 裝了 2005 x86, 2010 x86/x64, 2012 x86/x64

所以看起來是缺 2005 x64 ?

謝謝! 辛苦你了!

**Comment by KenLuoTW** [comment]
OpenCC 須要 VC++ 2013 runtime (x86)。
Python 須要 VC++ 2015 runtime (x86)。

這些在安裝 PIME 時,安裝程式會去檢測並安裝。
你發生問題的原因可能是微軟升級沒弄好,導致這些 DLL 雖然檔案存在,但沒有登錄至系統。

採用升級安裝的 Win10 還有很多疑難雜症,其實不是很穩定的系統,全新安裝 Win10 後就不會有這些問題。現在 Win10 的 RS1 版本已出,如果之前是採用升級的方式升到 Win10,現在剛好是一個重灌的好時機。

**Comment by PCMan** [comment]
我這兩天來找時間看能不能自己編譯 opencc，他編譯還滿麻煩，我第一次嘗試編譯失敗，所以才用現有的 binary，如果可以編成 vc++ 2015，就不需要 2013 runtime 了

**Comment by osfans** [comment]
編譯的問題，我想 @Prcuvu

**Comment by PCMan** [comment]
opencc 再最新 git 內已更新過
