### ISSUE TITLE
高解析螢幕顯示小視窗

### ISSUE THREAD

**Issue by kekwowse01** [EasyIME/PIME#164]
剛裝 PIME 0.14版. 發現PIME 0.14好像沒運用到Win10裡的scaling功能. 所以在高解析度的環境下, 因為保留了原本pixel大小而沒有根據高解析度調整, 所以變得很小. 

目前測試發現受影響的有
> 整個選字視窗
> 設定視窗的check box

使用界面：
Asus ux303ub 
Win 10 Home x64 英文版
3200x1800 解析度
200% scaled

![pime v0 14 nonscaled window - a](https://cloud.githubusercontent.com/assets/20890266/17463991/7eca95a2-5c99-11e6-944e-bb393f77bcec.png)

![2016-08-07_123129](https://cloud.githubusercontent.com/assets/20890266/17464055/20e1837c-5c9b-11e6-9abd-86fb41c366fb.png)

**Comment by kekwowse01** [comment]
我發現設定裡可以改變選字視窗的大小. 解決小視窗的問題. 不好意思沒查清楚就回報.... 雖然設定視窗的check box還是相對小, 但不影響使用～

**Comment by osfans** [comment]
Writing DPI-Aware Desktop and Win32 Applications
https://msdn.microsoft.com/zh-tw/library/windows/desktop/dn469266(v=vs.85).aspx
