### ISSUE TITLE
大易輸入法候選字視窗無法消失問題

### ISSUE THREAD

**Issue by kinwind** [EasyIME/PIME#165]
大易輸入法候選字視窗在打完句子的最後一個字後，如果沒有打任何字的情況下它會無法消失，
會一直顯示在畫面上

**Comment by KenLuoTW** [comment]
正常你輸入完字,就不會有候選清單,如果你指的是聯想字的候選清單,那個本來微軟也是要再隨便打個字它才會消失,該功能只是為了符合微軟的輸入方式而弄出的,基本上沒多大用處,一般使用覺得麻煩的話,將「中文模式下輸出字串後顯示聯想字詞」關閉即可。

離開該視窗程式,候選清單不會消失的問題,是 PIME 平台的問題,所以模組無法處理。

**Comment by osfans** [comment]
似乎`onCompositionTerminated`也不能處理這個離開後候選清單不會消失的問題

**Comment by KenLuoTW** [comment]
請將以下檔案先備份起來:
```
C:\Users\你的用戶名稱\PIME\chedayi\config.json
```
然後將此檔刪掉，刪掉以後如果還是發生相同狀況，請將此檔附件上來。

也可以試看看使用 https://github.com/EasyIME/forum/issues/3 的測試版本是否還有相同狀況。

**Comment by KenLuoTW** [comment]
今天以最新的源碼重新封裝才重現出此問題,以後回報請以 PIME 官方正式版本回報,
如果是自行編譯的版本,請在回報時註明。
