### ISSUE TITLE
超過 2bytes 編碼的中字或符號會導致組字游標不正確

### ISSUE THREAD

**Issue by KenLuoTW** [EasyIME/PIME#166]
新酷音的罕字比較少,所以比較少發生此狀況。

在新酷音中輸入「ㄓㄚˋ」選擇倒數第二頁的「𢕮」即可重現此狀況。
當組字游標經過「𢕮」字元時,它會少移動一格。

![2016-08-13](https://cloud.githubusercontent.com/assets/12954277/17641625/2bacdefa-615a-11e6-855e-b3d0f038673f.png)

**Comment by mrhso** [comment]
這大概是以 UTF-16 的位元組數判斷的吧。
要能判定代理對就不會這樣了。

**Comment by PCMan** [comment]
目前不確定問題是在哪裡造成。
TSF 理論上根據文件，是以「字元數」而不是 bytes 數來計算位置
python 內字串是 unicode，對於 surrogate pair 也是存成同一個字元，長度只會算1
合理推測 TSF的字元數是以 utf16 wchar 的字元數來計算，而把 surrogate pair算成兩個了
這部份還需要實驗，若為真，可能要在 python 端算成 utf16 wchar 數而非 unicode 字元數 :-(

**Comment by PCMan** [comment]
相關文件：
檢查 surrogate
https://msdn.microsoft.com/zh-tw/library/windows/desktop/dd318683(v=vs.85).aspx

取得 TSF composition string
https://msdn.microsoft.com/en-us/library/windows/desktop/ms628923(v=vs.85).aspx

可以在 PIME::Client 處理 composition cursor 時檢查，先取得 composition string，接著將 unicode char 數計算的 position 修正為 wchar_t length (每個surrogate pair 多 +1)，再傳給 TSF 應該就能修好

**Comment by PCMan** [comment]
已在 0.16-dev branch 內修正。
