### ISSUE TITLE
0.10版用方向鍵選字問題

### ISSUE THREAD

**Issue by furlong0507** [EasyIME/PIME#17]
在搜尋框中輸入搜尋文字時若按~叫出符號表、再用方向鍵選取，搜尋框彈出的建議選項也會跟著動

使用的OS是Windows 10、瀏覽器是Firefox
![2016-02-27_231124](https://cloud.githubusercontent.com/assets/5035279/13373615/711ac0e2-dda7-11e5-8237-674da73ea18a.png)

**Comment by daviking222** [comment]
區消選取設定方向鍵那個即可

**Comment by furlong0507** [comment]
這樣用方向鍵選字的選項就沒意義了

**Comment by PCMan** [comment]
Fixed in git HEAD.
