### ISSUE TITLE
在全形模式下以VK_ESCAPE方式取消關聯字時出現多餘符號

### ISSUE THREAD

**Issue by swkandrew** [EasyIME/PIME#174]
windows version: 10

以半形模式按下字碼後
如[onf][space]出現輸入"你" 然後在候選關聯字列表的情況下按VK_ESCAPE, 成功取消關聯字列表
但在全形模式下
按[onf][space]輸入"你"之後，按下VK_ESCAPE會出現  你"ﻻ"的字符

**Comment by KenLuoTW** [comment]
已在 https://github.com/EasyIME/forum/issues/3 裡的 TEST 版本修正。
