### ISSUE TITLE
請給予能選擇VK_RETURN的功能

### ISSUE THREAD

**Issue by swkandrew** [EasyIME/PIME#175]
現在的VK_RETURN 是hard code 連著VK_SPACE, 功能都是選擇第一個候選字
希望能給予選擇成按下ENTER 的功能

**Comment by KenLuoTW** [comment]
下個測試版本會變更,可能趕不及 PIME 0.15 正式版,因為要弄的東西還很多。

**Comment by osfans** [comment]
我在pime平臺上移植的中州韻引擎(rime)可支援此功能，預設爲字母上屏，空格爲首選字。

下載地址：
https://github.com/osfans/PIME/releases
