### ISSUE TITLE
以shift+number 的方式選取候選關聯字的選項

### ISSUE THREAD

**Issue by swkandrew** [EasyIME/PIME#176]
現在的候選關聯字的輸入方式是直接以number 鍵作選擇
希望可以用number 的方式選擇同碼字而用shift+number 的方式選擇候選關聯字

e.g.
(倉頡)
[onf][1] ->你 -> [shift+1] -> 你們
[onf][1] ->你 -> [1] -> 你1

**Comment by KenLuoTW** [comment]
這部份暫時不打算更動。

**Comment by osfans** [comment]
我在pime平臺上移植的rime引擎可以支援此功能：
比如注音方案中：
https://github.com/rime/brise/blob/master/preset/bopomofo.schema.yaml#L58
```yaml
menu:
  alternative_select_keys: "ABCDEFGHIJ"
```

下載地址：
https://github.com/osfans/PIME/releases
