### ISSUE TITLE
有關於酷倉輸入法

### ISSUE THREAD

**Issue by q120144178** [EasyIME/PIME#178]
想問一下為什麼酷倉輸入法不能像酷音輸入法，整句輸入後由系統自動判別錯別字呢？ 這樣不就可以大大的減少錯別字的發生了嗎？ 不然現在最多只能做到關連字的話，如「午餐」就會打成「什餐」的情況

**Comment by KenLuoTW** [comment]
因為酷倉模組跟新酷音模組不是同一個核心,新酷音模組是使用已開發許久的[新酷音](http://chewing.im/),大部份功能,新酷音的核心都已完成,在 PIME 平台裡只須導入即可。

酷倉的核心是今年三月底才開始開發,所有功能幾乎都是重頭做起,要實現智能輸入,首先要實現組字編輯模式,而目前正在弄的就是這個組字編輯模式: https://github.com/EasyIME/forum/issues/3

**Comment by q120144178** [comment]
了解！ 自從注音越來越先進後，倉頡就好像孤兒一樣，今天注意到這個輸入法，真的非常感謝！！

**Comment by KenLuoTW** [comment]
我已經有在加快開發時程了,因為原本想休息一陣子的,但是目前還是繼續在改。
