### ISSUE TITLE
可以像XP一樣按住shift來輸入英文嗎?

### ISSUE THREAD

**Issue by mannok** [EasyIME/PIME#180]
XP年代要中英夾雜來輸入的話可以在中輸模式下按住shift來暫時切換到英文, 但後來都變成了按一下shift來切模(按住shift打字變成了大草)，這很不方便。
可以加多一個選項是按住shift來暫時切換到英輸，放開就回到中輸嗎?

我找了這種輸入法好幾年，如能幫忙開發實在萬分感激!

**Comment by InSb** [comment]
@mannok 如同新倉頡2010的行為？可試用 https://github.com/EasyIME/forum/issues/3 的最新測試，其中正在完善的「組字編輯模式」您可能喜歡。

或者只輸入大寫字母的話，可以在設定頁中的「簡易符號」選項卡中關掉「中文模式下按住 Shift 快速輸入符號」。

**Comment by Elijahlin** [comment]
我也有一樣的問題，以前在舊版0.3.8的時候可以按住shift就輸入英文，就像其他輸入法一樣，但現在不行，希望可以加入這個功能

**Comment by mannok** [comment]
@InSb 不不...   其實我想要的功能很簡單    就是在windows 7的倉頡中輸模式裏可以按住shift來輸入小草英文    放手後回到中輸模式

**Comment by InSb** [comment]
@mannok 
![eisuu](https://cloud.githubusercontent.com/assets/8103265/17920585/094b5650-6a08-11e6-8046-4d924681c92d.png)

**Comment by KenLuoTW** [comment]
@mannok  不管你用什麼模式,按住 shift 輸入英文,其大小寫是由 Caps Lock 的狀態來控制輸出的。
@Elijahlin 新酷音模組預設都有將「Shift 押住輸出xx」的選項啟用,請進設定設定為符合自己習慣的輸出方式即可。

**Comment by mannok** [comment]
@KenLuoTW 感謝關注!    我明白Caps Lock可以大寫小寫互換   但這會令我極不方便
打個比如   我常常打字的時候會中英夾雜, 按你的意思是這種情況我可以先按caps lock, 然後要打英文時按住shift就可以直接輸入小寫英文         但更多的時候我什至會把語言轉為英語,好讓我一口氣打一段或者更多的文章, 這時候我就會變成了全大寫(因為我之前按了caps lock)   這又是一個很煩擾的問題, 所以最治本的方法是XP那種方法, 在caps lock關掉的情況下按住shift仍然可以輸入小寫英文, 希望開發員能幫我完成這個小小的功能

**Comment by KenLuoTW** [comment]
@mannok 事實上，在 XP ~ Win10，微軟的輸入法，不論新舊xx系列，甚至關閉輸入法，
都是採用 Caps Lock 的狀態來控制押住輸出的英文大小寫，這個方式一直都沒有改變。

如果你須要強制押住 SHIFT +字母鍵輸出的英文為小寫，你可以直接修改「簡易符號」裡的設定並啟用它。
![2016-08-24 2](https://cloud.githubusercontent.com/assets/12954277/17936639/0c2a0ac0-6a52-11e6-94b0-63ff5a536718.png)

**Comment by mannok** [comment]
感謝大大的分享啊!!!   你解決了我這4-5年的煩惱了!

**Comment by mannok** [comment]
用了@KenLuoTW 的方法試了幾天...   這出現第二個問題    就是如果想在中輸模式按住shift輸入大寫   理論上我要先按caps lock   但是因為我在設定了硬性規定了shift + 字母會輸出小寫    結果無論我caps lock有沒有啓用   結果都會輸入小寫    怎麼辦?

**Comment by KenLuoTW** [comment]
所以我上面才說「目前如果你須要強制押住 SHIFT +字母鍵輸出的英文為小寫」可以那樣使用。
這是在還沒有更新前的暫時解法，不是要你以後都用這方式。

**Comment by KenLuoTW** [comment]
已經更新於 PIME v0.15, 在設定裡會多個「押住 Shift 輸出英文時預設小寫」的選項,這個就會依 CapsLock 鍵狀態輸出英文大小寫。
