### ISSUE TITLE
酷倉輸入法輸入最後一個選字框不消失

### ISSUE THREAD

**Issue by YeungHiu** [EasyIME/PIME#181]
沒有開字詞聯想，系統是win10紅石版。# 輸入完一句話後，最後一個字的選字框會一直停留在介面上，直到窗口被關閉。

**Comment by KenLuoTW** [comment]
不太明白輸完一句話後是什麼意思？正常來說你輸完字根後,它會依設定直接顯示候選清單或須按空白鍵才顯示候選清單,此時你須要選字才能輸入下一個字。
而當選字完,這個候選清單也就關閉了,怎麼會還會停留在介面上？

**Comment by YeungHiu** [comment]
可是在我的電腦上選完字之後候選清單並不會關閉，系統是最新的win10，你可以試下

**Comment by mrhso** [comment]
這個問題我這裏可以重現。
![default](https://cloud.githubusercontent.com/assets/13294467/17989241/7b84f0d0-6b5e-11e6-859d-2f1bb70a9d80.png)

**Comment by KenLuoTW** [comment]
請將以下檔案先備份起來:
```
C:\Users\你的用戶名稱\PIME\checj\config.json
```
然後將此檔刪掉，刪掉以後如果還是發生相同狀況，請將此檔附件上來。

也可以試看看使用 https://github.com/EasyIME/forum/issues/3 的測試版本是否還有相同狀況。

**Comment by mrhso** [comment]
除了大易和酷倉以外，輕鬆、注音也遇到了同樣的問題。

**Comment by KenLuoTW** [comment]
今天以最新的源碼重新封裝才重現出此問題,以後回報請以 PIME 官方正式版本回報,
如果是自行編譯的版本,請在回報時註明。
