### ISSUE TITLE
候選字清單介面可以改為垂直嗎?

### ISSUE THREAD

**Issue by mannok** [EasyIME/PIME#183]
這個是小問題   只是一直習慣看垂直的介面   所以想問一下有沒有這選項   感恩!

**Comment by KenLuoTW** [comment]
由「介面外觀」來調整，只要將「每列顯示候選字個數」調為1，就會垂直顯示了。
![2016-08-25](https://cloud.githubusercontent.com/assets/12954277/17940707/e08e4a3c-6a62-11e6-82c4-df325b87b3cc.png)

**Comment by mannok** [comment]
@KenLuoTW 你真是一個天才啊!!!   我愛你!!!    感激不盡!

**Comment by osfans** [comment]
建議關閉。
