### ISSUE TITLE
Windows 7怎樣進入酷倉設定介面?

### ISSUE THREAD

**Issue by mannok** [EasyIME/PIME#184]
請問在Windows 7怎樣進入酷倉設定介面?

**Comment by InSb** [comment]
切換到酷倉模組後，
- 按\`m（\`在數字鍵1的左邊、`Esc`鍵的下邊）後按`空白`鍵；或按三次\`鍵後按`空白`鍵。
- 滑鼠右擊右下角的「中」字標記，彈出選單，選「設定輸入法模組」。

或者直接運行`C:\Program Files (x86)\PIME\python\input_methods\checj\config\config.hta`。
