### ISSUE TITLE
輕鬆輸入法問題回報

### ISSUE THREAD

**Issue by yj1099** [EasyIME/PIME#186]
當字根本輸入錯誤時，無法接續輸入新字根，必須按下esc鍵才能輸入新字根。

**Comment by KenLuoTW** [comment]
字根輸入錯誤請用「Backspace」鍵退回，或是「Esc」鍵清除。
如果你要輸入錯誤時即清除組字字根，請核取「拆錯字碼時自動清除輸入字串」。

**Comment by yj1099** [comment]
暸解了，感謝您。
