### ISSUE TITLE
0.14版選字問題

### ISSUE THREAD

**Issue by Elijahlin** [EasyIME/PIME#187]
目前用0.14 test21，在準備選字的時候按 ↓ 不會跳出選字視窗，要先按一下enter確認選字讓看不到的選字視窗消失，再按一次 ↓ 才會出現選字視窗。

作業系統是win10，使用的軟體是line、photoshop

另外早期winxp時代的時候，可以在選字視窗時按 → 跳隔壁行，但目前更新以後都是變成跳下個字而已，是否可以新增這個功能，增加選字速度，謝謝

**Comment by KenLuoTW** [comment]
測試版請勿再此回報問題,建議至 https://github.com/EasyIME/forum/issues 提出。

我目前在 Test21 版之後,作了很多選字的修改,所以這部份等 Test22 版再看看有沒有此問題。

PIME 的候選清單可以直式或橫式排列,故右鍵在直式排列就是跳到下一個字,
橫式排列時則是跳到右邊的項目,如果已是最右邊的項目,則是跳到下一列第一個項目。
目前不打算變更這個,因為已有空白鍵換頁,且 Page Up/Down 也可以換頁。
