### ISSUE TITLE
Windows 版詞庫編輯器

### ISSUE THREAD

**Issue by ottokang** [EasyIME/PIME#189]
最近想要試試看開發網頁版本的使用者詞庫編輯工具（chewing-editor 一直用不起來），看了一下chewing.sqlite 的結構，裡面phone_x的欄位紀錄的是每個字的注音，但是一直找不到對照表或者注音轉換的程式，請問一下有人知道在那嗎？

**Comment by PCMan** [comment]
@ottokang libchewing 裡面有完整的詞庫操作 api，不需要動 sqlite
FYI: https://github.com/chewing/libchewing/blob/master/include/chewingio.h#L524
用 chewing module 內帶的 libchewig.py 可以存取這些 APIs
chewing_userphrase_*() 這一系列的都是。

用 enumerate 就可以列出目前全部的使用者自訂詞，我們只需要一個 javascript 的 editable table 元件，就可以在 config web server 內實做，讓他顯示在設定工具的頁面上。

缺點是，libchewing 的 API 每次呼叫，就是直接變更詞庫，沒有 transaction 的概念，沒辦法 commit 了才引起變更。
如果想再 UI 上做出編輯完畢，要按下確定才套用，那需要自己把新增/修改/刪除的動作放入一個 queue，最後確定才一次根據這些動作依序呼叫 user phrase API.

**Comment by PCMan** [comment]
@ottokang 這部份我也一直很想把他做完，不然我們來合作吧？趁 @KenLuoTW 還在修正其他地方，我們來完成這塊？

**Comment by PCMan** [comment]
@ottokang 之前把設定工具移轉到 tornado 的 web server 其實就是為了有完整的 python 環境，而不要受限於瀏覽器內的 javascript。所以現在可以直接在 web server 內呼叫 chewing 的 api 來做這些。

**Comment by ottokang** [comment]
@PCMan 好我來研究看看，我本來的想法是透過 Python 的 SQLite 直接去動詞庫，感覺這樣比直接用 user phrase API方便

**Comment by PCMan** [comment]
@ottokang  最好是用 API，因為 sqlite 那是內部實做細節，之後有可能會變。用API 只要 API 沒有改，我們程式就不需要任何修改，事情會單純很多。

**Comment by ottokang** [comment]
對Python還有libchewing沒有很熟，目前的想法幫忙指教一下
1. 在configTool.py裡面的LoadHandler實做load_user_phrase()：所以是要在configTool.py裡面import libchewing.py？

2. 在config.hta 實做詞庫編輯界面

3. 將詞庫變動的queue透過libchewing API寫回詞庫

**Comment by PCMan** [comment]
@ottokang 大致上跟我目前想得一樣，不過我也沒動手實驗，不確定會不會有問題。
最簡單的作法當然是使用者新增/刪除，就直接 call libchewing，但是這樣和原設定工具要「確定」才套用的操作邏輯不合，所以可能會需要把變更 queue 起來，再一次套用，但這會略為增加實做困難。

**Comment by ottokang** [comment]
我覺得詞庫編輯可以採用立即套用的方式，不然就另外寫一個Python檔案處理，安裝的時候新增捷徑就好，另外問一下如果import libchewing，是不是要再次初始化chewingContext？還是可以使用系統已經初始化的chewingContext？

**Comment by Festum** [comment]
Good to know there got some progress at editor.  I'm counting on you two!

**Comment by PCMan** [comment]
已經在 0.16 版實做
