### ISSUE TITLE
在正航進銷存 T357 這套會導致 pime 掛掉

### ISSUE THREAD

**Issue by s793016** [EasyIME/PIME#192]
這套進銷存有點麻煩，進去後預設是英文輸入，如果在這邊切到 pime，然後跳出去正航後，就不能再使用 pime 了，必需重開機。

此時切別的輸入法再回來 pime，pime 的第二圖示會消失

**Comment by osfans** [comment]
殺掉python應該就可以，不用重開機嗎？

**Comment by s793016** [comment]
把 python 停掉，好像 ok 了，但不知道是不是沒重開的原因，發現另一個問題

在 A 軟體按 ctrl-space 切英文模式，然後切到 B 軟體，保持在英文模式，但 ctrl-space 可能1次切不回來中文模式，要兩次，此時狀態列的第二圖示已經沒有同步了，要回去 A 軟體切換後才會同步。
