### ISSUE TITLE
仓颉輸入法默认词序能否改为简体在先,繁体在后?如输入简体的"这",排在前面而不是最后一页. 默认是繁体的"這"排在第一页. 

### ISSUE THREAD

**Issue by zyhimg** [EasyIME/PIME#194]
请问,仓颉輸入法默认词序能否改为简体在先,繁体在后?如输入简体的"这",排在前面而不是最后一页. 默认是繁体的"這"排在第一页.

**Comment by osfans** [comment]
好像可以設置輸出簡體。
rime裏也可以。

**Comment by q120144178** [comment]
我覺得板主的意思就是他不想想繁體字的樣子
所以希望可以直接打簡體出簡體吧
就跟叫台灣人必須打簡單才顯示繁體一樣的不便...

**Comment by KenLuoTW** [comment]
這個不是問題，RIME 是基於簡體的輸入法，所以應該有特別將「這」的簡字加入候選清單，
並放到候選清單最後面，以方便簡體用戶輸入。

而樓主則是以繁體的「這」編碼（卜卜一口）打出「這」，卻又要簡體的「这」顯示在最前面...
我記得 RIME 應該也有打繁出簡的功能，可直接開啟這功能來解決他的問題。
