### ISSUE TITLE
押住shift輸出英文時預設小寫問題

### ISSUE THREAD

**Issue by mannok** [EasyIME/PIME#195]
剛試用了還沒release的version, 啟用了 押住shift輸出英文時預設小寫
沒錯預設押住shift是小寫, 但當caps lock啟用時押住shift依然是小寫
辛苦各位大大

**Comment by KenLuoTW** [comment]
記得之前你應該有把「簡易符號」改成都是小寫的字母,
「簡易符號」裡的設定,會優先於這個設定,請將簡易符號關閉即可。

**Comment by mannok** [comment]
可能我之前沒有正確去build這輸入法,   現在用release版本就行了
我等了這幾年了   終於等到了   感謝各位開發者!

**Comment by mannok** [comment]
更新: 這bug確實存在, 只是windows 10沒問題   但windows 7的caps lock確實沒有效

**Comment by KenLuoTW** [comment]
目前還在值班中,用得電腦很爛,暫時沒去測 WIN7 下的問題。
後天我回家後,我會去確認一下有沒有這個問題。

**Comment by KenLuoTW** [comment]
已確認在 Win7 下無作用, 下個正式版時會修正。

**Comment by KenLuoTW** [comment]
已修正於 https://github.com/EasyIME/PIME/commit/1e792e4ef1d4aa4d8e26b6bf6060a5860ecd8cee

**Comment by mannok** [comment]
好像還是沒有效 (也有可能是我的錯誤)   ken大有試在win7中運作正常嗎?
如果確實運作正常, 我再多試build幾次   謝謝~

**Comment by mannok** [comment]
剛剛release的版本測試了,   bug是修正了   但還有些時候會像是觸發不了caps lock似的
跟著這步驟就很容易測試得到:
在酷倉模式中按住shift, 右手不斷按字母鍵, 左手不斷按caps lock   就會發現輸出來的英字不會轉換大/小寫 (鍵盤上的caps lock燈是有轉換的)    拜託大大跟進一下   感激萬分!   謝謝!
