### ISSUE TITLE
Adding English support to the installer?

### ISSUE THREAD

**Issue by salty-horse** [EasyIME/PIME#196]
Hi,

I have a python-based input method for IBus (an equivalent system for Linux) which I would like to integrate with PIME. My project is an emoji input method that is quite different than the one you currently have in your source tree: [ibus-uniemoji](https://github.com/salty-horse/ibus-uniemoji).

I have tried the installer in the Releases section, and everything works fine. However, I couldn't read any of the dialogs and just pressed things blindly. It would be very helpful if the installer dialogs were in English. I am not familiar with how Windows installers work, but I think it would be able to pick the right language to use based on the system settings.

If you wish, I can provide English language strings to use, if you instruct me what needs to be translated.

**Comment by PCMan** [comment]
Yes, it's possible.
@osfans Since you just did the multi-language support for the installer, would you please help this part?

**Comment by osfans** [comment]
Yes, please check installer/locale and installer/resource folder. Or you can check my commit in the installer folder.

**Comment by salty-horse** [comment]
OK. At this stage, I'm not quite sure if you want me to start translating, or if you will.

Google Translate seems to work well for most of them. For example:

PRODUCT_NAME "PIME 输入法" - "PIME Input"
SECTION_MAIN "PIME 输入法平台" - "PIME Input Method Platform"
SECTION_GROUP "输入法模块" - "Input method module"

I can go over everything I understand and submit a pull request, and then I could use your help with the rest :)
