### ISSUE TITLE
設定界面問題

### ISSUE THREAD

**Issue by daviking222** [EasyIME/PIME#20]
一開啟就最大化
希望可以符合設定視窗邊界

**Comment by ottokang** [comment]
把 config.hta 檔的 windowState 改成 "normal" 就可以，但是我是覺得沒有這麼必要修改

**Comment by PCMan** [comment]
改成 normal 視窗內容有時後會超出可見範圍
用 javascript 沒有可靠的方法可以讓視窗大小剛好
所以才最大化
