### ISSUE TITLE
拆錯字碼時自動清除輸入字串 - 建議拆錯字碼後backspace可以一鍵清除錯字串

### ISSUE THREAD

**Issue by johnalert** [EasyIME/PIME#200]
現在有啟用這個選項時如果拆錯字碼會卡在錯字的字串表
如果錯了5個碼就要按5次backspace來回復
如果錯了4個碼則要按4次backspace來回復
可以換成backspace一鍵清除錯字碼或多加一個選項嗎?

**Comment by osfans** [comment]
esc可以嗎 rime預設是esc

**Comment by johnalerb** [comment]
可以, 但錯碼都是比較常犯的錯誤, 如果每次都要按esc好像有點不太方便

**Comment by KenLuoTW** [comment]
這個功能之前主要以倉頡這類以空白鍵作為結束鍵的輸入法而加入,
並未針對以聲調鍵作為結束鍵的輸入法而修改。
例如目前使用注音輸入「ㄌㄨㄟˋ」,須再按空白鍵才會清空字串。

我會在 0.16 版將以聲調鍵作為結束鍵的輸入法,在啟用此功能後,
只要按下結束鍵,也可以清除輸入錯誤的組字字根。

如果上述內容不是你所說的狀況,請詳述說明你的狀況,
至於 backspace 鍵的行為不會變更,要自行清除字串請用 esc 鍵。

**Comment by johnalert** [comment]
@KenLuoTW 我是港人所以不太懂注音   我的狀況其實不算是bug
我是在用酷倉的   簡單來說就是錯碼後希望可以一鍵清除字串    雖然esc是可以   但如果每次錯碼都需要按esc實在有點繁複
XP年代的倉頡好像錯碼後可以直接重新輸入新的字串, 或是按一下backspace清除錯的字串   這樣就可以避過每次按esc的問題了

**Comment by KenLuoTW** [comment]
大概了解你的意思了,就是按下空白鍵後,出現拼錯訊息後,
再按下字根鍵時,可直接拼下個字。

**Comment by johnalert** [comment]
"再按下字根鍵或倒退鍵時"   按下倒退鍵再拼下個字好像比較好
"再按下字根鍵直接拼下個字"  有機會不為意miss了錯字

**Comment by KenLuoTW** [comment]
這部份我有回頭去看 XP 及 WIN7 下的倉頡、新倉頡,從 XP ~ WIN7 預設的行為都是這樣。
當初也是想說,有時只是打錯了一兩個字根,如果不清除錯誤字根,可以按 backspace 退回修改。

且修改後因為 backspace 鍵已會清除拼錯的字根時,所以就算想回頭修改也是不可能的。
所以按下字根鍵,直接清除錯誤字根並拼下個字,才不會要多按 ESC 鍵才能清除錯誤字根。

總之修改後,行為模式會與微軟的方式一致,並會取代目前「拆錯字碼時自動清除輸入字串」的行為。
也就是核取後,按下空白鍵時不清除錯誤字根,等到按下 backspace 鍵或任一字元鍵時才會清除錯誤字根。

**Comment by KenLuoTW** [comment]
已修正於 https://github.com/EasyIME/PIME/commit/3bfd452fc1b96f911ae119db6ef7854fb3589dc6
剛剛修改這個問題時,發現我根本搞錯樓主意思,而樓主想要的方式是完全不合理的,故不會變動。
所以只修改某些支援  EndKey 的輸入法,按下 EndKey 時不會自動清除的問題。
