### ISSUE TITLE
0.15.1 安裝後被歸類為香港特別行政區語系

### ISSUE THREAD

**Issue by tiberiusteng** [EasyIME/PIME#201]
因此無法跟以往一樣，跟原有的台灣輸入法在同一個語系裡 ctrl+shift 切換

安裝過程中沒有看到相關選項，請問這是刻意做的變化嗎？
還是有辦法變更安裝到的語系

感謝

**Comment by mrhso** [comment]
作業系統？

**Comment by mrhso** [comment]
[https://msdn.microsoft.com/en-us/goglobal/bb896001.aspx](url)
根據這份資料，猜測是 ResolveLocaleName() 只理 zh-Hant，於是發生了這樣的慘案。
我使用的是 Windows 7，zh-Hant 就是到了香港來。（雖然説我本來就要弄到香港，但是 zh-Hant-TW 到了香港怎麼也説不過去）

**Comment by tiberiusteng** [comment]
Windows 7

**Comment by PCMan** [comment]
v0.15.2 已經設法修正，請更新。
https://github.com/EasyIME/PIME/releases/tag/v0.15.2
放棄使用問題多多的 ResolveLocaleName()，直接提供
當 zh-Hant-TW 系統無法辨認時，fallback 到 zh-TW 使舊版 Windows 相容
