### ISSUE TITLE
關於中州韻輸入法，請更新 TWVariants.ocd

### ISSUE THREAD

**Issue by s793016** [EasyIME/PIME#204]
opencc 目錄內的 TWVariants.ocd 看起來是沒有資料，所以設定 t2ts 都沒有作用，但查看 opencc 原 git hub 是有資料，手動修改 t2ts.json 強制指定給 txt 檔則正常，所以請更新此檔案，謝謝。

附檔為自 opencc git 處取得之 TWVariants 檔。
[TWVariants.txt](https://github.com/EasyIME/PIME/files/499943/TWVariants.txt)

**Comment by osfans** [comment]
用的是這個，看起來有資料。
https://github.com/EasyIME/PIME/blob/master/python/opencc/TWVariants.ocd
