### ISSUE TITLE
可否增加 繁體 簡體 快速切換方式？

### ISSUE THREAD

**Issue by coolyu99** [EasyIME/PIME#206]
像是小狼毫有這個功能，按F4可以選擇輸出 繁體 或是 簡體
小小建議
謝謝

**Comment by osfans** [comment]
rime模块现在也可以 也可以ctrl+shift+4直接切换简繁体。但是其他模块好像还没有快捷方式

**Comment by osfans** [comment]
只是rime模塊的問題的話，就先關閉了。
