### ISSUE TITLE
[rime]從自定義選項鍵的輸入方案切回默認選項鍵的輸入方案時，選項顯示不正確

### ISSUE THREAD

**Issue by biopolyhedron** [EasyIME/PIME#207]
我的中古三拼用的選項是默認的123456789，韓文是34567，拉丁字母是@#$%&_{}\（主要是因爲在韓文和拉丁字母裏，常用數字鍵在編碼裏有用），但現在比如先切拉丁再切回中古三拼時，顯示的選項仍是@#$%&_{}\，盡管敲123456789時仍能正確選字，敲@#$%&_{}\也正確出符号。
![image](https://cloud.githubusercontent.com/assets/931984/19021000/635a0e88-88ea-11e6-8f36-fc5f5889704c.png)

**Comment by osfans** [comment]
e7915f6e29696c2776f5d5c2c6fca9eb5bd65b60 解決
