### ISSUE TITLE
選字框會在畫面最右下角的

### ISSUE THREAD

**Issue by asps14741** [EasyIME/PIME#208]
使用發現如果沒有在反白選字的情況下(操作是按鍵左+下)
選字框是正常的位置
但是如果直接選字(操作是按鍵下)
選字框就會直接在畫面的右下角

還有可以新增如果有多重頁面選項時
可以知道說這個讀音有幾頁
也可以方便用左右鍵快速翻頁選擇

**Comment by PCMan** [comment]
這個位置是微軟的 TSF 給的，不是我們自訂，新注音也是在那個位置，並非 bug。
