### ISSUE TITLE
請問：0.15.2版在使用自由倉頡時，快碼第一碼是注音符號是否可以修改呢？

### ISSUE THREAD

**Issue by sirius95** [EasyIME/PIME#209]
朋友們你好：
因為我是使用自由倉頡的，然後在安裝了0.15.2版，發現原本一些快拆碼，按下去之後，不是像原先那樣
出現文字，而是出現注音符號，例如：
若按鍵盤上的「日」鍵，理應出現的快拆碼會出現「是」，不過卻變成了「ㄇ」；
按鍵盤上的「手」，應出現「年」，結果變成了注音符號，不知道是不是哪邊要勾選才能回復
到原先的出字方式呢？

請朋友們指導一下，感激不盡！謝謝～

**Comment by stu98601** [comment]
有同樣問題

**Comment by sirius95** [comment]
這個問題蠻怪的，之前版本沒有，卻在這個版本出現，真的無解嗎？謝謝

**Comment by lyenliang** [comment]
我在 #230 有提到暫時性的解法。

**Comment by KenLuoTW** [comment]
此問題已修正。
