### ISSUE TITLE
在半形輸入狀態下顯示全形與錯誤的標點符號

### ISSUE THREAD

**Issue by asps14741** [EasyIME/PIME#211]
目前使用新酷音注音的狀態下如果是使用半形狀態下
有部份的標點符號是顯示全形與錯誤的標點符號
有＝ 「 」 ＼ 、 
不是顯示= [ ] \ '

以上是比照鍵盤上面的標籤進行對比

**Comment by PCMan** [comment]
這其實不是 bug，原本的 libchewing  核心就是這樣設計
