### ISSUE TITLE
[酷倉] 日常生活中用不到的字很多，造成候選字很多、阻礙輸入

### ISSUE THREAD

**Issue by seantw** [EasyIME/PIME#213]
另外還有「晚」候選字出現2次, 而且候選字不常用的「冕」排在第一個? 很不好選

**Comment by q120144178** [comment]
那個晚沒有出現兩次喔！
你注意看的話兩個字的「儿」是不一樣的 「晩」是日本漢字 「晚」才是台灣在用的
而且冕我輸入法是第二順位欸？

**Comment by seantw** [comment]
我也不清楚我的為什麼會在前面?
![-1](https://cloud.githubusercontent.com/assets/6134241/19416895/ad349858-93cf-11e6-9858-3ab7d23b22a0.png)

**Comment by q120144178** [comment]
應該是你設定的字碼表是微軟的倉頡吧
要設定回來酷倉的話 按`(ESC下面)+M後選功能設定>輸入法碼表>選「酷倉」>右下角點確定
應該就可以看到「日弓日山」的順序是 晚、冕、晩了

**Comment by KenLuoTW** [comment]
用不到的字,主要是碼表所定義,選擇微軟碼表就不會有罕字。
那兩個晚字,實際上不是同一個字,是異體字。
