### ISSUE TITLE
建議 JavaScript 的另一選擇

### ISSUE THREAD

**Issue by seantw** [EasyIME/PIME#216]
Python 或 Node.js 跑起來佔記憶體大約 6~7MB。
Windows Script Host 的 JS 程式跑起來大概只佔 1.5MB。
不知可否考慮支援它來開發 PIME 輸入法?
它跟 DCOM 元件可以有很好的溝通

**Comment by PCMan** [comment]
PIME 沒有限制後端的語言，最新版本只需要能實作相容介面的 RESTful API 即可接上。只要是能在 locahost 跑起 http service 並且提供 RESTful API 的程式語言都能實作。

**Comment by osfans** [comment]
這樣一來 純c/c++也可以做了？

**Comment by PCMan** [comment]
@osfans 確實是，但是得實做 http RESTful API.

**Comment by osfans** [comment]
還是python寫得爽。只要打字流暢，我還是選擇python。

**Comment by PCMan** [comment]
@osfans 打字需要處理的 requests per second 不過 500 上下，用 scripting language 綽綽有餘了。開發快速好維護才是重點！
目前這架構，我反而覺得 golang 可以試試看，compile to native code, fast, 適合 web app.
