### ISSUE TITLE
PIME 0.15.2 版本在 Windows 10 x64 下间歇性失灵

### ISSUE THREAD

**Issue by gmsh** [EasyIME/PIME#219]
您好，
    PIME 搭配中州韵输入法（微软双拼方案、简化字）在 Windows 10 x64 (build 14393.321，locale zh-CN， UI 为英语) 下使用一段时间后，在切换程序或者切换中英文输入法时有一定机率导致 PIME 输入法失灵。
    具体表现为系统托盘中输入法图标存在并显示为中州韵，但是中英文切换图标不显示，同时切换中英文的快捷键失效，打字直接字母上屏，按 Ctrl + ` 也没有反映。
    附件是 Temp 目录下的日志文件。

[Temp.zip](https://github.com/EasyIME/PIME/files/526154/Temp.zip)

用任务管理器杀死 PIMELauncher 和 pythonw 并重启 PIMELauncher 之后恢复正常。

**Comment by Yunzj** [comment]
我也同样有这个问题，有时很难切过来。。因为一天大多数都在用cad2006的软件。。禁用输入法，在cad里输入命令，然后偶尔切到excel或word里就会发现输入不了中文了，有时需要ctrl+空格键，连按一至三次才会切到中文，有时无效，就需要按 alt+shift键 再配合 ctrl+空格键 才能切到中文，很郁闷。。。
微软自带的输入法禁用后，直接按shift就恢复中文了，这样也不好，在cad需要英文，并需要shift与鼠标组合，希望pime解决这个问题就完美了。。。。

**Comment by quericy** [comment]
我也是这样，kill掉pythonw让它自动重新唤起就能恢复，只能写了个kill进程的cmd固定到开始菜单

**Comment by dorawei** [comment]
+1，希望能盡快解決間歇失靈的問題…

**Comment by seantw** [comment]
+1

**Comment by gdnxdcs** [comment]
+1

**Comment by KNCheung** [comment]
+1

**Comment by PCMan** [comment]
和 #131 是同一問題
