### ISSUE TITLE
當某程式產生異常而關閉時，再次開啟新酷音就不能使用

### ISSUE THREAD

**Issue by cook2003** [EasyIME/PIME#222]
系統是win8.1
當某程式產生異常時，會自動關閉。
多半是word或者火狐，記事本偶爾也會。
但是重新時，卻發現不能使用。
更令人生氣的是，其他視窗都可以使用新酷音。
唯獨那個異常而重新開始的程式。
例如這次異常關閉是word
word完全沒辦法打新酷音，可是火狐和記事本以及其他程式可以。
下次換成火狐異常關閉。
變成火狐沒辦法打新酷音，可是其他程式如word和記事本就可以。

要重開機才會變成原狀。

不知道這是什麼回事，請加以改善。

**Comment by PCMan** [comment]
@cook2003 請測試看 0.16.1 版本是否還有此問題，應該有改善了。
