### ISSUE TITLE
新版被刪除的[編輯使用者詞庫]能否恢復

### ISSUE THREAD

**Issue by cacac0723** [EasyIME/PIME#223]
我是文字工作者，很多專門語彙，可藉由編輯使用者詞庫來做存錄。往後打字迅速，亦能減少錯誤。紀錄檔還能匯出匯入，轉移方便。不知能否恢復這項本有的功能？感謝。

**Comment by PCMan** [comment]
和 https://github.com/EasyIME/PIME/issues/19 重複
