### ISSUE TITLE
希望可以候選字自動上屏

### ISSUE THREAD

**Issue by dorawei** [EasyIME/PIME#224]
就像rime-gits那樣，輸入完就顯示首個候選字，現在的PIME是只顯示字碼，比如「竹手戈」，希望可以直接顯示出候選字「我」。

非常感謝

**Comment by osfans** [comment]
rime模塊嗎？是可以設置的。
參見：https://github.com/EasyIME/PIME/blob/master/python/input_methods/rime/data/PIME.yaml#L14
修改爲`preview`

**Comment by dorawei** [comment]
感謝~
