### ISSUE TITLE
outlook2016中无法正确显示字符

### ISSUE THREAD

**Issue by TerrrnceTam** [EasyIME/PIME#225]
小弟在使用osfans大大发布的PRIME时发现的问题。PIME中只安装了中州韵输入法，使用的是粤拼方案。系统windows10 enterprise N。
在outlook2016使用时发现在发送新邮件时，拼音处会涂黑，没有办法看到当前输入了什么字母。在打出汉字后则没有问题。
奇怪的是在outlook2016的其他位置如搜索栏等，以及其他应用中并没有同样的情况。

github好像不能贴图。。。？

**Comment by osfans** [comment]
可以貼圖的，就是上傳有點慢

**Comment by TerrrnceTam** [comment]
![1](https://cloud.githubusercontent.com/assets/19420091/19635445/f7850c32-99f4-11e6-8b08-93d7d96f96ed.png)
![2](https://cloud.githubusercontent.com/assets/19420091/19635446/f973c448-99f4-11e6-9ebb-af5d8870a399.png)

@osfans 答复得好快！
上传2张图片。
图1是在outlook2016新邮件的情况。第一行是打出汉字后没有问题；第二行是打字过程中按shift由中文转换成英文，部分字能正常显示但大部分黑了；第三行是打字过程中拼音部分全黑了。
图2是在浏览器中是正常的，其他程序也正常（包括outlook同一封新邮件中的收件人等栏位）

**Comment by osfans** [comment]
如果其他模塊也都有這個問題的話，那就跟rime無關，而是pime平臺的問題了。

**Comment by TerrrnceTam** [comment]
那应该是PIME的问题了。测试了酷仓有类似问题。
![3](https://cloud.githubusercontent.com/assets/19420091/19636765/ef8c8c40-99fd-11e6-812c-9a919869f106.png)

**Comment by qqldd** [comment]
@TerrrnceTam 使用了英文的win10+outlook 2016，无计重现该问题，你可以试试其它office程序里面有没有相同的问题

**Comment by PCMan** [comment]
windows 10 x64 + outlook 2016 + PIME 0.16，剛測試過無法重現此問題

**Comment by KenLuoTW** [comment]
這個不是 PIME 正式版的問題, 所以在正式版中無法重現。

**Comment by osfans** [comment]
暫時關閉，再有問題可以去Prime那邊開issue。
