### ISSUE TITLE
[RIME] [PRIME] 不支持 %APPDATA\Rime 配置？

### ISSUE THREAD

**Issue by qqldd** [EasyIME/PIME#226]
RIME 默认配置在 %APPDATA\Rime，我好像发现在PRIME里面这个folder的配置没有作用。

想确认下是不是现在改配置要直接改这里面的内容 C:\Program Files (x86)\PIME\python\input_methods\rime\data

**Comment by osfans** [comment]
是在`%APPDATA%\PIME\Rime`吧
具體參見：https://github.com/EasyIME/PIME/blob/master/python/input_methods/rime/rime_ime.py#L31

**Comment by qqldd** [comment]
@osfans 谢谢提醒，之后稍微看了下代码，没发现还有个PIME做为前缀
