### ISSUE TITLE
特殊符號設定會當機

### ISSUE THREAD

**Issue by cook2003** [EasyIME/PIME#229]
按新酷音的設定→特殊符號
將￣口￣或者￣▽￣加入裡面，
然後按 ` 打出來時就會當機。
我是win8的

**Comment by PCMan** [comment]
特殊符號一行只能打一個符號
目前存檔時沒有檢查格式錯誤，未來修正。

**Comment by ottokang** [comment]
在 #258 做出了修正，只在前端做檢查，後端就不做了（理論上不會有第三者越過前端直接寫入資料）
