### ISSUE TITLE
Ctrl + 數字新增詞彙沒有提示訊息

### ISSUE THREAD

**Issue by ottokang** [EasyIME/PIME#23]
TSF版本的新酷音有這個功能，找了一下PIME似乎沒有實做提示訊息的部份，可以指點一下從那邊連接嘛？

**Comment by PCMan** [comment]
還沒做

**Comment by PCMan** [comment]
@ottokang 其實 code 應該都有，要加上對應的 IPC

**Comment by PCMan** [comment]
Fixed in 2f3e8d4a00b3f2b934a4b2deb87b7f29cc4a247d.
