### ISSUE TITLE
自由大新倉頡異常

### ISSUE THREAD

**Issue by lyenliang** [EasyIME/PIME#230]
0.15.2 的自由大新倉頡輸入法選字的順序異常，例如 f 鍵第一個選項應該對應到「不」，但實際卻對應到「ㄅ」。
![image](https://cloud.githubusercontent.com/assets/3468329/19798008/20696b64-9d21-11e6-81bd-b21b4b2a8158.png)

**Comment by sirius95** [comment]
對啊....出了這個大問題了....很多第一碼都已不是中文字，而是注音符號....@@麻煩你們想辦法解決了...感激不盡

**Comment by lyenliang** [comment]
似乎跟 e3ebdd6c71ba461c2829f093b891edda922a72b6  「[CinBase] Add support for sorting the cin-table data by high frequenc...」有關，因為這個 commit 會改變選字的順序。

**Comment by lyenliang** [comment]
對於慣用倉頡輸入法的人，可以暫時先把 `C:\Program Files (x86)\PIME\python\input_methods\checj\cin.py` 202 行的 
`self.mergeDicts(self.bopomofochardefs, self.big5Fchardefs,...` 改成
`self.mergeDicts(self.big5Fchardefs, self.bopomofochardefs,...`，這樣倉頡輸入法可以恢復正常。

**Comment by sirius95** [comment]
@@ 真抱歉，我對這個不懂，不太知道怎麼改....

**Comment by KenLuoTW** [comment]
此問題已修正。
