### ISSUE TITLE
清理KMT威權詞彙

### ISSUE THREAD

**Issue by 1abcd** [EasyIME/PIME#231]
在Win98, XP 傳統注音輸入「李」的相關詞彙會出現: 總統, 登輝 
在Win7傳統注音輸入法可以發現上述詞彙已消除
在酷倉的聯想詞仍然把「總統」、「登輝」放於最前方
已經不符合目前時代思想

Win7注音輸入法除了消滅「李總統」詞彙，連「中華民國」的詞彙也已經消除，這部分請酷倉繼續保留

**Comment by KenLuoTW** [comment]
不會去處理這個,因為未來會變更資料來源,不會用現在的聯想詞庫資料。
