### ISSUE TITLE
PIME 0.16 Pre-release 無法設定輸入法 & 防毒軟體問題

### ISSUE THREAD

**Issue by mitch0118** [EasyIME/PIME#232]
Win 10 X64，無法設定輸入法，跳出來的設定頁面，選擇框全部預設都是沒有勾選，勾選後也無作用。
試過firefox、IE、Edge。

另外，安裝完後，Windows Defender似乎一值在掃PIME，CPU使用率明顯升高。

**Comment by InSb** [comment]
PIMELauncher.exe 被 Bitdefender 檢測有害，即使手動 restore 也會在調出輸入法時再次提醒。

**Comment by ottokang** [comment]
看起來應該是誤判

**Comment by PCMan** [comment]
@mitch0118 可以請你幫忙發一個 bug report 到 Bit defender 嗎?
http://www.bitdefender.com/submit/
就把檔案給他們然後說是 false positive
我剛跟 Bit defender 線上客服問過，通常發了一到兩天內會處理到。
我這邊也會再發一次更詳細的，感謝!

**Comment by PCMan** [comment]
@mitch0118 你的 Windows defender 有更新到最新嗎？我系統跟你一樣，也有 Windows defender，但是不會阻擋 PIME。
另外如果確定 Windows Defender 會衝到的話，上回已經有跟微軟回報一次錯誤他們修了，
不過問題還在的話，網頁在這裡，我可以再跟微軟回報一次。
https://www.microsoft.com/en-us/security/portal/mmpc/developer/resources.aspx

**Comment by PCMan** [comment]
@osfans 你的 RIME 用戶群有沒有發現被中國的殺毒軟件阻擋的情形？

**Comment by ottokang** [comment]
我的 Windows Defender 沒回報問題

**Comment by HPEACE** [comment]
Symantec 發現病毒，已協助排除

**Comment by PCMan** [comment]
@HPEACE 方便描述詳細的狀況嗎?
我們需要回報給 Symantec
https://submit.symantec.com/whitelist/
或者願意的話，你也可以協助回報 False positive.

**Comment by HPEACE** [comment]
我已回報且已排除
誤報的回報網址 https://submit.symantec.com/false_positive/

**Comment by PCMan** [comment]
@HPEACE 非常感謝
這問題實在滿麻煩的，其實防毒軟體對於沒有數位簽章的程式，會很容易誤判，但是購買這個簽章憑證每年需要非常高額的花費，實在負擔不起... 目前還沒想到比較好的方法解決頻繁遭誤判的問題 :(

**Comment by HPEACE** [comment]
没簽章要一直不被誤判只能在發新版前就往各家vender送先

**Comment by PCMan** [comment]
@HPEACE 是啊，這次的計畫就是如此! 感謝協助，防毒真是太多家了.... 囧
買簽章雖然一勞永逸，但是每年要五六千塊以上，對這種免費專案實在無法

**Comment by PCMan** [comment]
剛問過 comodo，以前有提供過 OSS 簽章的贊助，但是很早就停辦了，現在價格超貴，問了客服，也沒有任何方式可以拿到折扣.... :(
看來之後送 sample 到各家 antivirus 會變成 release 前必要的流程

**Comment by mitch0118** [comment]
@PCMan 好的，我來幫忙回報Windows Defender。不過我的Windows Defender沒有直接跳出來病毒提示，但是用工作管理員看得出來他一直在掃，我移除PIME，CPU使用率就降，再次安裝又會飆高

**Comment by HouMuYi** [comment]
Avast誤判，已回報該廠。
![2016-11-13 -002](https://cloud.githubusercontent.com/assets/15069632/20244764/e94a1f48-a9c8-11e6-876a-7deb663ba36a.png)
![2016-11-13 -001](https://cloud.githubusercontent.com/assets/15069632/20244765/ef01c4ae-a9c8-11e6-8751-5bf97b89d5fd.png)

**Comment by marvinyen** [comment]
今天一完成下載 就被pc cillin雲端板(win 10 pro , 64bits)認為是可疑檔案直接封鎖刪除..還在研究如何回報是誤判

![image 201611151](https://cloud.githubusercontent.com/assets/23466888/20290629/339ab91e-ab1c-11e6-9475-763802473f8a.jpg)

**Comment by HPEACE** [comment]
@marvinyen 
http://www.trendmicro.com/us/about-us/detection-reevaluation/

**Comment by marvinyen** [comment]
Thanks, 已經線上聯繫台灣客服人員協助排解

**Comment by InSb** [comment]
前些天安裝 development preview 2，Bitdefender 還是會報 PIMELauncher.exe 有威脅。拜託其他 Bitdefender 使用者確認。

**Comment by HPEACE** [comment]
@InSb  已幫回報，後續有需要回報請自行上傳 http://www.bitdefender.com/site/Main/automaticSampleUploader/

**Comment by HPEACE** [comment]
@PCMan  Compiler時試試把以下資料把補齊看是否會減少誤判

![image](https://cloud.githubusercontent.com/assets/20449305/20292068/b2404e9c-ab25-11e6-8f2c-0055686b4e8f.png)

**Comment by PCMan** [comment]
@HPEACE 我想應該是不會，根據 symantec 提供的資訊，應該是應用程式簽章比較重要。
有簽章應該是可以大幅度降低這種問題，但是簽章一年要花六千台幣....沒人捐款的話無法 XD
Symantec 允許在發行前先送審，如果你可以驗證發行者身份，他會把 exe 列白名單，但是每一個檔案要送一次，發新版一個 exe 檔要重送申請一次，非常麻煩。
一勞永逸的方法就是花錢買簽章，但是那真的太貴了，所以我現在的計畫是：
1. 每次發行之前先發 release candidate 小眾測試
2. 把 release candidate 送給各大防毒軟體排除
3. 把 RC 版改成正式版，大量發行

目前輸入法做的事情，就是攔截使用者鍵盤輸入，然後送給某個隱藏視窗的程式 (或  web service) 資料處理。這和惡意程式的行為模式幾乎一樣，所以幾乎是保證會被誤判...
如果要避免這種狀況，我想唯一合理的作法就是輸入法不能做任何 IPC，每個 app 和輸入法內部就是 in process 跑自己獨立的一份 python engine，但這樣開發上的彈性會大幅度減低，而且也無法支援不能嵌入 C++ 程式內的 scripting 語言，基本上 PIME 的優點就全廢了。

**Comment by HPEACE** [comment]
@PCMan  確實現在已經都需要簽章才能比較不被誤攔，各家應該都有white list summit的機制，可以在發出前先summit給防毒廠商，以下為Symantec的
https://submit.symantec.com/whitelist/isv/

**Comment by PCMan** [comment]
@HPEACE 除了 symantec 之外我好像沒有找到可以事先 whitelist 的，多半都是誤判的時候再送 sample。
不過我在想，如果不管有沒有誤判，都直接 submit sample 出去說懷疑誤判，請他們檢查，或許可以達成 whitelist 的效果 XD

**Comment by HPEACE** [comment]
@PCMan  不曉得你有没有瀏覽過這網站
http://stackoverflow.com/questions/1177552/code-signing-certificate-for-open-source-projects
我没仔細看完，不曉得有没有可以免費用的

**Comment by HPEACE** [comment]
@PCMan 找到 利用自然人憑證對檔案簽章 http://atic-tw.blogspot.tw/2013/07/blog-post.html 不知道行不行 ^^

**Comment by PCMan** [comment]
@HPEACE 不行， Windows 應用程式簽章微軟有指定的廠商，不是任何憑證都有效。
一般的 SSL CA 機構都未必可以，要符合微軟的某一些要求，看起來只有某些大廠的可以，我查過價格都在一年六千台幣左右。
詳情見微軟文件 https://msdn.microsoft.com/en-us/library/ms537364(v=vs.85).aspx

**Comment by HPEACE** [comment]
@PCMan  系統那一段可能的確是要符合微軟的要求才不會在系統上跳出一些警訊什麼的，不過先在是要先閃過防毒的部份，應該二者是有區别的，有大廠的憑證當然好，我認為可以先求有再來看後續

**Comment by marvinyen** [comment]
看樣子沒有數位簽章 , 會一直被pc cillin封鎖, 只能自己解封鎖~~

![image 20161115001](https://cloud.githubusercontent.com/assets/23466888/20300869/0cc40648-ab5c-11e6-8b81-ca4560d60b83.jpg)

**Comment by PCMan** [comment]
剛放了 Release candidate (0.16 rc1) 供先行測試，沒有問題就放正式版
本次重點是測試防毒軟體相容性，如果有被誤判，可回報各家防毒網站：

* Windows defender: https://www.microsoft.com/en-us/security/portal/mmpc/developer/resources.aspx
* Symantec: https://submit.symantec.com/false_positive/  (我已經有送 whitelist 要求)
* BitDefender: http://www.bitdefender.com/submit/
* Avira: https://analysis.avira.com/en/submit
* Avast: https://www.avast.com/false-positive-file-form.php
* PC-cillin: http://www.trendmicro.com/us/about-us/detection-reevaluation/

目前我先送了 Symantec 的 whitelist 申請，還請各位幫忙試試其他防毒
如果沒有大問題，我就把 RC 改成正式版本供開發行了，謝謝。

**Comment by gith0927s** [comment]
小紅傘會誤報
![snap2](https://cloud.githubusercontent.com/assets/22462658/20638627/a5ddc4de-b3e7-11e6-9382-edf967b2ce49.jpg)

**Comment by menghuatan** [comment]
McAfee VirusScan Enterprise會誤判，白名單被公司鎖定無法新增。
提交McAfee並已跟他們說可以review source code，但從回覆看不出來他們會修改。

McAfee Labs - Beaverton                                                                
Current Scan Engine Version:5800.7501                                                  
Current DAT Version:8369.0000                                                          
Thank you for your submission.                                                         

Analysis ID: 10237928

File Name            Findings                       Detection                    Type         Extra
--------------------|------------------------------|----------------------------|------------|-----
pimelauncher.exe    |current detection             |rdn/generic.mem             |Trojan      |no   

current detection [pimelauncher.exe]                                                                    

   The file submitted is malware that can be detected with current DAT files. It is       
recommended that you update your DAT and engine files and scan your computer again.

**Comment by CDF5B9FAC9AD** [comment]
### 安装pime-rime后cpu飙满
在 *控制面板* 的 *输入法* 管理中删除pime后重启，电脑恢复正常。
**如果只保留pime，删掉win10自带微软拼音，不会出现cpu100%占用的情况！**

*SURFACE PRO4  win10家庭中文版 14393.576*

**Comment by mhtxi3d** [comment]
關於簽章，請問如果是使用廠商的 Code Signing Certificate 來簽的話，可以接受嗎？（也就是數位簽章上的名字會是購買 Code Signing Certificate 的廠商，而不是 PIME 專案）

**Comment by PCMan** [comment]
Fixed in 1.3.0 beta:
https://github.com/EasyIME/PIME/releases/tag/v1.3.0-beta
