### ISSUE TITLE
傳統注音聯想字詞能否協助修改成按Shift + 數字鍵選擇

### ISSUE THREAD

**Issue by Cheniyuan** [EasyIME/PIME#236]
開發者您好

我還有一群朋友，是早期用傳統注音的使用者
很謝謝PIME還有所照顧到我們這群在Windows 10下的傳統使用者。
目前用起來都還蠻就手，唯獨聯想字詞這個功能，
如果開啟聯想字詞功能，跟傳統的習慣不大一樣，
容易會出現不是我們要輸入的文字，希望下ㄧ版的傳統注音，
能把聯想字詞的功能，增加Shift鍵加上數字鍵的選擇方式。

謝謝你們的付出

**Comment by Llona** [comment]
同為傳統注音愛用者淚推~~~

**Comment by KenLuoTW** [comment]
已修正此問題。
