### ISSUE TITLE
PIME 0.16没有启动PIMELauncher.exe

### ISSUE THREAD

**Issue by zaqzrh** [EasyIME/PIME#237]
PIME 0.16 (development preview 2) 安装在windows 10_X64简体中文版中PIMELauncher.exe没有启动（系统重启后一样），不能输入汉字，需要手动启动，才能输入汉字，状态条才有“英”图。

**Comment by PCMan** [comment]
@zaqzrh 沒啟動也沒錯誤訊息?
手動可以正常啟動？
可幫查看系統 registry (regedit)
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run 下面有無 PIMELauncher 嗎？

**Comment by zaqzrh** [comment]
@PCMan 是的，没有任何错误信息，手动能正常使用,注册表run下面没有 PIMELauncher（以管理员身份安装也没有）

**Comment by PCMan** [comment]
@zaqzrh 抱歉我說錯了，路徑應該是
HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run
理論上 installer 會寫入 reg 到此處然後自動執行才是 :(

**Comment by chrishsieh** [comment]
同樣的狀況，繁體中文Win10。啟動清單上面有，但是看起來沒有啟動，需要手動啟動

**Comment by KenLuoTW** [comment]
有可能是 Win10 更新的問題,我公司的電腦是直接從 Win10 TH2 升級到 Win10 RS1 版本,
原本還可正常使用 PIME, 後來某次 Win10 小更新後,莫名奇妙就不能用了。
所以現在在公司,我就沒有在更新模組了,因為根本不能用,沒法測試正不正確。

不過我的狀況跟上面有點不同,啟動時會執行 PIMELauncher, 但是切換至平台下的輸入法後,
PIMELauncher 就直接關掉了。手動再次啟動 PIMELauncher,一樣也是一切輸入法就關閉了。

家裡主要在用的電腦,我沒有用升級的方式,而是重新安裝 Win10 RS1 版本,目前一切使用正常。
