### ISSUE TITLE
輸出顯示為簡體字

### ISSUE THREAD

**Issue by jeeyi345** [EasyIME/PIME#239]
安裝完於word2016輸入後發現，字體會跑掉，
變成H??Sin 有點忘記字形，類似繁體的新細明體，儘管文字本身為繁體字
word也會提示偵測到簡體字，因打出的字體都會跑掉，需手動反白修改
即使插入在其他字體（如標楷體）的某段落中間字體也會改成該類似新細明體字體，
暫時移除改回rime，然而rime有增加win10卡死或崩潰的感覺

我想會不會安裝後win10歸類在簡體下有關?
除此之外跟win10適應良好。
希望修正，因word為主要輸入範圍

**Comment by osfans** [comment]
显然有关 改到繁体下就好了。暂时只能手动改。

**Comment by jeeyi345** [comment]
請教一下如何修改?
記得於windows語言裡只有英文，中文-繁體，裡面新增也沒有相關選項
而PRIME中設定為拼音改注音輸入，可能簡繁體是在PRIME這設定的？

**Comment by s793016** [comment]
這就是這個 [bug](https://github.com/EasyIME/PIME/issues/172) 的 dupliated

**Comment by jeeyi345** [comment]
原來如此，看得不是很明白。
看起來似乎還沒解決吧？
如果有正常使用的設定方法請再指點一下，謝謝

**Comment by s793016** [comment]
[這篇隨附的 reg 檔](https://github.com/EasyIME/forum/issues/9#issuecomment-246923041) 應該可以解吧。

解開點兩下直接匯入，然後手動到輸入法設定把簡中下的 rime 移掉，新增繁中的 rime。

**Comment by osfans** [comment]
暫時關閉，如reg導入有問題，可以繼續討論。

**Comment by jeeyi345** [comment]
使用OK
中途遇到一點小問題，移除RIME時誤停留在小狼毫下，移除不乾淨，PRIME也失敗，重新安裝並移除小狼毫、安裝PRIME即沒問題，謝謝。
