### ISSUE TITLE
Win10 + 0.9 to 0.10 安裝失敗

### ISSUE THREAD

**Issue by cwchiu** [EasyIME/PIME#24]
於系統有安裝 0.9 情況下, 執行 0.10 安裝程式
出現
"
安裝發生錯誤，無法完成。

有時是有檔案正在使用中，暫時無法刪除或覆寫

建議重新開機後，再次執行安裝程式。
"

1. Program Files 的 PIME 目錄存在
2. 系統輸入法設定仍殘留"不明輸入法"
3. PIMELauncher.exe 和 pythonw.exe 仍在運行

將上述問題排除後後可安裝新版程式

**Comment by dukelee** [comment]
我都直接重新開機，就可以了。
