### ISSUE TITLE
PIME-0.16-dev2 設定輸入法模組時無法開出新酷音的設定頁面

### ISSUE THREAD

**Issue by HPEACE** [EasyIME/PIME#241]
不知道是没人測還是没人回報
這版在新酷音時，於工作列的圖示上按滑鼠右鍵設定輸入法模組時無法開出新酷音的設定頁面

**Comment by ottokang** [comment]
應該是 chewing_ime.py 裡面 ID_SETTINGS 路徑設定的問題，目前也發現設定程式按下確定不會結束，但是設定會儲存。
