### ISSUE TITLE
怎麼用拼音輸入臺灣正題字

### ISSUE THREAD

**Issue by LearZhou** [EasyIME/PIME#244]
朙月拼音方案輸入字符集不是臺灣傳統正體的，比如詞組會輸入成「衆人」，而不是臺灣正體的「眾人」。

前身輸入法是可以用Ctrl + ~快捷鍵切換到臺灣正體字符集的，而非臺灣注音輸入。

這個選項比較重要和有用，希望能夠解決，多謝！

**Comment by osfans** [comment]
需要在default.yaml中添加luna_pinyin_tw

具體可參考：https://github.com/rime/rime-prelude/blob/master/default.yaml#L7
