### ISSUE TITLE
0.16 二個問題

### ISSUE THREAD

**Issue by HPEACE** [EasyIME/PIME#245]
1. 修改編碼表後重啟服務，仍没出現變動過的編碼字
2. 以前版本裡的重啟服務是（以下是我的script）
    TASKKILL /F /IM PIMELauncher.exe
    TASKKILL /F /IM pythonw.exe ＜---現在這個好像不用了
    start "" "C:\Program Files (x86)\PIME\PIMELauncher.exe"
目前版本的話重啟服務應該怎麼才正確呢？

補充一個問題，設定裡的編碼字數只會秀出安裝後的碼表字數，再去變動其他編碼或修改編碼表後並不會變動此字數（這是大易的狀態下，其他我不曉得，因為我不會其他的輸入法）

**Comment by KenLuoTW** [comment]
1 & 2: 應該 KILL 掉 pythonw.exe 即可,會自動再啟動。

3: 我測試是正常的:
https://youtu.be/DdKU1LIBeTE

**Comment by HPEACE** [comment]
@KenLuoTW 
1&2---問題是目前這個版本並没有pythonw.exe的程序在，只有python.exe
![image](https://cloud.githubusercontent.com/assets/20449305/20739106/e6a24fea-b6f2-11e6-9100-e25f75db532b.png)
3---以前不用確定出來再進去就會看到有變動了，原來新版本改了 =.=

**Comment by KenLuoTW** [comment]
是嗎,我還沒時間安裝新版本,因為電腦最近都不能重新開機,在跑東西。

3 的話,其實一直以來都須要重開設定視窗才會變動。
因為字數統計是模組在處理的,設定視窗只是去讀取模組處理出來的數據。

**Comment by HPEACE** [comment]
@KenLuoTW  辛苦了...
3 的話，我記得前版未按確定前是可以切換編碼表時直接看到裡不同的總字數變化的，不過没關係，按確定才能看也ok啦

**Comment by KenLuoTW** [comment]
以後有改再改成新酷音目前的設定方式,這樣才可以即時變動資料。

**Comment by YanjunLee** [comment]
taskkill 有一个 /T 参数，/T  终止指定的进程和由它启用的子进程。
用 `taskkill /F /T /IM PIMELauncher.exe` 更好些，防止误杀其它的python.exe进程。
```
TASKKILL /F /T /IM PIMELauncher.exe
start "" "C:\Program Files (x86)\PIME\PIMELauncher.exe"
```

**Comment by KenLuoTW** [comment]
更換碼表時已可刷新碼表統計資料。(https://github.com/EasyIME/PIME/commit/3017426efcdc1a04d73a0b371d7721a7e46b9c7a)
