### ISSUE TITLE
0.16 大新倉頡 標點符號輸入

### ISSUE THREAD

**Issue by mp66github** [EasyIME/PIME#246]
逗號和句號在0.16不能「直接輸出」（不需按空白鍵），
目前用0.14的版本是正常的。

作業系統：Win10

**Comment by KenLuoTW** [comment]
現在改成當你按下下一鍵時,才自動判斷,
因為這樣比較合理,且也可以支援有以符號編碼的對應表。

請參考下面這篇 TEST16 之後的討論:
https://github.com/EasyIME/forum/issues/3

![2016-11-30](https://cloud.githubusercontent.com/assets/12954277/20739168/72a9ad58-b6f3-11e6-881c-94002cadd017.png)

**Comment by mp66github** [comment]
另外，符號的「選字順序」有問題，例如：
輸入「kk」，「？」應排第一，現在排第三。
輸入「;」，「；」應排第一，現在排第一的是「ㄤ」。

**Comment by sirius95** [comment]
我也是大新使用，確實有上述情況，頓時不太適應....
請教一下樓上的朋友，要如何自行定義按鍵輸出想要的文字（句子）或符號呢？
有辦法這樣子做嗎？
感激不盡！謝謝～

**Comment by mp66github** [comment]
改字碼表？
PIME\python\input_methods\checj\cin\newcj.cin

我現在退回0.14了，0.16用不慣。

**Comment by sirius95** [comment]
$B9%A|(B0.14$BHG2D0JD>@\JT=4;zb{!$@_Dj@.<+8J4n]DE*(B $B<+Dj5AIdiK!"J8;z0?;z;l(B?$B!)(B

$BWO2fE*(B iPhone $BQ#Aw(B

mp66github <notifications@github.com<mailto:notifications@github.com>> $B1w(B 2016$BG/(B12$B7n(B17$BF|(B $B2<8a(B7:04 $BUmF;!'(B


$B2~;zb{I=!)(B
PIME\python\input_methods\checj\cin\newcj.cin

$B2f8=:_B`2s(B0.14$BN;!$(B0.16$BMQIT47!#(B

-

**Comment by KenLuoTW** [comment]
修正於 https://github.com/EasyIME/PIME/commit/9067f85701e34f08ea67a2be58c82dff33a7df18 。
完全取消常用字排序了,因為大新的碼表怎麼排序都是錯。

**Comment by KenLuoTW** [comment]
之前是改成大新倉頡一律不排序，不過剛剛將此變更為可選項目，請參考：
https://github.com/EasyIME/forum/issues/16#issuecomment-279204640
