### ISSUE TITLE
當按PIME-0.16「新酷音設定法」要進去設定時，不能跳出視窗。

### ISSUE THREAD

**Issue by cook2003** [EasyIME/PIME#247]
我的系統是win8.1(x64)
當我按進去要設定時，跳出一個視窗，告訴我這個檔案要用什麼開啟？
於是我選擇了筆記本，之後就一直用筆記本開起來。
誰告訴我要怎麼辦啊？

**Comment by mitch0118** [comment]
我猜...是副檔名.html的預設開啟被改成記事本了，去控制台看看應該可以改回來。

**Comment by PCMan** [comment]
@mitch0118 說的沒錯，修改檔案的預設程式即可
