### ISSUE TITLE
v0.10版本，符號選擇多重選單位置沒有從頭開始

### ISSUE THREAD

**Issue by taichunmin** [EasyIME/PIME#25]
重音符號→選擇多重的選單後→下一層選單不會從第一個選項開始

舉例說明：選擇常用符號後，選字框會從 `。` 開始，若選擇特殊圖形，則會從 `↘` 開始。

**Comment by PCMan** [comment]
Fixed in 1be4c03.

**Comment by taichunmin** [comment]
<(_ _)>
