### ISSUE TITLE
PIME如何打字後出現倉頡的組字字根?

### ISSUE THREAD

**Issue by yukent0406** [EasyIME/PIME#251]
不好意思,請教一下

小弟剛用了WIN 10,本身也是用倉頡,WIN 10環境下,裝了樓主的0.16版的話可以用倉頡或注音打字後,顯示[字根]嗎?

例如 輸入[是],出現字根為日、一、卜、人....

我裝完沒有看到能顯示字根的設定,故來求問^^

**Comment by KenLuoTW** [comment]
有在計劃中,尚未加入~

**Comment by KenLuoTW** [comment]
已更新於 https://github.com/EasyIME/PIME/commit/52907f6957078d1bab75e347a649bbaf591230f1 ，下個正式版本即可使用。
