### ISSUE TITLE
行列輸入法無法用數字鍵選聯想字詞

### ISSUE THREAD

**Issue by kevinfis** [EasyIME/PIME#255]
狀況：例如打O^Zv;- 組完字，"知" 字出現，按下數字 1 可輸出字並跳出聯想字視窗，但是按下數字鍵時卻是輸出數字，而不是數字鍵對應的關聯字，除了按空白會出現第1個關聯字而已。

另外，不重要順路提的:
1.打字行為的 智能輸入 不能勾選，請問是否這個功能還未開放？
2.行列輸入法的設定是跳出一個mshta.exe的視窗，這個視窗的連結預設都用ie開啟，不像注音輸入是開html瀏覽器設定。

win 8.1 x64      平台版本 0.16版

**Comment by Cheniyuan** [comment]
你關聯字，試試看是不是也被改成了，按Shift + 數字，才會出來，如果是的話，那就是這個功能變預設(我們打注音的是這樣的習慣)，就請作者改成選擇性功能即可，或是注音跟行列的關聯字選取的方式不一樣。

**Comment by 1abcd** [comment]
注音鍵位佔用了鍵盤上排數字鍵
我猜是這個原因注音選詞才要多按Shift選詞 (#236)
以倉頡來講上排數字鍵沒有被輸入法字根佔用
結果現在酷倉輸入法也要壓Shift選詞 (#252)

**Comment by KenLuoTW** [comment]
關於這個,因為我不希望同一系列的輸入法,有不同的操作方式,
故其它輸入法,也全部統一為須押住 shift + 數字鍵才能輸入詞庫。

**Comment by 1abcd** [comment]
我覺的未佔用上方數字鍵位的輸入法讓兩者皆行比較好

微軟的傳統注音輸入法選詞要按的Shift與數字可以看成這些代號!@#$%^&*(
（更老的xp系統還有不同標色）也有表示註明要按Shift+數字鍵

酷倉輸入法的按鍵沒按Shift為123456789，有按Shift為!@#$%^&*(
我怎樣想都覺的沒按Shift的123456789與候選窗表示的代號比較吻合
