### ISSUE TITLE
注音符號的輸入

### ISSUE THREAD

**Issue by q120144178** [EasyIME/PIME#259]
覺得生活上要打到注音符號的機會也不算少，
很好奇好像還沒有任何一個倉頡輸入法願意直接把注意的每個字當成漢字一樣去編碼耶！
如
ㄅ 女尸
ㄆ 女大
.... 對於熟悉拆字的人應該可以更有效率的打出注音符號吧

**Comment by 1abcd** [comment]
匚𠚣𠫓𠄎巜丂厂丩𡿨丅㞢彳𡰣𠮚卩厶丫𠃒𠀅乁幺又𠃑尢𠃋儿一㐅凵万兀广帀
找了一些山寨注音符號的漢字 (譬如他國使用的 "厂、儿、广")
我是想一般人沒那個眼力去分辨國字(一)和注音(ㄧ)的區別
要編入的話 注音(與聲調)符號要與漢字的倉頡碼有差異比較好
譬如難字開頭 #263 
(以上個人建議)

**Comment by q120144178** [comment]
也是 不知道中文輸入法有沒有辦法像日文字典一樣 可以在選字欄出現一些標籤或解釋可能可以改善這個問題

**Comment by 1abcd** [comment]
突然發現"弓人"的候選字編入了一個符號№的例子

**Comment by q120144178** [comment]
覺得
弓中 №
人難 ☠ 
這些小圖示很有趣，不過在網路上好像都沒有看到有人針對這些小圖示做出一張表，
跟大家分享要怎麼打出這些符號，我記得也可以打出溫泉的符號，但我忘了碼是什麼....

**Comment by osfans** [comment]
這邊有整理一些：

https://github.com/rime-aca/OpenCCDict/blob/master/ch2emoji/emoji_word.txt

**Comment by 1abcd** [comment]
回樓上上，我指的是萬用字元(Z按鍵、重字)回傳列表的排序邏輯，當然以人腦來猜的確應該由A~Z這樣子的排序。可是我輸入  "卜卜卜難重" 回傳列表的排序看起來很雜亂，我記得昨天輸入時是ㄇ在首位，今天打卻是ㄆ在首位，完全不是我預期的ㄅㄆㄇㄈ排列。

至於酷倉碼表已經被我挖到了
https://github.com/EasyIME/PIME/blob/master/python/input_methods/checj/cin/checj.cin

**Comment by q120144178** [comment]
這張表格好像只有圖示而已，沒有對應的倉頡碼耶！

**Comment by q120144178** [comment]
哈 打到這裡 現在突然有一個想法
不知道系統可不可以開發自定義的碼表，
如此一來沒有以上問題，畢竟每個人的常用字不一樣，何不能直接客製化

**Comment by InSb** [comment]
每樣碼表都有各自對符號的編碼。雖然倉頡自身有一套方法，但全靠背誦。
只了解某一種碼表的符號編碼也可以，或者改動自己常用的碼表，但一旦換用其他碼表就會很無奈。
現在還是要多利用 PIME 自己的「特殊符號」甚至「全形標點」、「簡易符號」功能才好。

如果能讓載入時額外加載一個只有符號編碼的碼表，且讓它最先被加載，可能方便些。

**Comment by 1abcd** [comment]
在ios的注音鍵盤打溫泉符號，按ㄨㄣㄑㄩㄢ然後♨️就會接在溫泉詞彙後面。或許PIME可以學ios以中文字詞替符號編碼。

**Comment by q120144178** [comment]
To 1abcd
其實PIME有這個功能喔 
注音的部分沒在用所以不曉得，而酷倉的部分，只要打如「尸廿日口 即STAR」就出現☆或★，而「heart」也可打出♥或♡，溫泉♨的部分也在碼表找到是「SSS」。

**Comment by 1abcd** [comment]
謝謝 q120144178 回答，現在的酷倉是以25個倉頡字根(也可以視為英文字母)來輸入中文(或符號)。例如輸入一人人弓(moon)顯示: 1. 月亮; 2. ☽; 3. ☾
而我想像的是使用詞彙表輸入符號，見圖片: 1. 🈷; 2. 月亮; 3. ☽; 4. ☾; 5. 月薪
![default](https://cloud.githubusercontent.com/assets/1331388/21740021/bec70314-d4e6-11e6-8ba8-4d264e71d7b3.PNG)

**Comment by KenLuoTW** [comment]
其實我不太建議去記碼表裡對一些特殊字型或圖形所定義的編碼,
不過之後會加入一個「用戶自訂編碼」的功能,讓一些個人慣用的編碼可以自行擴充。

**Comment by KenLuoTW** [comment]
@1abcd  以萬用字元查詢「卜卜卜難重」的排序問題已修正於 https://github.com/EasyIME/PIME/commit/a92e1765fdda03c3d4ea40f60fbf4c06120c4bfb 。

至於注音符號編碼的建議，我傾向於不修改原碼表，而是用擴展碼表功能，讓用戶個別新增。

表情符號的話，依序打「`E」，就有選單項目可選，內含 Unicode 9.0 所有的表情符號，所以也不須要去記碼表內的編碼。

**Comment by KenLuoTW** [comment]
擴展碼表功能已加入，目前可由 https://github.com/EasyIME/forum/issues/16 裡提供的測試版來測試。
