### ISSUE TITLE
增加難字輸入倉頡輔助字形

### ISSUE THREAD

**Issue by 1abcd** [EasyIME/PIME#263]
微軟新倉頡2010按難字加倉頡碼可以輸入輔助字形
難月:  ⺆⺝⺥⺼冂冖爫
難卜: ⺀⺊⻌⻍亠辶
難竹: ⺮𠂆
手機上的Google輸入法同樣也可以用難字輸入
ios 的輸入法可以從展開選單輸入
希望酷倉也增加此方法

**Comment by InSb** [comment]
以前未注意有這種辦法，現在想想，還不錯。
可以暫且自行編入碼表使用。
但可能有衝突，當心重碼增加。

補加編碼應 @KenLuoTW 。

**Comment by KenLuoTW** [comment]
可以改用雅虎倉頡的碼表,有支援這個。
或是把資料整理出來,我再加進去。
