### ISSUE TITLE
調整酷倉空格鍵行為

### ISSUE THREAD

**Issue by 1abcd** [EasyIME/PIME#264]
![default](https://cloud.githubusercontent.com/assets/1331388/21293854/4bc8829c-c56a-11e6-9207-70609fc72744.PNG)
上面是我的酷倉輸入法設定，我發現空格鍵的行為有時候是 "選字" 有時候是 "換頁" (在候選字數大於一頁時候空格鍵會換頁。由於ui的不明瞭，我無法發現候選字總數是否超出一頁 #252)。

我提議的調整是，按完字根，再按了空格鍵以後，結束字根組字，自動出第一個候選字並加上虛線底線(像是有虛線底線的人一變成有虛線底線的丘)，候選視窗仍然開啟仍然可選（選字後依設定顯示或不顯示聯想詞），等到敲下字根按鍵時，舊的候選視窗消失。

圖中第三個選項打勾時，禁止空格鍵選字，使用Enter選字。並且增加Shift+Space逆向換頁。

**Comment by InSb** [comment]
似乎需要設計一下了。
或許去 [EasyIME/forum](https://github.com/EasyIME/forum) 討論更好一些。

**Comment by KenLuoTW** [comment]
已修正於 https://github.com/EasyIME/PIME/commit/1e963e753c5cf4de016451623113cf9eabda703b

關於 #252 所提到的候選清單操作,其實一直都有這些功能,
其中上、下、左、右鍵會視候選清單的排列而自動變化。

以下為預設的行為:
```
上下左右鍵可移動游標。 
Page Up/Down 鍵可直接換頁。 
Home/End 鍵可直接切到首/尾項目。 
空白/Enter 鍵為送出選取項目的字串。 
鍵盤上方數字鍵 0~9 可直接送出項目編號後方的字串。 
```

至於「使用空白鍵作為候選清單換頁鍵」會在候選視窗僅有一頁時輸出所選項目,
其實當初是為了方便一些用戶的使用,與「直接輸出候選字 (當候選字僅有一個)」的概念類似,
不過這兩個特殊的變化,我也覺得很不理想。

目前我先將「使用空白鍵作為候選清單換頁鍵」改回完全僅作為換頁用,不再可輸出候選字。
至於「Shift+Space」逆向換頁是不可行的作法,這個組合鍵一直都是用來作為全/半形切換。
候選視窗的部份,要在 PIME 中改,不是由模組來修改的。
