### ISSUE TITLE
PIME的漢語拼音的聲調，如何定義為可選的輸入碼？

### ISSUE THREAD

**Issue by zaqzrh** [EasyIME/PIME#267]
PIME中的「漢語拼音（正體拼音\羅馬拼音\泰瑞拼音）」的聲調如何定義像RIME的「地球拼音」通過「正則」方式設置為可選的輸入碼？例如「拼」輸入pin或pin1（聲調12345可隨意定義任何字母和數字，如pin1=pin；）都可輸出。

**Comment by KenLuoTW** [comment]
目前拼音輸入法,僅會對於1聲的組字自動輸出,例如:
輸入 pin = pin1

2345 聲的組字,就沒有支援了。

其實你要的功能,應該是指無調拼音,這個你只要擁有無調拼音的碼表,即可達可,無須改程式碼。
