### ISSUE TITLE
win7 內容設定問題依然存在

### ISSUE THREAD

**Issue by KennethWong355** [EasyIME/PIME#271]
【系統：Win7， 測試版本 Pime0.14  至  v0.16.1 】 

有關 Win7 安裝完輸入法后，如果進入“文字服務與輸入語言”，更改 microsoft 的輸入法的內容設定（如倉頡，速成），會導致 ”microsoft IME 停止運作的問題“， 

## 請問可以在 release 版本中加以修復嗎？

https://github.com/EasyIME/PIME/issues/257

**Comment by PCMan** [comment]
請測試 1.0.0 rc 看是否有這個問題

**Comment by PCMan** [comment]
confirmed, 還是有問題，同 #257
