### ISSUE TITLE
定制輸入法行為 0.16版 問題請教

### ISSUE THREAD

**Issue by KennethWong355** [EasyIME/PIME#272]
## _問題請教_
我之前曾經下 **PIME 0.14** 請教過以下問題：

_我想把輸入法的候選字輸出個人化， 例如酷倉輸入法，現在打 “日”字， 只會出現 ‘’日‘’ 跟 ‘’曰‘’ 這
兩個字，但我想打 ‘’日‘’字的時候， 所有 “日" 字開頭的 字都會出現在候選字選單， 就如 (aaa 的 “晶") 和
(aitc 的“曠”) 。_

相關連結：
https://github.com/EasyIME/PIME/issues/155

現在我一樣把酷倉的 “cin.py” 的 ”def getCharDef(self, key)” 改成：

    def getCharDef(self, key, candMaxItems):
        keylength = len(key)
        chardefslist = []
        if self.isInCharDef(key):
            chardefslist.extend(self.chardefs[key])
        for chardef in self.chardefs:
            if key == chardef[:keylength]:
                for char in self.chardefs[chardef]:
                    if not char in chardefslist:
                        chardefslist.append(char)
                    if len(chardefslist) >= candMaxItems:
                        return chardefslist
        return chardefslist

然後在 cinbase 下的 init.py 改成:

            # 組字字根超過最大值  (Line 1310)
            if len(cbTS.compositionChar) > cbTS.maxCharLength:
                if cbTS.cin.isInKeyName(cbTS.compositionChar[len(cbTS.compositionChar)-1:]):
                    keyLength = len(cbTS.cin.getKeyName(cbTS.compositionChar[len(cbTS.compositionChar)-1:]))
                else:
                    keyLength = 1
                if cbTS.compositionBufferMode:
                    self.removeCompositionBufferString(cbTS, keyLength, False)
                else:
                    cbTS.setCompositionString(cbTS.compositionString[:-keyLength])
                cbTS.compositionChar = cbTS.compositionChar[:-1]

_加入：_
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		if cbTS.imeDirName == "checj":
			candidates = cbTS.cin.getCharDef(cbTS.compositionChar)
			if cbTS.sortByPhrase and candidates:
				candidates = self.sortByPhrase(cbTS, copy.deepcopy(candidates))
			if cbTS.compositionBufferMode and not cbTS.selcandmode:
				cbTS.compositionBufferType = "default"

也試過：
		if cbTS.imeDirName == "checj":
			candidates = cbTS.cin.getCharDef(cbTS.compositionChar + '1', cbTS.candMaxItems)
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////
					
            elif cbTS.cin.isInCharDef(cbTS.compositionChar) and cbTS.closemenu and not cbTS.ctrlsymbolsmode and not cbTS.dayisymbolsmode:  # If => elif
                candidates = cbTS.cin.getCharDef(cbTS.compositionChar)
                if cbTS.sortByPhrase and candidates:
                    candidates = self.sortByPhrase(cbTS, copy.deepcopy(candidates))
                if cbTS.compositionBufferMode and not cbTS.selcandmode:
                    cbTS.compositionBufferType = "default"
					
            elif cbTS.imeDirName == "chepinyin" and cbTS.cinFileList[cbTS.cfg.selCinType] == "thpinyin.cin" and not cbTS.ctrlsymbolsmode:
                if cbTS.cin.isInCharDef(cbTS.compositionChar + "1") and cbTS.closemenu and not cbTS.ctrlsymbolsmode:
					candidates = cbTS.cin.getCharDef(cbTS.compositionChar + '1')
                    if cbTS.sortByPhrase and candidates:
                        candidates = self.sortByPhrase(cbTS, copy.deepcopy(candidates))
                    if cbTS.compositionBufferMode and not cbTS.selcandmode:
                        cbTS.compositionBufferType = "default"	

## 但都不成功，所以請教一下，現在 在 PIME 0.16 應該要怎樣改？

**Comment by KenLuoTW** [comment]
參考 getWildcardCharDefs 的部份:
https://github.com/EasyIME/PIME/blob/master/python/cinbase/cin.py#L268-L355

其實你把 287 行的 regex 改一下,並將 keyLength 的限制拿掉,也就達到了你要的結果。
如果不依常用字排序,後面不用寫得那麼複雜。

**Comment by KenLuoTW** [comment]
前面我沒注意看,不過看到後面有誤:
```
if cbTS.imeDirName == "checj":
candidates = cbTS.cin.getCharDef(cbTS.compositionChar)
```
我今天已經把所有模組的 cin.py 合併到 cinbase 資料夾下的 cin.py。
所以之後可能又要改掉,先說一下 0.16 怎麼改好了。
```
if cbTS.imeDirName == "checj":
    candidates = cbTS.cin.getCharDef(cbTS.compositionChar, cbTS.candMaxItems)
```
