### ISSUE TITLE
新酷音全形半形符號問題

### ISSUE THREAD

**Issue by passeralpha** [EasyIME/PIME#274]
在中文模式下預設的"＝"都會打成全形

請問一下有辦法把這些非注音的鍵"＝「」、"改成半形嗎?

謝謝

**Comment by KenLuoTW** [comment]
問題同 #148 。
我覺得可以弄個選項,讓用戶在按下符號鍵時能夠選擇要輸出全形或半形。
因為新酷音原始的設定,不一定是最好的,輸入法還是要符合人性才好。

**Comment by ottokang** [comment]
稍微實做了一下，做個對照表轉換一下就可以，目前是想要用鍵盤上有兩個符號的按鍵，中文模式下按 Shift 會輸入下方的符號，（例如：-=[]\;',./`），這樣應該可以符合需求

**Comment by ottokang** [comment]
新增半形符號選項 #306
