### ISSUE TITLE
新酷音網路辭典網址失連

### ISSUE THREAD

**Issue by 1abcd** [EasyIME/PIME#278]
教育部國語辭典簡編本點下去後404找不到

另外，下面提供我整理的一些網址

教育部重編國語辭典修訂本
http://dict.revised.moe.edu.tw/cbdic/

教育部國語辭典簡編本
http://dict.concised.moe.edu.tw/jbdic/

教育部國語小字典
http://dict.mini.moe.edu.tw/

教育部成語典
http://dict.idioms.moe.edu.tw/

臺灣閩南語常用詞辭典
http://twblg.dict.edu.tw/holodict_new/index.html

國家教育研究院雙語詞彙、學術名詞暨辭書資訊網
http://terms.naer.edu.tw/

教育部教育百科
http://pedia.cloud.edu.tw/Home/list?search=

教育部異體字字典
http://140.111.1.40/

中央研究院國際電腦漢字及異體字知識庫
http://chardb.iis.sinica.edu.tw/

常用國字標準字體筆順學習網
http://stroke-order.learningweb.moe.edu.tw/home.do

《重訂標點符號手冊》修訂版
http://language.moe.gov.tw/001/Upload/FILES/SITE_CONTENT/M0001/HAU/c2.htm

**Comment by ottokang** [comment]
字典我留著預設的字典，更新了連結 #279
