### ISSUE TITLE
酷倉中「汞」字的輸入

### ISSUE THREAD

**Issue by q120144178** [EasyIME/PIME#280]
不好意思，對於習慣於三代倉頡的用戶來說，
「反」字應該會很習慣的輸入「竹水」吧？
而酷倉本來就是以三代的打法為主，
不解的地方在於為什麼當輸入「一水」的時候出來的字不是「汞」而是「反」？
而且還不能夠用「難一水」來得到「汞」字，實在是有點不便，
還請開發者能夠修正這個情況，辛苦了！！

**Comment by KenLuoTW** [comment]
預設碼表採用的是泰瑞先生所編修的碼表,其為混合三代、五代及勘誤的碼表,
一水組反有其意義存在,與其相關組字依據的組字也少,如將之移除或掉換順序,
其它相關組字是否也要跟著做變動?所以在原作者未更改下,我暫時不會去動這個。

可改用倉頡或雅虎倉頡...等三代為主的碼表。

**Comment by q120144178** [comment]
嗯 了解 謝謝你的回覆，
但是我是建議像是汞或是豚
這些字是不是可以把「難」字加在前面的輸入碼

**Comment by KenLuoTW** [comment]
原作者有加了很多類似的編碼在裡頭,我明天會把裡頭有多組字根的字貼在
https://github.com/EasyIME/forum
到時再來檢討這個碼表要如何改良。

**Comment by q120144178** [comment]
好的 這個真的很值得討論
之前我是不用大新倉頡的，但是這幾天接觸大新倉頡後發現，
這個輸入法遇到重碼字時用了「;」鍵也是注音ㄤ的位置，
當要輸入在「知」後的「佑」字時可以打「人大口+;+SPACE」，覺得這是非常好的想法，
但是他的缺點是在「;」後的SPACE顯得多餘，;不可能再有重碼的問題
如果酷倉可以把這些重碼字變成 直接將SPACE取代成另外一個好打的鍵，可降少按按鍵的次數呢！

**Comment by InSb** [comment]
輸出第二、第三候選項常用`;（分號）`、`'（單引號）`這一組，或`左Shift`、`右Shift`這組。

**Comment by KenLuoTW** [comment]
之後請轉至 https://github.com/EasyIME/forum/issues/15 討論

至於「人大口+;+SPACE」,其實並不是很好的想法,對於時常中英混輸的人來說,例如 #274 
符號相關的按鍵,不要定義字根會比較好,這也是為何酷倉預設碼表,
為何不沿用「泰瑞倉頡」碼表,而要去除符號編碼的原因。
但是如果打純中文文章,那麼直接輸出全形符號會比較方便,此時可直接選用「泰瑞倉頡」碼表。

「知」後的「佑」字,在酷倉中可直接打「人大口+2」,一樣也是減少了按鍵的次數。
