### ISSUE TITLE
可否提供給win7免安裝的步驟

### ISSUE THREAD

**Issue by getoutnow2013** [EasyIME/PIME#282]
pcman您好，因為公司電腦連安裝輸入法都要被管制。所以是否可以提供一個免安裝的步驟，來啟動PIME輸入法？謝謝！

**Comment by KenLuoTW** [comment]
權限問題,檔案須放在 Program Files 下,也須管理員權限登錄機碼,
再加上使用時會鎖住 DLL 檔,故無法製成可攜版。
