### ISSUE TITLE
請問詞庫路徑？

### ISSUE THREAD

**Issue by nonolucky** [EasyIME/PIME#284]
請問是否可以提供選項重置詞庫或是提供路徑呢？ 謝謝

**Comment by ottokang** [comment]
Windows 下詞庫的路徑是在%APPDATA%（C:\User\[使用者名稱]\AppData\Roaming）下的PIME\chewing，裡面的 chewing.sqlite3 就是詞庫了，要重置應該把詞庫刪掉就可以了
