### ISSUE TITLE
新增詞彙無法新增詞句

### ISSUE THREAD

**Issue by cmhdream** [EasyIME/PIME#285]
無法新增  姿蓉 這兩個字詞

**Comment by KenLuoTW** [comment]
已用最近更新的 Code 檢測過, 確認已修正此問題。

**Comment by cmhdream** [comment]
謝謝，其實我已經移除了。不過還是感謝你。

2017-01-25 2:47 GMT+08:00 Ken Luo <notifications@github.com>:
