### ISSUE TITLE
pime-rime能否以横排显示后选词？

### ISSUE THREAD

**Issue by CDF5B9FAC9AD** [EasyIME/PIME#286]
rt

**Comment by CDF5B9FAC9AD** [comment]
没有找到合适的wiki来diy

**Comment by osfans** [comment]
基本上修改PIME.yaml就好。
https://github.com/EasyIME/PIME/blob/master/python/input_methods/rime/data/PIME.yaml#L17

橫排修改這個，大於1就好。

**Comment by CDF5B9FAC9AD** [comment]
**谢谢！**
@osfans 颜色等主题的定制暂时还不可以是吗？    自定义用户文件夹的位置是否和小狼毫一样？

**Comment by osfans** [comment]
差不多，小狼毫是Rime目錄，這個是PIME/Rime目錄。

皮膚的在我那裏有做，還沒做完所以沒有合併過來。
https://github.com/osfans/PRIME/releases

**Comment by Yunzj** [comment]
可以的，打开PIME.yaml文件，找到candidate_per_row: 9把原来那个9改5然后重新部署一下就横了，也可以重启或注销一下电脑。。

**Comment by osfans** [comment]
還有rime特有的問題的話，可以去osfans/prime那邊討論。
