### ISSUE TITLE
請問學習功能?

### ISSUE THREAD

**Issue by nonolucky** [EasyIME/PIME#287]
不知道有沒有可能關閉學習功能? 目前的使用經驗上，只要輸入過就會自動新增至辭庫，打錯的詞彙也會一併新增。

**Comment by mitch0118** [comment]
可以手動刪掉打錯的詞彙

**Comment by nonolucky** [comment]
但只要打錯一次就立馬新增到詞庫，例如"真類"，這樣每一次只要錯誤就要進去詞庫裡面刪除，有點不方便，還是希望能有關閉學習功能的選項，讓使用者自行新增詞彙。
