### ISSUE TITLE
[問題] 九宮格鍵盤數字鍵當輸入法

### ISSUE THREAD

**Issue by uranus0206** [EasyIME/PIME#293]
我再新編譯的PIME中增加了自訂的三角輸入法。初步安裝起來後一般上方的數字鍵可以當作輸入法使用，但是右邊的九宮格數字還是依然直接輸出數字。是因為keycode不同嗎？請問我要如何改才能讓右邊的九宮格數字也能當作字根輸入呢？

**Comment by rocfatcat** [comment]
Virtual Keycode 是不一樣的
可參考https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx
Numeric keypad 部分

**Comment by uranus0206** [comment]
請問那我是不是只要在cinbase的filterKeyDown將NUM_PAD的Keycode - 0x30就可以轉換成一般數字鍵來當作輸入法字根？還是還有哪幾個部份需要注意的？因為我一直嘗試在filterKeyDown跟onKeyDown這兩個函式加入條件轉換，但是一直失敗。

**Comment by KenLuoTW** [comment]
filterKeyDown 先判斷 NUMLOCK 燈號是否亮著,然後再
```
        if keyEvent.isKeyToggled(VK_NUMLOCK): # NumLock is on
            # if this key is Num pad 0-9, +, -, *, /
            if keyEvent.keyCode >= VK_NUMPAD0 and keyEvent.keyCode <= VK_DIVIDE:
                return True
```
onKeyDown 裡再針對這幾個鍵去處理。
