### ISSUE TITLE
Chrome windows 10 无法输入中文

### ISSUE THREAD

**Issue by baoming** [EasyIME/PIME#295]
windows: Windows 10 x64
chrome: 版本 56.0.2924.59 beta (64-bit)
pime: PRIME PRIME-0.16.1-setup-20170105.exe

问题描述：
在chrome浏览器下只能输入英文，但在其它窗口可以正常输入中文
切换和重新部署输入法，都无法激活输入法

**Comment by osfans** [comment]
除了rime模塊，其他模塊也是這樣嗎？

**Comment by KenLuoTW** [comment]
windows: Windows 10 x64 （1607）
chrome: 版本 56.0.2924.59 beta (64-bit)
pime: PIME v0.16.1 正式版

新酷音、CIN 糸列、RIME 皆可使用。

**Comment by laubonghaudoi** [comment]
请问楼主能否在UWP应用下使用？
