### ISSUE TITLE
win10 x64 PRIME无法启动

### ISSUE THREAD

**Issue by yurocy** [EasyIME/PIME#298]
![qq 20170118095038](https://cloud.githubusercontent.com/assets/9815561/22047745/bebb49fe-dd63-11e6-978c-b73a6388ff03.png)

安装0.15.2启动正常。

**Comment by zaqzrh** [comment]
PIME 0.16.1很不稳定，问题多

**Comment by osfans** [comment]
需要排查是Rime模塊的問題，還是PIME平臺的問題。

**Comment by KenLuoTW** [comment]
我是建議還未併入 PIME 的自訂版本,不要 PO 在這邊,
免得正式版跟測試版的問題都混在一起討論,
可改到 https://github.com/EasyIME/forum 討論。

剛在虛擬機下的 Win10 32bit 下裝了一下 PRIME,覺得編譯環境應該有問題,
因為還提示缺少 VS2015 的組件,裝回 PIME 的正式版就正常了。

**Comment by osfans** [comment]
@KenLuoTW  那個是cmake 3.7的問題，暫時還沒有解決。

**Comment by osfans** [comment]
已重新上傳 https://github.com/osfans/PRIME/releases/download/prime/PRIME-0.16.1-setup-20170106.exe
PRIME那邊也開了issues，歡迎使用。
