### ISSUE TITLE
On Windows 10, we can only type english

### ISSUE THREAD

**Issue by zvn** [EasyIME/PIME#3]
After building the project according the readme.md, I can see the 2 new input method, including chewing and meow appearing. 

After switching to "meow", I can only type English. And I cannot switch to chewing.
Then I tried to switch back to Microsoft built-in chewing and then try to switch to the new chewing, I still cannot type Chinese characters. There's no any pop-up window or dialog indicating that I am typing Chinese words.

By the way, may I know how to debug? Or anyway to redirect the logs into a log file without changing code?

**Comment by zvn** [comment]
oh... I guess I got the root cause.. I forgot to install pywin32 package on my laptop. will try it again and close this issue if it works

**Comment by zvn** [comment]
bad news, the problem still exists after installing pywin32 packages..

**Comment by PCMan** [comment]
請問最新版本還會嗎? v0.10

**Comment by zvn** [comment]
新酷音 in 0.10 works. But when I tried to fork the latest code on GitHub, build and install manually, the problem persists. So maybe there are something missed in the manual installation steps. Will close this issue first since I cannot provide what I missed here.
