### ISSUE TITLE
[rime]僅在一方案配置alternative_select_labels導致所有方案均為該labels

### ISSUE THREAD

**Issue by thothit** [EasyIME/PIME#300]
#207 #212 
如題，僅在一方案內配置

    menu:
      alternative_select_keys: "ASDFGHJKL"
      alternative_select_labels: [甲, 乙, 丙, 丁, 戊, 己, 庚, 辛, 壬] 

導致所有方案均為此款labels。

另，單獨方案設置style/menu/page_size無效。

**Comment by osfans** [comment]
確實有這個問題，還有跟部署不立即生效有關。

**Comment by osfans** [comment]
e7915f6e29696c2776f5d5c2c6fca9eb5bd65b60 解決
