### ISSUE TITLE
打不出 "亘" 字

### ISSUE THREAD

**Issue by ericsuperman** [EasyIME/PIME#301]
因為某間餐廳用了 "亘" 字，讓我注意到這個字用新酷音的注音打不出來。
它發音跟 "宣" 一樣，微軟的新注音輸入法打的出來。

**Comment by osfans** [comment]
在大陸 亘爲亙的簡化字。
查了康熙字典，亘可以讀宣或者桓。

**Comment by hiunnhue** [comment]
根據教育部異體字字典，「亘」是……
  * 「宣」的本字
  * 「桓」的異體
  * 「亙」的異體（有 ㄍㄣˋ 和 ㄍㄥˋ 兩種讀音）

但教育部《重編國語字典修訂本》只有提到「亘」是「亙」的異體字。

新酷音可以用 ㄍㄣˋ 和 ㄍㄥˋ 打出「亘」。

**Comment by ericsuperman** [comment]
謝謝，原來是有多種讀音。
不過，餐廳老闆跟我說要讀 "宣"，
微軟的新注音輸入法也可以用 "宣"讀音 打出 "亘"，
可否 讓 新酷音 也能用 用 "宣"讀音 打出 "亘" 呢？

**Comment by 1abcd** [comment]
國際電腦漢字及異體字知識庫
漢字「亘」：基本資料
http://chardb.iis.sinica.edu.tw/search.jsp?q=%E4%BA%98&x=0&y=0&stype=0
讀音有ㄒㄩㄢ和ㄍㄣˋ

我在猜大概傳統中文很大程度被簡體中文影響
所以只有收錄「亙」的讀音
以下是紫光华宇拼音输入法V6的漢字屬性
![default](https://cloud.githubusercontent.com/assets/1331388/22595325/fa1fdcac-ea61-11e6-9f37-bc22a793e5dc.PNG)

**Comment by KenLuoTW** [comment]
要新增或校正新酷音的注音對應表,應該在下面連結回報及建議:
https://github.com/chewing/libchewing/issues

因為這個對應表是新酷音團隊在維護的, 所以在這邊回報並沒有用。
