### ISSUE TITLE
同音字查詢功能

### ISSUE THREAD

**Issue by cerebellum92** [EasyIME/PIME#302]
首先謝謝各位做出這麼強大的輸入法框架，適用各種不同的輸入法。
我有一個小小的建議，官方的嘸蝦米輸入法有一個很好用的功能叫同音字查詢。
這樣如果忘了一個字怎麼寫，只要知道其中一個同音字的字碼，就可以列出同音的所有字
如此不用轉換輸入法就可以利用注音來找字。
如果可以實做這個功能，可以造福所有拆字型的輸入法！
請考慮考慮！
謝謝！

**Comment by KenLuoTW** [comment]
實作不難，但會多佔用記憶體，故尚須考慮一下。

**Comment by cerebellum92** [comment]
可以考慮做成選項，預設關閉，想用的人必需額外載入(重開機或重登入才生效)？
謝謝納入考慮！

**Comment by KenLuoTW** [comment]
不須重新開機，啟用後才會將之載入記憶體內，並可立即調用。
順便問一下，嘸蝦米中同音字查詢是用什麼方式輸入？

**Comment by cerebellum92** [comment]
嘸蝦米是用enter 鍵旁邊的單引號(')，現在我是自己匯入字典檔(取代其中一個倉頡的字典檔)，目前如果按下', 再按其它鍵就會直接輸出丶這個符號

**Comment by KenLuoTW** [comment]
嘸蝦米的方式可能無法套用,因為這功能得套用到各種輸入法模組內,
有些輸入法已將「'」設為字根或選字鍵,故會有衝突。

目前想到的是:
選項加入「啟用同音字查詢功能」,啟用後才載入注音碼表。
用輸入法輸入同音字後,然後在候選清單顯示時,按下鍵盤左上角的「`」鍵,
即將候選清單改為「同音字清單」,選好同音字後,顯示該模組的字根提示。

若覺得可以,我就開始實作。

**Comment by cerebellum92** [comment]
這個方法或許比嘸蝦米官方的方法還好！謝謝！

**Comment by KenLuoTW** [comment]
此功能已完成,用法請參考:
https://github.com/EasyIME/forum/issues/16
