### ISSUE TITLE
自由大新倉頡選字順序異常

### ISSUE THREAD

**Issue by lyenliang** [EasyIME/PIME#304]
自由大新倉頡原本選字的順序都是固定的，原本`;`鍵有設計用來選 候選名單 內下個字的功能
例如
`h + 空白鍵`對應到候選名單的第一個字「的」
`h + ; + 空白鍵`對應到候選名單的第二個字「竹」

但是PIME 的自由大新倉頡似乎是為了要把常用字移到候選名單前面的關係，而會動態調整候選字表的順序，例如我本來想打一句「今天我買了新的書」，結果似乎因為輸入法判定「新竹」比「新的」常出現，而導致我原本的打法會變成「今天我買了新竹書」。

希望這套輸入法不論在何種情況下，它的候選字表的順序都能保持不變，這樣比較符合當初的設計。

**Comment by KenLuoTW** [comment]
你所說的情況是可選功能,可以自行關閉 (優先以聯想字詞排序候選清單)。

而且以下情況既使開啟此功能,也不可能會發生。
```
h + 空白鍵對應到候選名單的第一個字「的」
h + ; + 空白鍵對應到候選名單的第二個字「竹」
```
因為 h + ; 在碼表中沒有定義「的」

碼表的排序也在大新倉頡裡取消,請參考 #246

**Comment by lyenliang** [comment]
感謝 KenLuoTW 的回答！Orz
原來這個功能早就是可選的

**Comment by KenLuoTW** [comment]
之前是改成大新倉頡一律不排序，不過剛剛將此變更為可選項目，請參考：
https://github.com/EasyIME/forum/issues/16#issuecomment-279204640
