### ISSUE TITLE
在命令模式滾動滑鼠的問題

### ISSUE THREAD

**Issue by HPEACE** [EasyIME/PIME#307]
如題，好像没人發現....
![image](https://cloud.githubusercontent.com/assets/20449305/22876930/eb6d9880-f20d-11e6-809b-49e25dd5198c.png)

**Comment by osfans** [comment]
發現了，但是微軟輸入法也有，估計不好解。

**Comment by HPEACE** [comment]
原來這是微軟本身的問題，看來就只能等微軟解決了

**Comment by KenLuoTW** [comment]
目前可暫時核取「使用舊版主控台」以解決此問題。
![2017-02-16](https://cloud.githubusercontent.com/assets/12954277/23007279/92a5d672-f442-11e6-9985-05de1d714386.png)

**Comment by Yunzj** [comment]
这个应该是WIN10的问题。。。
最新版win10更新时，整个屏还会闪闪啊。。
