### ISSUE TITLE
如何設置間繁體？

### ISSUE THREAD

**Issue by laubonghaudoi** [EasyIME/PIME#308]
PIME 0.16.1版本，是否支持輸入簡體字？

**Comment by baoang** [comment]
我用WIN10，现在输入的就是简体字，我用五笔（86），但是没发现如何令PIME像小狼毫一样拼音五笔混输

**Comment by laubonghaudoi** [comment]
> 我用WIN10，现在输入的就是简体字，我用五笔（86），但是没发现如何令PIME像小狼毫一样拼音五笔混输
请问是怎么设置的？而且我现在win10只能在win32程序上用，UWP程序用不了

**Comment by baoang** [comment]
不知道呢，我安装好之后从小狼毫调成PIME，就直接输入的是简体字。

**Comment by osfans** [comment]
rime簡繁、拼音五笔混输的問題，可以轉rime那邊去討論。因爲都是通用的，跟平臺無關。

**Comment by laubonghaudoi** [comment]
> 不知道呢，我安装好之后从小狼毫调成PIME，就直接输入的是简体字。

如何把小狼毫调成PIME？

**Comment by laubonghaudoi** [comment]
我按照這個教程增加了.custom.yaml文件並加入reset: 1之後仍然是繁體字
http://blog.yesmryang.net/rime-setting/

**Comment by laubonghaudoi** [comment]
已经解决，需要在设置完毕之后按Ctrl+`然后选汉字→漢字
