### ISSUE TITLE
擴展碼表的問題

### ISSUE THREAD

**Issue by cerebellum92** [EasyIME/PIME#310]
我有點搞不清擴展碼的用法。
我試著加入一些自定的對應碼，例如：
n 嗯
hah 憾
不過無法生效
如果我加入：
email my@email.account
或其他英文如：
bmail haha
n gaga
則會生效
我猜是不是只有原本不在碼表內的字(串)才會生效？
又，有時候有些自定的編碼是想要優先於原本碼表內的字的，
例如，在嘸蝦米輸入法中，n 原本是南，不過我想要讓n = 嗯 優先於南
也是就是按下n，候選字會是1. 嗯 2. 南
請問有辦法實做這個功能嗎？
我知道這對嘸蝦米輸入法很有幫助，不知道對其他輸入法有沒有幫助？

**Comment by KenLuoTW** [comment]
無法生效的問題應該與 #144 的問題一樣,我會連同新酷音模組一併修復。

擴展碼表如要優先,之後會加入選項讓用戶自行選擇。

**Comment by KenLuoTW** [comment]
已經修正,下一測試版會放上。

**Comment by KenLuoTW** [comment]
已加入「優先載入擴展碼表」選項。 ( https://github.com/EasyIME/PIME/commit/667679550802e88d8cdb4ea4c7d2fb3ee0e602d2 )
