### ISSUE TITLE
Windows 10 安裝時除了README所述是否還有其他必須操作?

### ISSUE THREAD

**Issue by davidleeplaysmart** [EasyIME/PIME#311]
我在依照README去build完之後, 把PIMETextService/debug/PIMETextService.dll以及python, node資料夾都放到指定位置.

並且regsvr32執行時也未出現錯誤, 但是卻無法在輸入法選擇新酷音, 請問跟我是在VM上面使用未輸入啟動碼的windows10有關嗎? 還是其實還有其他步驟要做呢?

**Comment by davidleeplaysmart** [comment]
抱歉，似乎不是這樣的問題，我啟動後仍然無法選擇新酷音，請問我有缺少什麼步驟嗎？(除了README之外有其他必須執行的動作嗎？)謝謝！

**Comment by KenLuoTW** [comment]
那個說明有些新版的變動沒寫進去,請參閱 installer 腳本的內容找出自己遺漏的部份。

**Comment by davidleeplaysmart** [comment]
謝謝提供資訊，我會去看看

**Comment by davidleeplaysmart** [comment]
我發現根據install script ... 我的dll檔案應該在build/build64下面, 但是其實我沒有在該資料夾下面看到, 這樣是我build錯project了嗎? 我是用VS開在PIME根目錄下面的PIME project來按建置全部的內容, 不知道正確來說應該要build什麼地方呢? 不好意思問題不少 如果有相關文件懇請指出我也很願意自己去看 不好意思 謝謝!

**Comment by KenLuoTW** [comment]
比較簡單的方法就是建立一個獨立的資料夾,先從 GITHUB 衍生目錄拷貝所須的檔案,
然後再將 VS 下建置好的 PIMELauncher.exe 及 PIMETextService.dll (x86/x64)分別拷貝至指定的目錄,
最後再用 NSIS 直接建置安裝檔,建置完後就可安裝使用了。

![2017-02-24](https://cloud.githubusercontent.com/assets/12954277/23307925/50afc838-fae4-11e6-93d6-468fb5f3346d.png)

**Comment by davidleeplaysmart** [comment]
謝謝！我安裝成功了！
不好意思再問一個小問題...如果我嘗試改動了python裡面的檔案, 我需要重新安裝嗎？還是我可以直接把python檔案在Program Files(x86)裡面對應的資料夾修改就好呢？
再次感謝您的回覆和幫助 感恩

**Comment by KenLuoTW** [comment]
這個明天上班時,我再回覆你,要先休息了。

**Comment by KenLuoTW** [comment]
僅改動 Python 裡面的檔案可以不用重新安裝,你可以直接在 Program Files(x86) 資料夾內修改。
如果是要新增輸入法模組,則重新安裝會比手動去處理方便。

修改好 Python 檔案並存檔後,如要測試修改後的內容,必須結束目前正在執行的 Python.exe 進程,然後用 Python3 資料夾裡的 Python.exe 執行 server.py,例如:
![2017-02-25 1](https://cloud.githubusercontent.com/assets/12954277/23325944/43ae4f10-fb34-11e6-88ce-2606e182054e.png)

當你在結束 Python.exe 進程前,你須要先切換到 PIME 平台下輸入法模組以外的輸入法,並點擊所有有用過 PIME 平台下輸入法模組的視窗,最後再去結束 Python.exe 進程。
否則目前 PIME 的 PIMELauncher.exe 會自動再啟動 Python.exe 去執行 server.py。

或是也可以先將 PIMELauncher.exe 進程結束掉,再將 Python.exe 進程結束。
之後先使用 Python.exe 執行 server.py, 再執行 PIMELauncher.exe 即可。

另外如果你要在 CMD 顯示一些 Code page 950 (繁體系統) 以外的中字,請參考 https://github.com/EasyIME/PIME/issues/97 。

**Comment by davidleeplaysmart** [comment]
再次感謝 回復得超級詳細 3q
