### ISSUE TITLE
請問 PIME 輸入法 v0.16.1 如何使用粵拼和設置安裝路徑？

### ISSUE THREAD

**Issue by DingChil** [EasyIME/PIME#312]
安裝時有提示標準安裝的中州韻引擎有粵拼方案，但是下載之後發現無法使用/切換到粵拼，求助。
同時安裝時沒有設置安裝路徑的選項，希望開發者添加這一功能。

**Comment by osfans** [comment]
這個是rime的問題，可以去rime那邊詢問。基本上跟小狼毫一樣，放自己的schema和dict，然後修改default.yaml就好了。
