### ISSUE TITLE
酷倉無法在Acrobat Reader DC輸入中文

### ISSUE THREAD

**Issue by tinynose** [EasyIME/PIME#314]
只可以在Acrobat DC切換為酷倉，但不能切換為中文輸入，只能打英文。

**Comment by InSb** [comment]
切換到其他輸入法再切換回酷倉，這樣會不會好。
候選窗口是否不跟隨？用 Photoshop CC 2017.0 測試會不跟隨。

**Comment by tinynose** [comment]
不會。狀態列顯示倉，情型就像酷倉切轉為英數輸入，但就再也切換不回中文輸入。

現在解決辦法是在記事本打中文，再貼到Reader DC裡面。

**Comment by KenLuoTW** [comment]
參考 #139
