### ISSUE TITLE
無法設定符號、每列顯示候選字個數

### ISSUE THREAD

**Issue by usert109** [EasyIME/PIME#315]
https://images.plurk.com/5kISxKgXnJWWuu63kAZM.jpg  https://images.plurk.com/2acWkNWamcaq00e5kAZM.jpg  https://images.plurk.com/7pgAkGWyh9TWTizJkAZM.jpg 

如圖，設定好之後，沒有改動。
不論我怎麼重新安裝，都無法改掉上次的設定

另外，「麼」無法用「ㄇㄛ˙」輸入

**Comment by KenLuoTW** [comment]
設定無法套用問題請參考 #144 。
「麼」的注音問題請參考 #301 。
