### ISSUE TITLE
請問一下中州韻的倉頡詞庫在哪邊可以增加？

### ISSUE THREAD

**Issue by jfhsu** [EasyIME/PIME#316]
個人用起來覺得蠻方便的，
連打的時候不用按space可以一直一打中文
但有時候發現打太長反而有些詞不對了，
想請教一下在哪邊，我可以自己增加？

**Comment by jfhsu** [comment]
剛剛自己發現了詞庫定義在 cangjie5.userdb.txt,
不過還是不太明白怎麼定義詞庫
舉裡面的例子
-》encaamro 	時間可以	c=0 d=0.1 t=2214
想請教一下 c, d , t 各代表的意義？

**Comment by osfans** [comment]
https://github.com/rime/rime-cangjie
修改這裏面的dict.yaml，改完要登出後再登入。

再有問題可以去rime/home討論。

**Comment by osfans** [comment]
https://github.com/rime/home/issues
