### ISSUE TITLE
輸入法失效的問題還在

### ISSUE THREAD

**Issue by seantw** [EasyIME/PIME#319]
打什麼都出現英文字母，很常發生! 我是 Windows 10 下使用的。是 python 的問題嗎? python 這部份有沒有可能用其他的程式語言來改寫? 哪裡可以找到開發支援 PIME 輸入法的文件?

**Comment by KenLuoTW** [comment]
我本身注音打很爛,所以很少用新酷音模組。今天我稍微測了一下,感覺應該是一些輸入法狀態沒有正確送給 libchewing 的關係,Python 基本還正常在運作。

例如 Ctrl + 空白鍵 (鍵盤開關),在別的輸入法中關閉鍵盤後,再切換到以下輸入法的狀況:
cinbased  系列輸入法: 沒有正確顯示鍵盤狀態,但再按一次 Ctrl + 空白鍵,即可正常輸入。
新酷音模組: 沒有正確顯示鍵盤狀態,再按一次 Ctrl + 空白鍵,變成按什麼鍵都無法輸入。

所以以此類推,應該是有別的輸入法狀態沒有正確送給 libchewing,所以導致只能輸入英文。
或許在 onDeactivate 時,把 libchewing 給釋放掉,能夠減少一點問題。

**Comment by osfans** [comment]
目前cinbase很穩定？

**Comment by SharerMax** [comment]
RIME 输入法也有时会失效

**Comment by KenLuoTW** [comment]
@osfans 是的,自 0.16.1 正式版使用至今,沒有碰過打一打會突然只能打英文,或無法輸入的問題。

**Comment by seantw** [comment]
我平常是使用倉頡, 遇到不會打的字就換注音, 會不會是因為這樣經常切換所以造成輸入法失效的問題?

**Comment by KenLuoTW** [comment]
@seantw 前天的狀況,我要重現卻重現不出來,新酷音也是沒有正確顯示鍵盤狀態而已,按按一次 Ctrl + 空白鍵,即可正常輸入。

PIME 及 Python 這邊應該是沒有失效,因為當我新酷音發生問題時,我切到至其它 PIME 下的輸入法,依然可以正常輸入。

問題很可能就是切換輸入法所照成的偶發性事件,因為 @PCMan  有用過 [TOOL](https://github.com/EasyIME/PIME/tree/master/tests) 測過,裡頭沒有測試到的就是輸入法切換的測試。

我會去看看這部份有沒有辦法改善,到時要麻煩您測試一下。

**Comment by SharerMax** [comment]
RIME 强制关闭Python后等待重新运行Python后恢复

**Comment by seantw** [comment]
@KenLuoTW 不知 @PCMan  的測試工具有沒有測試開不同的應用程式然後輸入。我通常是在新應用程式一開始就遇到。

**Comment by code-moritz** [comment]
同样存在这样问题，在RIME时，使PIME时间一长。必然出现无法输人中文的问题，需要重新启动电脑问题才可以解决。

请尽快fixed掉。

**Comment by osfans** [comment]
@code-moritz 
嗯，已知問題。强制关闭Python后等待重新运行Python后恢复。

**Comment by code-moritz** [comment]
是在task manager中关闭python进程？

重新运行是系统会重动重新运行吗？

我试过，好像系统会卡死。

**Comment by PCMan** [comment]
請問這個問題在 1.0.0rc 版本還有嗎？

**Comment by kmchub** [comment]
1.0.0 rc1 , rc1.1 , rc1.2 所有輸入法都只能出現英文字母
0.16.1 和最新的 rc1.3 則是可以正常使用輸入法
感謝 PCMan , 辛苦了

**Comment by PCMan** [comment]
請統一在 https://github.com/EasyIME/PIME/issues/131 回報
