### ISSUE TITLE
Windows10 64bit [版本 10.0.14393] ，Sandboxie 64bit [版本 5.1.6]，PIME失效。

### ISSUE THREAD

**Issue by GoGoogle** [EasyIME/PIME#322]
Windows10 64bit [版本 10.0.14393] ，Sandboxie 64bit [版本 5.16]，PIME v0.16.1 失效。

在Sendboxie的程序中无法打出中文，连PIME的设置菜单都点不出来。
但微软自带的五笔是可以的。

希望能修复！

**Comment by PCMan** [comment]
這不是 bug
sanboxie 禁止裡面的程式對外連線，所以 PIME client/server 架構被禁止使用
所以本輸入法無法相容 sandboxie

**Comment by l1000x** [comment]
win7下测试在Sandboxie中运行PIME，就可以正常使用了。
