### ISSUE TITLE
Windows 10 64位元 專業版 無法使用 PIME輸入中文應用程式清單.隨時更新....

### ISSUE THREAD

**Issue by JYken** [EasyIME/PIME#324]
20170412/Adobe Acrobat Reader DC
20170412/WPS Office 2016

**Comment by PCMan** [comment]
Adobe Reader 可以到設定當中找到「安全性/沙盒」關閉「受保護模式」即可

**Comment by PCMan** [comment]
Duplicate: https://github.com/EasyIME/PIME/issues/139
從設定關閉 Adobe Reader 保護模式即可。
相關的 registry
[HKEY_CURRENT_USER\SOFTWARE\Adobe\Acrobat Reader\10.0\Privileged]
"bProtectedMode"=dword:00000000

@KenLuoTW 你覺得我們有需要在安裝程式也提供關閉 Adobe Reader 保護模式嗎? 跟 IE 同一頁

**Comment by KenLuoTW** [comment]
Adobe Reader 並非每個人都會用到,且也不是作業系統所內建的軟體,故以後在 WIKI 註明即可。

**Comment by Yunzj** [comment]
可以搞个安装前判断，[HKEY_CURRENT_USER\SOFTWARE\Adobe\Acrobat Reader\10.0\Privileged]
"bProtectedMode"值是否存，存再就改成0 @PCMan

**Comment by 3togo** [comment]
still not working
20180528/WPS Office 2016

**Comment by PCMan** [comment]
1.3 版已經修復，現在 adobe 可以用了
