### ISSUE TITLE
請問小鶴雙拼如何輸出臺灣正體？

### ISSUE THREAD

**Issue by as255287** [EasyIME/PIME#327]
請問使用小鶴雙拼如何輸出臺灣正體？
目前使用的輸出爲繁體沒錯，但是並不是臺灣正體。
例如： 
爲 為 
着 著
裏 裡
羣 群

**Comment by craze429** [comment]
參考Rime設定：http://zqpythonic.qiniucdn.com/data/20130326120851/index.html

1. 在用戶資料夾（%APPDATA%\PIME\Rime）下新增設定檔：double_pinyin_flypy.custom.yaml（utf-8, 無bom），設定檔內容：
```
# double_pinyin_flypy.custom.yaml
#
# 於重新部署後生效
#

patch:
  "simplifier/opencc_config": t2tw.json
  "simplifier/option_name": zh_tw
  "switches/@2/name": zh_tw
  "switches/@2/states": [ 繁體, 台灣正體 ]
````

2. 存檔後，重新部署

**Comment by as255287** [comment]
謝謝。

**Comment by zzz67240** [comment]
FYI，包含臺灣正體及簡體中文。
https://gist.github.com/zzz67240/fa920d255d56b9fa310e4f0864e22a29

**Comment by imper0502** [comment]
這是我的設定檔，除了輸出正體外，還增加了注音的外觀。
yin 除了可以打 YB 之外，打 YF 也可以。（符合注音的習慣）
ying 除了可以打 YK 之外，打 YG 也可以。（符合注音的習慣）
https://gist.github.com/imper0502/ff63da3b8d006ef9646ed7f74a1204cc
