### ISSUE TITLE
中洲韻更改color scheme 的功能可以用嗎？

### ISSUE THREAD

**Issue by jfhsu** [EasyIME/PIME#329]
我試了改了 pime.yaml ,
改 font_face, font_point 都可以看到改變...
但改 color_scheme ， 將底下preset的拿上來套用， 顏色都不會變..
請問一下會下是目前還未之援還是我的方法有錯..?

**Comment by osfans** [comment]
暫未完成，所以沒有合併過來。

**Comment by jfhsu** [comment]
了解， 感謝你辛苦的porting, 這真是一個很好用的輸入法 ，雖然我只用倉頡而已
