### ISSUE TITLE
新酷音使用嘸蝦米表格提供一個建議

### ISSUE THREAD

**Issue by bluesxblues** [EasyIME/PIME#33]
在過去cin輸入法使用嘸蝦米表格跟官方版最大的不同就是

轉換 多國語言輸入 的方式

在官方版中可以輸入「，，ＣＴ空白鍵」來切換「打繁出簡模式」，

「日本漢字」輸入「，，Ｊ空白鍵」來切換

使用方式詳見官方說明

https://boshiamy.com/tutorial_function.php?page=3

另提供表格對應表

liu-uni.tab: 繁體中文參考檔,,T
liu-uni2.tab: 簡體中文參考檔,,C
liu-uni3.tab: 打繁出簡參考檔,,CT
liu-uni4.tab: 日文參考檔,,J

如果有可能實現的話希望能納入這個功能

謝謝

**Comment by fygul** [comment]
基本上這種作法也有點像切換到不同的輸入法
只不過切換的都是同屬嘸蝦米的不同碼表，而這些碼表分屬正/簡體中文、日文漢字

自己不曾使用PIME，但個人猜想，PIME也許會朝成為「輸入法平台」的方向發展
可以讓使用者自行掛上自己想用的輸入法，那麼就沒必要去完全摩仿某種輸入法的作法，就走自己的路吧!

@bluesxblues 
http://www.black-show.com.tw/fygul/blog/yong_tw-20151207/
供參考，使用小小輸入法平台
內建繁簡切換功能，所以沒有額外提供單獨的簡體字碼表
有「快無」、「特無」之別的不同碼表
Ctrl + 字母區上數字鍵可切換不同輸入法，雖然這方式有時會當掉，故不建議。切換的設置是可改的

**Comment by PCMan** [comment]
@timtan 這些資訊看起來滿有用的

**Comment by KenLuoTW** [comment]
實現不難,問題在於嘸蝦米的授權問題,所以暫時不會加入嘸蝦米的輸入法。

不過我到時會另外弄一個蝦米模組的安裝程式,
只要你有合法的嘸蝦米 CIN 表格,將可以簡單地將它套用進來使用。

**Comment by dasu88** [comment]
請問這個蝦米模助，有後續進度嗎？
