### ISSUE TITLE
PIME 1.0.0-rc1：Win8.1下無法在Notepad，Chrome中使用

### ISSUE THREAD

**Issue by marcoseaver** [EasyIME/PIME#330]
昨晚也是無意中看了一下，發現PIME1.0.0-rc1，馬上下來試了一下。安裝沒有問題，但是不管怎麼Reboot系統，都無法在Notepad中使用中文輸入。Office中則沒有問題。

**Comment by ottokang** [comment]
測試了一下，安裝在64位元 Windows 7，只有啟動 Debug console 的畫面可以啟動PIME，其他的應用程式都不行，也沒辦法用Debug console，應該是64位元的檔案沒安裝到？

@PCMan

**Comment by marcoseaver** [comment]
我使用的Chrome是64位元的軟體，也不能啓用PIME哦。

**Comment by marcoseaver** [comment]
好像真和32位元或64位元有關哦。我的Office是32Bit的，而windows是64Bit的。

**Comment by HPEACE** [comment]
跟樓上相反，在Windows 7 64bit上，用SysWOW64裡的notepad可以輸入，而預設位置裡的notepad無法輸入

**Comment by mitch0118** [comment]
這次更新，我是W7遇到msvcp140.dll 遺失，要安裝vc++ 2015，X86、X64兩種版本，安裝完後就好了。之前的PIME不用特別安裝

**Comment by HPEACE** [comment]
@mitch0118   在Test20時有遇到這問題，要手動安裝 Visual C++ 2015 Redistributable x86版本
為什麼會發生這狀況，當時KenLuoTW是這麼說的

> 我目前的電腦都沒有裝 Visual Studio,故 Test19 之後是使用 AppVeyor 生成的檔案,所以產生上述問題。

**Comment by PCMan** [comment]
https://github.com/EasyIME/PIME/releases
PIME 1.0.0-rc1.1 緊急修正釋出，修正 Windows 7 64-bit 下無法使用的問題，昨日有下載 rc1 的朋友請更新。
問題成因是上次建立執行檔的時候，VC++ 一個參數意外調錯，導致出來的程式需要 VC++ 2015 runtime 才能正確運作 (vc140*.dll)，而 Windows 7 沒有內建這個 dll 檔。

**Comment by PCMan** [comment]
已經修復
