### ISSUE TITLE
PIME 1.0.0-rc1：2012-r2下新酷音,設定預設以停用輸入法模式啟動,輸入法列顯示是相反的

### ISSUE THREAD

**Issue by xgtcarter** [EasyIME/PIME#331]
亦即停用時是顯示"ㄅ",啟用時沒有顯示"ㄅ"
而且每次在修改完設定後,有很大的機會整個視窗無回應當掉

**Comment by PCMan** [comment]
無法重現，不過我會找時間檢查

**Comment by xgtcarter** [comment]
測試方法:在Hyper-V環境中安裝完2012r2後,立即安裝pime RC1.3,安裝時只有選擇新酷音,
並將控制台->語言的部份只保留新酷音,其他的輸入法皆移除,新酷音設定預設以停用輸入法模式啟動,
重開機後,開啟記事本開始輸入文字測試!
經測試發現,如果將"控制台->語言->進階設定->切換輸入法->在桌面語言列可用時使用它"打勾,
才會出現相反問題,不打勾看不到浮動語言列當然就沒有此問題

**Comment by PCMan** [comment]
fixed.
