### ISSUE TITLE
常用詞語選單

### ISSUE THREAD

**Issue by abc0922001** [EasyIME/PIME#333]
有沒有像新自然輸入法那樣有文字範本

就是我呼叫常用詞語選單就會有我設定好的詞語，直接輸入

像 
1. 感謝 >>感謝大大無私分享
2. email >> abc09@hotmail.com

這樣，就可以方便輸入，不用每次都打一大串。

**Comment by PCMan** [comment]
沒有，但是有類似功能，新酷音設定打開在簡易符號輸入有類似的部份支援。
