### ISSUE TITLE
「麼」打不出來

### ISSUE THREAD

**Issue by abc0922001** [EasyIME/PIME#334]
打ㄇㄛ˙ 它都不給我打

windows10 64bit  1703板

PIME版本是PIME 1.0.0-rc1.1 (release candidate 測試版本)

**Comment by hiunnhue** [comment]
因為沒有 ㄇㄛ˙ 這個音，只有……

* ˙ㄇㄜ ：什麼、怎麼、那麼、這麼

* ㄇㄚˊ：幹麼（=幹麻）

* ˙ㄇㄚ： = 嗎

請參見：https://www.moedict.tw/%E9%BA%BC

**Comment by abc0922001** [comment]
@hiunnhue 原來是這樣的阿，一直以來都是用其他輸入法打ㄇㄛ˙
這個沒辦法加進去新酷注音裡嗎

**Comment by HongJheLi** [comment]
@abc0922001 我在想你是不是誤以為 `ㄇㄛ˙＝＝ ㄇㄜ˙`？

直接打 `ㄇㄜ˙` 是可以打出字來的。

真的沒有 `ㄇㄛ˙` 這個字說。

**Comment by abc0922001** [comment]
@HongJheLi  我是一直以為「麼」的注音是`ㄇㄛ˙`一直以來從微軟注音到新自然都是打`ㄇㄛ˙`，所以才沒發現其實是`ㄇㄜ˙`
