### ISSUE TITLE
Skype(Win10)黑色佈景主題，新酷音打字不會顯示文字 (Windows 10 1703 - 1.0.0-rc1.2)

### ISSUE THREAD

**Issue by Wolfrisger** [EasyIME/PIME#335]
使用Windows 10內建的Skype (先前的Skype Preview)，若切換到暗色佈景主題，新酷音打字時會完全看不到字，推測是文字是黑色的，背景也是黑色的緣故。

**Comment by PCMan** [comment]
confirmed

**Comment by PCMan** [comment]
@osfans 你在 rime 那邊有做自訂顏色？
有的話可以 merge 回來嗎？對這個可能有幫助？

**Comment by osfans** [comment]
還有些問題，等完善後再merge。看看能不能解決此問題。
https://github.com/osfans/PRIME/blob/rime/python/input_methods/rime/data/PIME.yaml#L36

細項比較多，最好有一個統一的設定方式。

**Comment by oblin** [comment]
測試過 1.1.0 版本已經沒有這個問題，應該可以關閉了。

**Comment by Wolfrisger** [comment]
我這邊測1.1.0問題還在呢

**Comment by PCMan** [comment]
這個在 1.3 版應該是修好了，我先關掉，如果還是有請再 re-open
