### ISSUE TITLE
中文模式下按住Shift輸入全形標點符號選項失效

### ISSUE THREAD

**Issue by nereis-nereus** [EasyIME/PIME#340]
PIME 輸入法平台版本：1.0.0-rc1.2

僅勾選「中文模式下按住Shift輸入大寫英文字母」／「中文模式下按住Shift輸入全形標點符號」未勾選狀態下，中文輸入模式下按住Shift鍵仍會生出符號如【】「」“”≠≒而非asdfghjk。

**Comment by ottokang** [comment]
是不是勾選了〔簡易符號輸入〕 -> 〔中文模式下按住Shift快速輸入符號〕？

**Comment by wellsteven** [comment]
我也一樣有這問題 不論怎麼改勾選  都是一樣輸入符號如【】「」  按住SHIFT無法正常輸入英文 不論大小寫都無法  WIN7 專業版 64bit
