### ISSUE TITLE
PIME 1.0.0-rc1.3 颜色皮肤无效

### ISSUE THREAD

**Issue by fxliang** [EasyIME/PIME#345]
之前的0.16.1的颜色皮肤都是可以的，这个版本就不行了....

**Comment by osfans** [comment]
這個一直不行的，還沒有做完。你之前用的是prime吧？

**Comment by fxliang** [comment]
@osfans 是的，这个不是可以合并上来的么？我只用rime部分

**Comment by osfans** [comment]
還不行，可能會造成不穩定。暫時就留在prime那邊。
