### ISSUE TITLE
osfan 的 PRIME 分支了 EasyIME 的 PIME 然后改名称骗捐款

### ISSUE THREAD

**Issue by cyrilkong** [EasyIME/PIME#347]
osfan 的 "PRIME" fork 了 EasyIME 的 PIME 然后改 source 里面的名称骗大家捐款赞助，请关注一下

**Comment by osfans** [comment]
噢，知道了，大家可以繼續用純淨的pime，因爲rime的部分我已經提交過來了。

偶爾也可以用用prime，算是rime的深度定製版，用得爽就自願捐款。

**Comment by osfans** [comment]
其實不是爲了改名字而改名字，只是因爲要跟PIME原版區別。
覺得prime不妥的話，就改成pime-rime定製版吧，名字長了點。

**Comment by PCMan** [comment]
@cyrilkong 自由軟體的精神就是歡迎改作，只要遵照原 LGPL 授權有放出 source code，這並沒有違反授權合約，衍生著作收捐款或是改名都是可以的。
