### ISSUE TITLE
1.0.0-rc1 酷倉模組：「萬用字元查詢」設為星號時，輸入兩次星號後宕掉

### ISSUE THREAD

**Issue by InSb** [EasyIME/PIME#348]
「萬用字元查詢」設為星號時，輸入兩次星號後，PIME Debug Console 顯示如下：
`
ERROR: ord() expected a character, but string of length 2 found 7e8f2b09-3d38-4483-973c-a4fdde1598cc|{"charCode":42,"isExtended":false,"keyCode":56,"keyStates":[0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,128,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,128,0,0,0,0,0,0,0,0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,128,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0],"method":"onKeyDown","repeatCount":1,"scanCode":0,"seqNum":529}
`
所在窗口假死，之後須 kill 掉 python.exe 進程。

**Comment by InSb** [comment]
在用1.00-rc2的酷倉模組，雖仍可觸發上述 ERROR，但所在窗口不會假死。

**Comment by KenLuoTW** [comment]
已修正。
