### ISSUE TITLE
PIME 1.0.0-rc2：2012-r2在VC++2010 Express一輸入就發生問題必須關閉

### ISSUE THREAD

**Issue by xgtcarter** [EasyIME/PIME#351]
測試方式:在Hyper-V環境中安裝完2012r2後,立即安裝pime RC2.0,安裝時只有選擇新酷音,並將系統其它輸入法刪除只保留新酷音,然後安裝VC++2010 Express,安裝時可選組件皆不選,完成後執行VC++輸入任一字元即顯示發生問題必須關閉.此問題在RC1.3時並無發生.

**Comment by PCMan** [comment]
我這裡無法重現那個環境來測試
有興趣編譯一份 debug build 幫除錯看看嗎?
git clone 出來之後
git submodule update --init
然後照 README 裡面寫的用 cmake 生出 VC++ 專案檔，就可以編譯了

**Comment by HolyWu** [comment]
Visual Studio 2017 Community encounters the same crash problem after installing PIME 1.0.0-rc2. It doesn't occur in rc1.2 or rc1.3 (can't remember which one I installed last time).

**Comment by PCMan** [comment]
真怪，我這邊 VS 2015 很正常，找時間再檢查一次好了

**Comment by PCMan** [comment]
Fixed in git.
