### ISSUE TITLE
使用新酷音 1.0.0 rc2 會搞當V.S.

### ISSUE THREAD

**Issue by cs-pchsu** [EasyIME/PIME#354]
剛剛發現使用新酷音 1.0.0 rc2 會搞當
visual studio 2015 或 2017，
只要一按ctrl或shift就會馬上當機。

但上述的情況只發生在系統只安裝新酷音。
如果再裝個微軟的新注音就不會了。

**Comment by PCMan** [comment]
duplicated with #351
