### ISSUE TITLE
win10 RS2 新酷音 RC2無法使用

### ISSUE THREAD

**Issue by noddio** [EasyIME/PIME#356]
剛下載RC2在兩台都剛升級到RS2的win10測試使用
一台可以安裝, 另外一台安裝後 右下方不會出現新酷音, 就是說無法切換使用
但是在控制台裡面卻有出現新酷音, 另外按設定也會當機閃退 

另外一台可以正常切換, 但有時候卻發生不能打字也無法切換中英文

**Comment by PCMan** [comment]
@noddio 可以幫試一下最新的 RC3 嗎？我覺得應該已經修好了 Thanks

**Comment by noddio** [comment]
其實我發現那個應該不會是你的問題, 因為我換個使用者就可以用了
我後來乾脆那台的win10整個重置了, 就都可以正常安裝
現在就只剩下穩定的問題, 是否在某些程式上會不會造成當機的問題
如果有不穩定的狀況我再來回報, 太爽了 新酷音!!
