### ISSUE TITLE
PIME 1.0.0-rc2 易导致CAD，WORD等

### ISSUE THREAD

**Issue by Yunzj** [EasyIME/PIME#357]
比如开机时，默认切到pime，打开CAD时，有然后打开一个图纸，在cad里输入命令，cad有一定几率致命错误。。旺旺也会。用的是五笔拼音方案

**Comment by junsinpon** [comment]
+1
目前使用WORD、EXCEL和COREL DRAW也都會發生上述註況。
退回使用rc1.3後正常。

**Comment by weison620** [comment]
+1 使用 XSHELL　也會導致　CRASH

**Comment by PCMan** [comment]
昨天剛放 RC3 可以幫測試一下是否還會嗎？
Thanks

**Comment by weison620** [comment]
@PCMan 你好 目前測試XSHELL 已無此問題 感謝！
@junsinpon 看到你的問題我也順便測試了一下OFFICE2016， WORD跟EXCEL 目前已也都無遇到問題

**Comment by Yunzj** [comment]
经过测试最新版，已经没有这个问题。。怎么删除帖子？
