### ISSUE TITLE
PIME v1.0.0 出現防毒軟體報錯

### ISSUE THREAD

**Issue by mifire** [EasyIME/PIME#362]
Pime 1.0.0 正式板下載後 會被防毒軟體 小紅傘報錯
https://images.plurk.com/7dwjNEcnU9upem1sjHfz.jpg
如上圖

**Comment by PCMan** [comment]
可以幫回報給廠商嗎？
請參考這裡 https://github.com/EasyIME/forum/issues/13#issuecomment-262121352
這算 avast 的 bug

**Comment by oblin** [comment]
使用 windows defender，會出現木馬： Trojan: Win32/Fuery.B!cl

https://1drv.ms/i/s!Aq58LdBZ0cQflaZR802UIFSkbESQPQ

**Comment by PCMan** [comment]
Windows defender & Avira 都回報給廠商排除了
更新病毒碼應該就好了

**Comment by oblin** [comment]
謝謝，windows defender 也不會報錯，已經測試過可以正常使用了。

**Comment by PCMan** [comment]
Fixed in 1.3.0 beta:
https://github.com/EasyIME/PIME/releases/tag/v1.3.0-beta
