### ISSUE TITLE
1.0 用了後...感覺有個問題

### ISSUE THREAD

**Issue by HPEACE** [EasyIME/PIME#364]
我用大易，以前的cin碼表，我有依打字習慣排過順序，但轉成json後，它好像會依筆劃順序排
導致我原本的順序又没了，不知道何時能導入自動學習的功能了？

**Comment by HPEACE** [comment]
看了一下cin2json的程式碼，應該是有依常用字、次常用字....的排序點式，可是實際上排出來怎麼不太一樣
比如說我打大易碼「at」出來的會是
0. 仦 
'.  尒
[. 你

**Comment by HPEACE** [comment]
自從po了這問題後一直在思考這問題，愈想愈覺得這對打大易的我來說好像不是問題
因為打大易是一個字一個字打，讓系統自動選字或是所謂的智能輸入，反而變得不好用
打更慢，所以...請忽略掉我提的這個問題吧

**Comment by kmchub** [comment]
我也是用大易的, 雖然說大易的選字機率很低, 但如果有自動選字, 一定會更好, 幾乎可以盲打.
目前使用上算滿意, 但同樣是選字問題, 常用字有時都排在後面, 如果有詞庫的輔助, 或用統計來排序, 應該會更好

**Comment by HPEACE** [comment]
@kmchub 你可以試試，選用「優先以聯想字詞排序候選清單」「聯想字詞」，看能否達到你要的效果

**Comment by HPEACE** [comment]
其實，「優先以聯想字詞排序候選清單」「聯想字詞」二者都有勾選時變得超難用，但是我說不上來怎麼難用法，但若是只勾「優先以聯想字詞排序候選清單」不勾「聯想字詞」時則還蠻不錯用，唯選字順序會有點小聰明，常會按錯，而不勾「優先以聯想字詞排序候選清單」則會完全照碼表內的順序，要符合個人用我都只好去人工調碼表內的順序

**Comment by KenLuoTW** [comment]
@HPEACE 你可以參考 #346 ,將你的 CIN 轉成 JSON,這樣就可沿用你原本的順序。

自動學習短時間不會加入,且也對重碼字少的輸入法無用,反而有害。
可以照 @HPEACE 所說,將自己常打的重碼字加入聯想字詞,只記一些常用的,比較不會搞混。

「中文模式下輸出字串後顯示聯想字詞」我也是建議不要核取,這選項只因微軟有而加入。
在 PIME 中,並沒有像微軟輸入法一樣會提示該候選為聯想字,並要按下 SHIFT 鍵選字。
整個候選清單又跟一般候選清單一樣,故使用起來容易混淆。

**Comment by kmchub** [comment]
「聯想字詞」我也覺得不好用, 
因為用大易都一字一字接著打, 突然有詞要選, 反而要想一下, 反而慢了
我理想中的詞庫是打第二個字時幫忙選字, 而不是打第一個字時提示第二個字或詞來讓我選
加上聯想字詞還要自己建那個格式的詞庫, 有點麻煩
新酷音 的那種學習方式, 如果也能拿來大易用, 應該也可以減少選字
能夠自動選字, 就沒有碼表的順序問題 .... 
純個人習慣..

**Comment by HPEACE** [comment]
@KenLuoTW cin to json 我轉了，但實際上不是照我cin裡的自訂順序，我看了cintojson的程式碼，如果没有理解錯的話，它應該是照常用字、次常用字...重新排序，但不會參考原cin裡的順序

**Comment by KenLuoTW** [comment]
如果沒有加參數的話,是不會去排序的,而是照原碼表順序。

**Comment by HPEACE** [comment]
不理解排序參數為何，當初是這樣下的指令
python.exe .\cinbase\tools\cintojson.py D:\Dayi\Dayi-modified.cin

**Comment by KenLuoTW** [comment]
這樣就沒有排序了,請確認拿來轉的檔案是修改過的。
並且拷貝至 JSON 資料夾後,須更換碼表,才會重新載入至記憶體。

**Comment by HPEACE** [comment]
那請問要排序的參數是怎麼下，可能是我眼睛業障重，往前篇參考只找到上述那樣的指令
轉完當然是改成dayi3.json到json資料夾內並重新啟動PimeLauncher

**Comment by KenLuoTW** [comment]
@HPEACE 這轉換工具沒有問題,如果排序有問題的話,大新倉頡的用戶會先提出來。
@kmchub 常用字會排在後面,就是沒有去排序,一切都照原碼表所定義的順序。
