### ISSUE TITLE
關於在其他介面開發此輸入法

### ISSUE THREAD

**Issue by q120144178** [EasyIME/PIME#369]
我知道目前此輸入法僅在windows中可用，
想問開發者們未來有考慮移植到android or ios嗎？

**Comment by acacool** [comment]
安卓上有同文输入法了

**Comment by osfans** [comment]
嗯，rime模組的話，android上有同文輸入法。

**Comment by q120144178** [comment]
殘念 哈哈 我用的是iphone

**Comment by PCMan** [comment]
目前無此計畫

**Comment by lyenliang** [comment]
我今天查看[同文輸入法的 Github 頁面](https://github.com/osfans/trime/blob/develop/README_sc.md)，發現它的[穩定版](https://play.google.com/store/apps/details?id=com.osfans.trime)已從 Google Play 上消失了，請問有人知道是什麼原因嗎？
