### ISSUE TITLE
pime会让svchost占用cpu异常升高

### ISSUE THREAD

**Issue by yMartyr** [EasyIME/PIME#377]
win10 64位：
pime会让我这台机器上的svchost进程持续占用很高的cpu。起初都还好，而当我把系统默认的输入法换成pime，cpu就占用不正常。
而在我没有安装pime时，怎么切换默认输入法都没有这个问题。
所以我想问下着怎么解决。
谢谢了

**Comment by styyu1281** [comment]
試試重新啟動過後有沒有恢復正常。
我的狀況是剛安裝好會有svchost持續高佔用CPU的這種問題，但是重新啟動後就在也沒有了。

**Comment by yMartyr** [comment]
@styyu1281 刚重启了，如果什么也不做还好。但只要访问PIME的配置文件，cpu的占有就立刻上来了。我查了一下，svchost是联网时，才会运行的一个进程。PIME不是离线的吗，怎么会无故导致svchost进程占用这么高呢？

**Comment by styyu1281** [comment]
與我的狀況不同，可能要等開發人員回覆了。

**Comment by yMartyr** [comment]
@styyu1281这样啊， 谢谢了！

**Comment by chrissilently** [comment]
這問題好像是win10造成的
之前試過只要有進入到 "控制台-語言-進階設定"
無論是用什麼方式進入"進階設定"
不論有沒有變更
 svchost 裡的task scheduler就會造成cpu異常佔用
