### ISSUE TITLE
送出文字前切換視窗 backspace 失效

### ISSUE THREAD

**Issue by float-tw** [EasyIME/PIME#38]
輸入任意文字，還沒選定送出時使用 alt + tab 切換到其他地方，在切換回來
這時候無法使用 backspace 刪除文字

**Comment by PCMan** [comment]
請問 v0.12 還有這問題嗎?

**Comment by float-tw** [comment]
v0.12 有相同問題

**Comment by PCMan** [comment]
win7 下最新版本無法重現

**Comment by float-tw** [comment]
更新到 0.13 還是可以重現
複製步驟
1. 打開 chrome 在 url 列輸入"測試"
2. 在還沒按下 enter 文字底下還有底線時切換視窗再切回 chrome
3. 這時底線已經消失，按 backspace 無反應

抱歉手邊電腦不適合錄影，無法錄下 issue 的現象

**Comment by PCMan** [comment]
ok, confirmed!
