### ISSUE TITLE
资源管理器崩溃的问题

### ISSUE THREAD

**Issue by yMartyr** [EasyIME/PIME#380]
win10 64位
右键小图标，打开用户文件夹以后。再右键小图标，打开用户文件夹，会导致资源管理器崩溃。

**Comment by DesmondSylin** [comment]
我也蠻常遇到在軟體進行打開文件時，只要新建目錄而導致新酷音輸入啟動，就會造成打開文件這個功能崩潰，無奈這是不定期（但蠻常）發生的狀況，很難重現。
Win10 64位元
