### ISSUE TITLE
正式版本是否能編輯字根檔？

### ISSUE THREAD

**Issue by callinner** [EasyIME/PIME#381]
使用輸入法為自然大新，但內建的自然大新有許多的注音文及表情符號，用不到又佔輸入時選字的空間，
之前的版本有cin檔可以編輯，可以自行將不需要的字根直接刪除，
但是正式版的架構修改了，找不到cin檔可以編輯，
正式版本是否已無法自行修改字根檔了？

**Comment by InSb** [comment]
可以編輯 json 檔。

**Comment by callinner** [comment]
能否指導一下，我使用EmEditor編輯位於「C:\Program Files (x86)\PIME\python\cinbase\json」下的json檔，
但是編輯完登出再登入後，python程序會當掉 ，無法使用輸入法。

舉例來說：
        _"hqi": [
            "我",
            "牫",
            "ㄛㄞㄋ",
            "偶love泥",
            "^3^",
            "我愛你"
        ],_

修改成
        _"hqi": [
            "我",
            "牫",
        ],_

存檔後就會當掉，是哪裡有做錯嗎？

**Comment by InSb** [comment]
@callinner 修改後的最後一字後面有一個逗號。雖然不敢確定，還是去掉為好。

**Comment by callinner** [comment]
的確是逗號的問題，逗號刪掉就可以了，感謝回答！
