### ISSUE TITLE
請問1.0版後打字空白鍵跳候選是新設定嗎?

### ISSUE THREAD

**Issue by Tokenyet** [EasyIME/PIME#382]
我是原0.16.1版的使用者，
換到1.0版最不能適應的是，當打一連串字數想按空白的時候，跳的是候選視窗。
嘗試過1.0.0跟1.1.0版的行為模式是一樣的，所以想請問一下是新的設定嗎?

**Comment by DesmondSylin** [comment]
這部份可以在輸入法設定裡面可以改

**Comment by Tokenyet** [comment]
謝謝 原來裡面有 當時眼殘沒看到
