### ISSUE TITLE
Firefox 左右選字錯誤

### ISSUE THREAD

**Issue by suwilltw** [EasyIME/PIME#39]
有發現使用Firefox 45版，如果新酷音選字按下方向鍵就會跳掉，
無法輸入（畫面卡在那邊），但切換新注音又切換回來就正確，
但是Google Chrome正常。

**Comment by PCMan** [comment]
請問 v0.12 還有這問題嗎?

**Comment by suwilltw** [comment]
回報  還是有這個問題
選字按下就會卡住

**Comment by PCMan** [comment]
windows 7 + firefox 47 + 目前 git 版本無法重現此 bug
