### ISSUE TITLE
『什麼』注音打不出來？

### ISSUE THREAD

**Issue by kaihsing** [EasyIME/PIME#41]
得打ㄕㄜˊ ㄇㄚ˙才出得來

**Comment by jessy1092** [comment]
`ㄕㄜˊ ˙ㄇㄜ`  也可以吧?

教育部字典是兩個讀音: `ㄕㄣˊ　˙ㄇㄜ`　（又音）`ㄕㄜˊ　˙ㄇㄜ`
http://dict.revised.moe.edu.tw/cgi-bin/cbdic/gsweb.cgi?o=dcbdic&searchid=Z00000131338

**Comment by kaihsing** [comment]
喔，謝謝。
是我自己搞錯，「麼」˙ㄇㄜ打成 ˙ㄇㄛ˙

**Comment by dukelee** [comment]
那我也要說一個，垃圾（ㄌㄜ四聲，ㄙㄜ四聲），。另一發音（ㄌㄚ一聲，ㄐㄧ一聲）。之前好像GCIN還是自然可以打。
