### ISSUE TITLE
PIME 是否有 Error Log 輸出的方式

### ISSUE THREAD

**Issue by CC-Hsu** [EasyIME/PIME#413]
版本：1.1.0
OS：Windows 10
狀況：
使用新酷音輸入法打字，使用shift來回切換中文狀態 (狀態列顯示[中])
和輸入法關閉狀態 (狀態列顯示[A])。
有時候會發生狀態列卡在英文狀態(狀態列顯示[A])，此時會打不出字，只有使用 ctrl+space 切換成輸入法關閉狀態 (狀態列顯示[X]) 才能輸入一般英文字。

發生的重現步驟：不明，用到一半時突然發生

我知道這樣的描述不容易找錯誤
請問 PIME 是否有可供除錯的 Log 輸出
以便我在下次狀況發生時
快點把相關的 Log 段落找出來
以利我在這裡提供給開發者

最後，謝謝你們的貢獻
這真的是很方便的程式

**Comment by InSb** [comment]
有的，是`C:\Program Files (x86)\PIME\PIMEDebugConsole.exe`。
開啟之後再觸發 bug 試試看。

**Comment by CC-Hsu** [comment]
不好意思

請問可以導向文字檔嗎

例如類似 Linux 裡面的 2>&1

因為我也不確定問題哪個時候發生

因此想要讓他自己長 Log

出事的時候再快點拉出來

謝謝
