### ISSUE TITLE
無法在Acrobat reader DC 切換成中文

### ISSUE THREAD

**Issue by cs-pchsu** [EasyIME/PIME#418]
在Acrobat reader DC可以用ctrl + F把搜尋視窗叫出來。
但如果使用新酷音，這時候沒辦法切換成中文。但在其他程式視窗可以切換成中文。

**Comment by styyu1281** [comment]
PIME 1.1.0 on Windows 10 Home 1703 x64 Acrobat Reader DC 2017.012.20098 的ctrl + F搜尋視窗有相同問題，供開發者參考。

**Comment by InSb** [comment]
見 https://github.com/EasyIME/PIME/issues/139 。

**Comment by PCMan** [comment]
fixed in 1.3.
