### ISSUE TITLE
求救!!某一天開始轉換成新酷音按下第一個注音底下的"中"直接轉A 無法輸入任何字

### ISSUE THREAD

**Issue by zero11995** [EasyIME/PIME#429]
如題
http://imgur.com/a/qeEdV
這樣連英文都不能打 平常酷右邊那個字明明應該是中文的"中"或是"英"
結果按下一個鍵就變成有框框的A
然後就不能用了

重新下載安裝也會有一樣問題

**Comment by s81511** [comment]
這是目前的BUG 也是一直沒有修復的Bug 估計官方也不知道怎麼解決吧
有個暫時治標的方法 在這個問題出現的時候 按ctrl+alt+del 叫出工作管理員 在處理程序那一個介面裡
找到python.exe 把它結束 再重新切到新酷音 就會正常

**Comment by zero11995** [comment]
感謝提供意見
可惜這招對我不管用...
殺掉python.exe切回去新酷音直接還是在A的情況
這真的是我目前用到電腦最好的輸入法
但是有這麼常見這麼致命的BUG
真的是傻眼 感覺沒重灌前不能用了
重灌後也不能確定還會不會又出現問題

**Comment by oversky** [comment]
我目前是懷疑「使用 Shift 快速切換中英文」這功能有 bug，
按了一定次數後，輸入法狀態會整個亂掉。
還有 Shift+Space 切換全形半形可能也有類似的問題。
PIME 可能要寫個 debug 視窗顯示輸入法目前中英文全形半形狀態，
並和 windows 的輸入法狀態列一起看，
這樣可能比較容易找出問題。

我目前  Windows10 輸入法整套設定如下
1. windows 10 控制台的語言喜好設定不裝英文 (這一步可能不重要，還在觀察中)
https://i.imgur.com/9BA9j7I.png

2. 進階設定內覆寫預設輸入法選 PIME，
https://i.imgur.com/KQsMjA2.png
   我也沒勾選「讓我窗每個應用程式視窗設定不同的輸入法」(這一步可能不重要，還在觀察中)

前兩個設定讓 windows 10 以 PIME 為預設輸入法，
再搭配 PIME 自己的設定。

3. 預設以停用輸入法模式啟動 (Windows 8 以上適用)
    這設定讓 PIME 預設以英文輸入。
4. 不要使用 Shift 快速切換中英文，改用 ctrl+space。
https://i.imgur.com/gJol1Tu.png

5. 不要去按到 Shift+Space 切換全形半形。

**Comment by zero11995** [comment]
我個人是用Win7啦
感覺設定上很有差異...

**Comment by tree632** [comment]
那個方法我有效
另外我在想的是新酷音有許多切換功能都是用shift切換，或許也導致輸入法掛掉
所以要確認一下是不是有重複使用shift切換的功能
讓新酷音無法辨識他要做什麼樣的切換導致當掉

**Comment by zero11995** [comment]
沒想到issue還在
我來關一下
我以前好像是用1.1還1.0版 記得1.1用起來感覺問題比較多
我目前是win10 預設英文鍵盤 自動手動切新酷音中文 然後第一次這樣切換後就一直使用ctrl+space
遇到轉A問題工作管理員到詳細資料結束PIMELauncher.exe 手動重開

**Comment by alexpert237** [comment]
可以試試在工具列 圖示 找到pime launcher 滑鼠移至上方 右鍵 restart pime
