### ISSUE TITLE
有关候选字显示的问题

### ISSUE THREAD

**Issue by duoduoeeee** [EasyIME/PIME#448]
请问须如何设置才能让 rime 的候选输入窗像这样显示

![image](https://user-images.githubusercontent.com/14347369/32977370-0e492b42-cc67-11e7-9e5c-c08f560db7c4.png)

而不是这样显示

![image](https://user-images.githubusercontent.com/14347369/32977396-90ca5366-cc67-11e7-9383-fc3b02897703.png)

我的意思不是配色方案，是把输入的未上屏字符显示在编辑框里的方式

PIME.yaml 里貌似叫 `inline_preedit`

但是我把这里的参数都试过一遍了也不行

版本 1.1.0

**Comment by osfans** [comment]
暫時PIME和PRIME都還不支持小狼毫那種

**Comment by duoduoeeee** [comment]
我的妈耶
