### ISSUE TITLE
某些应用下无法呼出输入法

### ISSUE THREAD

**Issue by nameoverflow** [EasyIME/PIME#452]
PRIME release 1.1, windows 10 1709，已知包括 firefox 58.0b6，typora，cortana。

右下角角标正常：

![image](https://user-images.githubusercontent.com/10287709/33325972-a71f606e-d48e-11e7-81a3-c9b742134012.png)

但是在激活上述应用窗口后右键点击图标没有反应。

激活上述应用窗口后，做任何操作 PIMEDebugConsole.exe 中都没有输出。

在另外一些应用（如腾讯 TIM）下完全正常。

（包括这个issue也是从 TIM 中输入后贴过来的……）

杀掉 python 和 pime launcher 、或者重启注销后也一样。

**Comment by nameoverflow** [comment]
输入法使用的是rime……

**Comment by nameoverflow** [comment]
好了，发现问题是由于 [osfans/PRIME/releases](https://github.com/osfans/PRIME/releases) 中提供的 1.1.0 安装包安装后，PIME 文件夹中没有 x64 的 dll。之前所有有问题的应用都是 x64 应用。

自行 build 了一个之后正常了。

**Comment by osfans** [comment]
@nameoverflow  是這個原因？沒有x64？
