### ISSUE TITLE
請問現在還有支援自由大新倉頡嗎？

### ISSUE THREAD

**Issue by weichipedia** [EasyIME/PIME#464]
之前看舊版網頁的介紹有支援大新倉頡
但最新版本似乎沒有大新的模組？
請問還有支援大新倉頡嗎？

**Comment by mrhso** [comment]
![image](https://user-images.githubusercontent.com/13294467/34764957-044b3700-f62b-11e7-8afc-9fa3d37518fc.png)
支援的，併入酷倉模組了。
