### ISSUE TITLE
全形符號

### ISSUE THREAD

**Issue by Yayuki** [EasyIME/PIME#47]
鍵盤上＝「」這類符號中文下是全形 是否有辦法改成半形?

**Comment by ottokang** [comment]
這是新酷音的設定，中文模式下會預設成全形，把「按住 Shift 輸入全形標點符號」選項關掉，可以輸入+[]，但是={}這些就不行了

**Comment by alwayschoco** [comment]
您好： 

我有把那個選項關掉且在半形模式下，但還是出現＋「」而不是+[]
另外想請問，是否有需要改成在中文模式下也分全形半形而不是預設全形呢？

謝謝。

**Comment by PCMan** [comment]
和 #48 是同一個 bug.
