### ISSUE TITLE
Shift按住 輸入全形標點符號

### ISSUE THREAD

**Issue by Tokenyet** [EasyIME/PIME#48]
不管「Shift按住，輸入全形標點符號這個選項是否勾選」
Shift按住後，一定都輸入全形標點符號。
在之前TSF版，不勾選有時候還會導致按住Shift無法輸入任何符號。
我一直在期待這個按住Shift輸入符號的選項能完善說!
如果這功能OK就能拋棄微軟注音了。

**Comment by PCMan** [comment]
經查，和 "中文模式下按住 Shift 快速輸入符號" 開啟有關
這兩個選項要一起關閉才能正確停用 shift 全形符號。
用 shift 輸入全形符號和 shift 快速輸入符號在上游的 libchewing
當中，似乎只能夠同時開關，需要再確認，可能無法從 PIME 這端修正
待進一步檢查...

**Comment by KenLuoTW** [comment]
已修正於 https://github.com/EasyIME/PIME/commit/7ca9e2523f20ba1cad9fe0707c836b58ed52998a ,兩個選項可個別開關,互不影響。
