### ISSUE TITLE
選字鍵自定義

### ISSUE THREAD

**Issue by psc2350** [EasyIME/PIME#494]
能不能添加個選字鍵自定義功能
比如以空白鍵選字
不是單純的空白鍵翻頁在用數字鍵挑字
而是以空白鍵打開候選欄
並且每按一下空白鍵跳下一個候選詞
按著不放就繼續往下跳
確定要用哪個字的時候
在按enter確認
就是能取代原本向下鍵的功能
和日文輸入法的空白鍵差不多
這樣可以減少不少手指移動的距離和時間（只要大拇指按著就可以）

**Comment by ottokang** [comment]
已經發新的PR #500 ，可以的話下載那幾個變動的檔案測試看看

**Comment by psc2350** [comment]
我把chewing資料夾覆蓋後沒法使用，能發一個RELEASE嗎？

**Comment by ottokang** [comment]
請說明一下狀況，變動檔案之後 PIME 要重新啟用才能作用

**Comment by psc2350** [comment]
剛裝了1.2.0-beta1
之前改檔案實在弄不好
在設置看到了使用空白鍵在打字時叫出選字窗口在選字時移動游標(循環)
的功能
不知道這個是不是就是這次更新的功能
只是這功能用了在候選字不超過9個的時候
只能從1跳到4跳到7在跳回1
候選字超過9的注音
在選字的時候會直接跳下一頁
能改成每按一次就從當前候選字跳到下一個候選字嗎?
1>2>3>4這樣

**Comment by ottokang** [comment]
目前測試沒有這樣的狀況，可否詳細說明一下？

**Comment by psc2350** [comment]
https://www4.zippyshare.com/v/TxUamP9X/file.html
我把實際情況錄了個影片
請你看下

**Comment by ottokang** [comment]
OK，知道問題在那邊了，應該把空白鍵模擬成按下 → 的動作，我程式寫成按下 ↓ 的動作，這在單欄模式下不會有問題，不過雙欄就會跟預想的動作的不太一樣，我再去修正。

**Comment by psc2350** [comment]
我試了把"每列顯示候選字個數（1-10）："設置為1
會出現沒法循環的情況，比如說”我”這個字共有４個候選字
到了候選字４就沒法循環回１
然後超過９個候選字的字，比如龍：會和之前錄的影片中（"每列顯示候選字個數（1-10）："設置為３）的情況一樣，本來應該１＞２＞３＞４的，卻成了翻頁的動作
https://www95.zippyshare.com/v/H08DP6jm/file.html
慣例錄了一次影片
拜託你看下了

**Comment by ottokang** [comment]
已經修正發了 PR

**Comment by psc2350** [comment]
請問這個是直接替換425/426這兩行嗎?
我替換了後
還是和之前一樣

**Comment by ottokang** [comment]
替換了要重新啟動 PIME（或者重開機），我這邊測試是 OK 的

**Comment by psc2350** [comment]
我有重啟
只是還是沒法
空白鍵還是只會換頁面
只有同音字在一頁以內的可以

**Comment by psc2350** [comment]
我今天直接把chewing_ime.py下下來替換後重啟
也還是一樣

**Comment by ottokang** [comment]
測試了一下，「我」空白鍵選字不會循環，這應該是小 Bug，我再修正看看，因為空白鍵移動游標我是做成模擬按下 → 的效果，所以要連 → 一起修正，「龍」的話沒有這個問題，你可以直接改那兩行測試看看

**Comment by ottokang** [comment]
你設定檔有選項嗎？
![screenshot_2019-01-02](https://user-images.githubusercontent.com/5523656/50582104-fdf5af00-0e9a-11e9-8596-19a5ffa54d33.png)

**Comment by psc2350** [comment]
https://i.imgur.com/Lguyyv5.png
確實是有的

**Comment by ottokang** [comment]
好吧，等我修正 → 的效果再測試看看

**Comment by psc2350** [comment]
好
麻煩您了

**Comment by ottokang** [comment]
我原本的 PR #507 有新修正，應該是OK了，現在左右鍵、空白鍵可以循環

**Comment by psc2350** [comment]
这个确实是新酷音输入法使用的吗?
不知道为什么我替换了还是没法用
我替换的是C:\Program Files (x86)\PIME\python\input_methods\chewing
目录下的chewing_ime.py
换完后Size on disk是40.0 KB (40,960 bytes)

**Comment by ottokang** [comment]
[chewing_ime.zip](https://github.com/EasyIME/PIME/files/2780935/chewing_ime.zip)
看一下這個檔案

**Comment by psc2350** [comment]
这几天用下来
发现如果是词汇的话
会卡著没法选候选字
比如打出"词汇"之后
只有后面的汇可以选候选字
前面的"词"只能跟著"汇"一起选两字的词汇/辞汇/慈惠/词汇/慈诲
我印象中原本是可以给弟一个字选其他的候选字的
词汇这例子可能不太好
一时想不出更好的例子
但是有时候打字的时候
前后两个字并不希望组成词汇
并且是不同的字
因为这个原因为没法选字
只能回去重打
或者一开始就知道的话，按ENTER跳出候选字模式，把第一个字选完，然后再打第二个字
这个有希望改善吗？

**Comment by ottokang** [comment]
這是新酷音本來的動作，要改可能要改 libchewing 了

**Comment by psc2350** [comment]
要再开一个issue吗?

**Comment by hiunnhue** [comment]
嗨，

沒記錯的話，選字的時候是選「游標後面」的字，如果想要給「詞彙」的「詞」選字，要先把游標移動到「詞」的前面，像是這樣：

```
|詞彙
```

這時按下選字鍵 ( 向下鍵或空白鍵 ) ，出現的就會是「詞」的候選清單了。

**Comment by psc2350** [comment]
看hiunnhue的回复
同原本词汇的例子
打词汇的时候
把游标移动到第一个字
以空白键选字可以跳出"词汇"选单
但是到最后一个的时候会循环到第一个选项
但这时候用向下键的话
则可以选跳出"词"的候选
有办法把空白键做得和向下键一样吗?

**Comment by cherngchin** [comment]
由於在 Mac 上適應慣了，也由於過去的 YahooKeyKey 輸入法，也提供『游標後置』的選字與選詞方式。

因此，一直很期待在 Windows 10 上，PIME 能有個在『游標後置』的選字與選詞的功能選項，讓 PIME 能類似 Apple 的『注音輸入法』或『自然輸入法』那樣使用，那就太完美，太幸福了！

期待啊！
