### ISSUE TITLE
！！！！！发生酷a锁死 打不出中文 解决方法在这！！！！！

### ISSUE THREAD

**Issue by wsxcom** [EasyIME/PIME#495]
用qq电脑管家把PIMELauncher啟動項開啟

打字途中 倉字左方的 中 字 突然不見了（新酷音比照辦理）
用qq電腦管家 選 遊戲加速 把python勾選 點一鍵加速 這時候 中 字 應該出現了
※比如使用qq必須重開 才能再打中文※

**Comment by wsxcom** [comment]
用qq电脑管家把PIMELauncher啟動項開啟

打字途中 倉字左方的 中 字 突然不見了（新酷音比照辦理）
用qq電腦管家 選 遊戲加速 把python勾選 點一鍵加速 這時候 中 字 應該出現了
※比如使用qq必須重開 才能再打中文※

**Comment by wsxcom** [comment]
用qq电脑管家把PIMELauncher啟動項開啟

打字途中 倉字左方的 中 字 突然不見了（新酷音比照辦理）
用qq電腦管家 選 遊戲加速 把python勾選 點一鍵加速 這時候 中 字 應該出現了
※比如使用qq必須重開 才能再打中文※

**Comment by psc2350** [comment]
任務管理氣關閉PIMELauncher.exe就好
然後再去程式目錄重開

**Comment by PCMan** [comment]
Fixed in 1.3.0 beta:
https://github.com/EasyIME/PIME/releases/tag/v1.3.0-beta
