### ISSUE TITLE
PIME 1.2.0-alpha 徵求測試: 修正 bugs + 新增 debug log

### ISSUE THREAD

**Issue by PCMan** [EasyIME/PIME#498]
下載: https://drive.google.com/open?id=1Pp0ajDWsUpoycHj20WD2Oyou1C5AmAZ7
這是使用這個 PR build 出來的版本: https://github.com/EasyIME/PIME/pull/497

改進:
1. 修正兩個記憶體錯誤
2. 移除 PIMEDebugConsole，因不好用，又容易被誤判為惡意程式
3. 加入工作列可叫出選單 "Restart PIME"，可手動強制重啟死掉的 backend servers (鎖死的時候可能有用)
4. 避免 PIMELauncher 重複啟動多份
5. 自動偵測鎖死，當 backend servers 沒回應超過 30 秒自動 restart
6. 新增 debug log 可以透過工作列 popup 選單開關，輸出檔案在: C:\users<user>\AppData\Local\PIME\Log\PIMELaunher.log   這樣當發生當機的時候，就可以調出 debug log，提供更有用的訊息給開發者除錯 (需要手動開啟，因保障隱私，預設是關閉)

警告：這是還在實驗中的版本，並且程式碼還需要 peer review

**Comment by ottokang** [comment]
目前測試還沒什麼問題，也尚未發生之前 PIMELauncher 掛掉的狀況

**Comment by zdd0730** [comment]
可以請問一下，新酷音輸入法，只出現酷，可是沒辦法打字，然後重啟(Restart PIME)也沒有用
只能打英數而已，這樣是怎樣的問題呢？

**Comment by PCMan** [comment]
@zdd0730 你要不要試試看從選單開啟 debug log，然後看看當掉的當下 debug log 裡面有沒有什麼有用資訊？

**Comment by zdd0730** [comment]
有看過了，打開PIMELauncher.log，裡面是空白的

**Comment by mitch0118** [comment]
@PCMan 
最近遇到PIME-1.2.0-beta1失效，工作管理員看不到PIMELauncher，需要手動去資料夾啟動，
以下是LOG
https://drive.google.com/open?id=1TXajFB1ymLe7sZZICHJf4gSdWAAvMKDx

**Comment by zdd0730** [comment]
你好，我這邊遇到是有安裝新的版本，但是重開機後就又只有「酷」圖示，無法打字了
然後連下方PIMELauncher的圖示都沒有

**Comment by mitch0118** [comment]
@PCMan 
新增LOG紀錄，另一臺不同硬體的電腦，相同問題，工作管理員看不到PIMELauncher，需要手動去資料夾啟動，以下是LOG
https://drive.google.com/open?id=1YdzSLZAM35ZyNGvkTUgrrmO0OsX9SodF
---
Windows 10_1809_17763.194

**Comment by PCMan** [comment]
剛更新了 1.3.0-alpha1 版本，可以試試看還有沒有問題
