### ISSUE TITLE
v0.12 自由大新輸入法是否可以作為安裝選擇項目而非必裝？

### ISSUE THREAD

**Issue by Chinan** [EasyIME/PIME#50]
自由大新輸入法是否可以在安裝時作為選擇項目讓使用者選擇是否安裝(即便預設已經打勾都可以)，而非必裝？
對於不用倉頡的使用者，還要移除有些麻煩。

**Comment by darkakia** [comment]
+1

我也覺得直接預設全部裝上去，對我們不用倉頡的人來說是真的有些麻煩。

而且我還想順便回報一個小小的狀況，我也不知道算不算是bug？
就是這一版的PIME裝上Win 10 64 bit之後，
雖然立刻就可以開始使用，但打開「控制台」或「設定」裡面的語言相關列，
是找不到新酷音跟自由大新兩個新增輸入法的。

我卡在這邊想了半天，找不到移除自由大新的方法。

最後我是用了很蠢的方式：「先把新酷音跟自由大新都新增進去，再自己手動移除自由大新。」

**Comment by KenLuoTW** [comment]
已經安裝想移除大新倉頡,可用以下方式:

1: 先以系統管理員身份開啟命令提示字元

![2016-03-16](https://cloud.githubusercontent.com/assets/12954277/13799702/e3a157a8-eb5c-11e5-9cde-85c6bcc73026.png)

切換至 PIME 安裝目錄後,依序輸入:

```
regsvr32.exe /u /s "x86\PIMETextService.dll"

regsvr32.exe /u /s "x64\PIMETextService.dll"

PIMELauncher.exe /quit

rd /s server\input_methods\newcj

regsvr32.exe /s "x86\PIMETextService.dll"

regsvr32.exe /s "x64\PIMETextService.dll"

```

2: 開啟執行視窗 (Win鍵 + R)

![2016-03-16 2](https://cloud.githubusercontent.com/assets/12954277/13799776/8ad7f8d8-eb5d-11e5-94c9-eb324efed5e7.png)

輸入 `"C:\Program Files (x86)\PIME\PIMELauncher.exe"`

Win10 的語言選項裡沒有新酷音,其實是安裝程式要做的事:
在登錄機碼裡加入:

```
[HKEY_CURRENT_USER\Control Panel\International\User Profile\zh-Hant-TW]
"0404:{35F67E9D-A54D-4177-9697-8B0AB71A9E04}{F80736AA-28DB-423A-92C9-5540F501C939}"=dword:00000003
```

數值 dword:00000003 基本要看用戶已裝輸入法的數量而變更。

**Comment by darkakia** [comment]
收到！

感謝！我回家到Win10上試試看！

謝謝！

2016-03-16 10:05 GMT+08:00 Ken Luo <notifications@github.com>:

> 已經安裝想移除大新倉頡,可用以下方式:
>
> 1: 先以系統管理員身份開啟命令提示字元
>
> [image: 2016-03-16]
> <https://cloud.githubusercontent.com/assets/12954277/13799702/e3a157a8-eb5c-11e5-9cde-85c6bcc73026.png>
>
> 切換至 PIME 安裝目錄後,依序輸入:
>
> regsvr32.exe /u /s "x86\PIMETextService.dll"
>
> regsvr32.exe /u /s "x64\PIMETextService.dll"
>
> PIMELauncher.exe /quit
>
> rd /s server\input_methods\newcj
>
> regsvr32.exe /s "x86\PIMETextService.dll"
>
> regsvr32.exe /s "x64\PIMETextService.dll"
>
>
> 2: 開啟執行視窗 (Win鍵 + R)
>
> [image: 2016-03-16 2]
> <https://cloud.githubusercontent.com/assets/12954277/13799776/8ad7f8d8-eb5d-11e5-94c9-eb324efed5e7.png>
>
> 輸入 "C:\Program Files (x86)\PIME\PIMELauncher.exe"
>
> Win10 的語言選項裡沒有新酷音,其實是安裝程式要做的事:
> 在登錄機碼裡加入:
>
> [HKEY_CURRENT_USER\Control Panel\International\User Profile\zh-Hant-TW]
> "0404:{35F67E9D-A54D-4177-9697-8B0AB71A9E04}{F80736AA-28DB-423A-92C9-5540F501C939}"=dword:00000003
>
> 數值 dword:00000003 基本要看用戶已裝輸入法的數量而變更。
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/EasyIME/PIME/issues/50#issuecomment-197112938>
>



-- 
Dark‧淡藍
http://www.dark.idv.tw
E-mail：darkakia@gmail.com
MSN：darkakia@hotmail.com

**Comment by dukelee** [comment]
darkakia 你原本的方法也很好用。

**Comment by Chinan** [comment]
我的系統是 win10 ，會有找不到大新輸入法，所以無法移除的問題。
目前的作法是 到系統去新增大新輸入法，然後再移除他...

**Comment by KenLuoTW** [comment]
我有弄了一個新的安裝程式，預設就是僅安裝新酷音，並且安裝後在語言選項裡即會顯示所裝的輸入法，如果須要的話，可以向我索取。

[修改後的 NSIS 腳本](https://github.com/KenLuoTW/PIME/blob/thcj/installer/installer.nsi)

![2016-03-21](https://cloud.githubusercontent.com/assets/12954277/13912369/5170a928-ef77-11e5-82cf-72159951365d.png)

**Comment by darkakia** [comment]
喔喔！實在太感謝了！

Ken Luo <notifications@github.com> 於 2016年3月21日 下午3:18 寫道：

> 我有弄了一個新的安裝程式，預設就是僅安裝新酷音，並且安裝後在語言選項裡即會顯示所裝的輸入法，如果須要的話，可以向我索取。
>
> 修改後的 NSIS 腳本
> <https://github.com/KenLuoTW/PIME/blob/thcj/installer/installer.nsi>
>
> [image: 2016-03-21]
> <https://cloud.githubusercontent.com/assets/12954277/13912369/5170a928-ef77-11e5-82cf-72159951365d.png>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/EasyIME/PIME/issues/50#issuecomment-199152503>
>



-- 
Dark‧淡藍
http://www.dark.idv.tw
E-mail：darkakia@gmail.com
MSN：darkakia@hotmail.com

**Comment by jessy1092** [comment]
@KenLuoTW cool, 不發個 pr 嗎?   XD

**Comment by KenLuoTW** [comment]
@jessy1092 因為寫入語言選項的機碼應該僅適用 Win8 以後的系統，我還沒確定 Win7 及 Vista 下能不能正常。

**Comment by PCMan** [comment]
Fixed by @KenLuoTW .
