### ISSUE TITLE
v0.12 自訂詞庫錯誤

### ISSUE THREAD

**Issue by zdd0730** [EasyIME/PIME#51]
在Win10 x64環境下，使用v0.12，打字一整句
如...針對區域內之植生現況，之後建立自訂詞庫時
在況的地方按下ctrl+4，反而出現"之植生現"的詞庫
接下來直接打植生現況的時候，但是詞庫自動改成
"之植生現"，可以協助確認一下詞庫的問題嗎?
如果要刪掉這一個錯誤的詞庫要如何操作呢?
以上，謝謝

**Comment by KenLuoTW** [comment]
問題同 #117。
