### ISSUE TITLE
字打不出來，另存打字會出現問題

### ISSUE THREAD

**Issue by wengboyu** [EasyIME/PIME#52]
1)「麼」會打不出來。

2)更新的版本，檔案另存的時候
切注音沒辦法打出中文，切倉頡整個另存畫面會消失。

**Comment by float-tw** [comment]
v0.12 測試
http://dict.variants.moe.edu.tw/yitia/fra/fra04765.htm
除了 ㄇㄛˇ 以外都打的出來

**Comment by zdd0730** [comment]
ㄇㄜ。可以打的出來

**Comment by wengboyu** [comment]
1) 更正說明，應該是只有注音ㄇㄛ˙會打不出麼
2) 另存功能剛測試了一次，切換注音可以了(可能要某種情況下才會出現打不出中文的情況)，但倉頡還是會整個跳掉，點背景後又會跳回來。
測試影片
https://www.youtube.com/watch?v=dc5Ey7COA0I&feature=youtu.be

**Comment by wengboyu** [comment]
因為看不出我有沒有打ㄇㄛ。 想重錄影片，就出現新酷音shift切換後仍打不出注音的問題
https://www.youtube.com/watch?v=t43f_4PyeA0&feature=youtu.be

**Comment by float-tw** [comment]
我想是因為沒有 ㄇㄛ˙ 這個音
可以參考 https://www.moedict.tw/%E9%BA%BC

**Comment by wengboyu** [comment]
了解，看起來是因為原本的注音有這個輸入的音
新酷音則採用了教育部的修訂，所以才會打不出那個字
這個結果讓我著實有些意外，感謝
