### ISSUE TITLE
能不能指定單獨使用"左/右shift"來切換英文

### ISSUE THREAD

**Issue by NatsuArashi** [EasyIME/PIME#53]
如題 左shift在玩遊戲時會跟一些按鍵衝突

**Comment by hsuyh** [comment]
v0.12 可以使用左shift切換中英文

**Comment by NatsuArashi** [comment]
太贊了 那我就關閉討論了 精簡版面

**Comment by NatsuArashi** [comment]
REOPEN...
我看錯你的回應了
你可以再重新看一次我這則Issue

**Comment by hsuyh** [comment]
我懂你的意思了！ 抱歉沒有看清楚....

**Comment by is-me-hlu** [comment]
每次寫程式的時候用左邊的Shift鍵切換英文大小寫，常常變成中文，很不方便，像Windows 10就把左右的Shift當成不同的切換鍵，只有右邊的Shift當成中英文切換，左邊留給其他輸入使用，不知道下一個版本是否可以有此功能。
