### ISSUE TITLE
大易的設定頁面變為無任何設定值

### ISSUE THREAD

**Issue by HPEACE** [EasyIME/PIME#531]
用目前1.2 的beta，發現有時如圖，所有頁籤的設定都變空了
![image](https://user-images.githubusercontent.com/20449305/56271603-72431e00-612b-11e9-9d62-93fd22ce9368.png)

**Comment by cerebellum92** [comment]
我用嘸蝦米也有這個問題。
另外我發現有時候"一般設定"下的子選項"介面外觀"所有的數字都會消失(如下圖)，這樣的情況下嘸蝦米也會無法打字。
![Untitled](https://user-images.githubusercontent.com/9559134/57481673-3bfb4900-7268-11e9-97d9-7e9976b42899.png)

**Comment by HPEACE** [comment]
發現把 .html檔關聯回去給ie就正常了
