### ISSUE TITLE
安裝程式被 Windows Defender SmartScreen 攔截

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [EasyIME/PIME#533]
如下：

![](https://user-images.githubusercontent.com/13408130/56586035-8c8c6880-6611-11e9-9748-381e19da5c06.png)

聽說弄數位簽章「有可能」可以解決（不過好像有人弄了結果從一個警告畫面變成另一個警告畫面就是（汗））

**Comment by ottokang** [comment]
數位簽章要錢，之前贊助的好像沒了

**Comment by PCMan** [comment]
數位簽章要買最貴的 EV 才能避免這個，但那個通常只賣給公司行號而且一年好幾萬，沒辦法
