### ISSUE TITLE
在outlook 2016輸入會變成黑色方塊 (win10)

### ISSUE THREAD

**Issue by cassidy1226** [EasyIME/PIME#545]
Win10更新後在outlook 2016輸入會變成黑色方塊(如下圖)
按enter後才會看到輸入的字是不是正確，無法直接選
![image](https://user-images.githubusercontent.com/53845016/62589554-34e1e680-b8fc-11e9-920a-eb24f412cf12.png)
目前僅有出現在outlook，其他office軟體無此問題，請問有其他人遇到這個狀況嗎~?

**Comment by J4X0N** [comment]
windows 10 1903 深色模式 word 365 也會

**Comment by GelionLin** [comment]
Windows 10 1903, Outlook 2016/2019也都會有這樣的問題
Outlook確切版號為 1908(11929.20396)

**Comment by slowman001** [comment]
在office 內都會，不只outlook

**Comment by GelionLin** [comment]
> 在office 內都會，不只outlook
我使用Office 365, Word沒有這個問題
Version 1908 (11929.20516)
另外測試過
Word/Excel/PowerPoint都沒問題, 僅有Outlook有問題
是否可以提供版本號作為參考?

**Comment by PCMan** [comment]
我有找到可能的問題了，正在修正。
希望近期可以發布新的版本

**Comment by PCMan** [comment]
https://github.com/EasyIME/PIME/releases/tag/v1.3.0-alpha1
新版本，請幫忙確認是否還有這問題
我這邊測試是修好了，謝謝

**Comment by GelionLin** [comment]
目前沒有遇到問題
感謝!

**Comment by PCMan** [comment]
fixed.
