### ISSUE TITLE
無法使用編輯詞庫及設定功能

### ISSUE THREAD

**Issue by ushenli** [EasyIME/PIME#548]
這兩個功能按下去後，不像之前會打開網頁頁面
現在只會跳出記事本視窗，如下圖
https://imgur.com/NpekKPT

不知有沒有什麼暫時的方法可調整設定呢？

回不去微軟輸入法了，不能設定好崩潰阿
重裝後原本用習慣的特殊字元都沒了

**Comment by ottokang** [comment]
你的 html 檔預設開啟可能被改到記事本了，改成用瀏覽器看看

**Comment by ushenli** [comment]
可以了！太厲害了大大！謝謝！
