### ISSUE TITLE
win10家用版更新至1809(OS組建17763.774)之後，酷倉輸入法無法使用

### ISSUE THREAD

**Issue by cjykey** [EasyIME/PIME#551]
win10家用版更新至1809(OS組建17763.774)之後，酷倉輸入法無法使用。雖然按了win鍵+space之後可以看到pime輸入法，但是進入word、chrome等等任何程式用pime酷倉輸入法輸入文字之後，只會顯示倉頡碼（下面有點點點），不會變成文字。
![win鍵+space之後可以看到的畫面](https://user-images.githubusercontent.com/53204387/65734786-37480c00-e107-11e9-913a-3a544c1eb5eb.jpg)

**Comment by cjykey** [comment]
![擷取](https://user-images.githubusercontent.com/53204387/65930390-2e717600-e438-11e9-91e9-95435489c6c4.jpg)

**Comment by cjykey** [comment]
應該出現的的文字是[今天中華民國一百零八年]

**Comment by Nick838** [comment]
用Win10 1903版本，可以打中文...

**Comment by cjykey** [comment]
謝謝您！原來win10 1903版之後不會自動升級，必須去微軟的官網去下載安裝小幫手。後來升級到1903版、net.frame也同步升級之後，就可以打中文了！感激涕零～
