### ISSUE TITLE
不能build Visual Studio 2019

### ISSUE THREAD

**Issue by martimafonso** [EasyIME/PIME#554]
抱歉由我的中文、是要需visual studio 2015 为筑成吗、我在使用visual studio 2019

Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	718		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	411		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	667		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	735		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	738		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	741		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	757		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	751		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	760		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	763		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	773		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	239		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	802		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	856		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	807		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	817		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	783		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	786		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	796		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	879		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	898		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	968		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	984		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	1002		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	1018		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	1025		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	1038		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	1056		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	1076		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	1102		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	1192		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	1256		
Warning	C4702	unreachable code	jsoncpp_lib_static	C:\Users\Microsoft\PIME\jsoncpp\src\lib_json\json_value.cpp	124		
Error	C2238	unexpected token(s) preceding ';'	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	128		
Error	C2238	unexpected token(s) preceding ';'	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	128		
Error	C2238	unexpected token(s) preceding ';'	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	128		
Error	C2238	unexpected token(s) preceding ';'	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	128		
Error	C2238	unexpected token(s) preceding ';'	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	128		
Error	C2238	unexpected token(s) preceding ';'	PIMETextService	C:\Users\Microsoft\PIME\LibIME\TextService.h	128		
Error	C2238	unexpected token(s) preceding ';'	PIMETextService	C:\Users\Microsoft\PIME\libIME\TextService.h	128		
Error	C2059	syntax error: '('	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	128		
Error	C2059	syntax error: '('	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	128		
Error	C2059	syntax error: '('	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	128		
Error	C2059	syntax error: '('	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	128		
Error	C2059	syntax error: '('	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	128		
Error	C2059	syntax error: '('	PIMETextService	C:\Users\Microsoft\PIME\LibIME\TextService.h	128		
Error	C2059	syntax error: '('	PIMETextService	C:\Users\Microsoft\PIME\libIME\TextService.h	128		
Error	C2001	newline in constant	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	26		
Error	C2001	newline in constant	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	26		
Error	C2001	newline in constant	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	26		
Error	C2001	newline in constant	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	26		
Error	C2001	newline in constant	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	26		
Error	C2001	newline in constant	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	26		
Error	C2001	newline in constant	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	26		
Error	C2001	newline in constant	PIMETextService	C:\Users\Microsoft\PIME\LibIME\TextService.h	26		
Error	C2001	newline in constant	PIMETextService	C:\Users\Microsoft\PIME\LibIME\TextService.h	26		
Error	C2001	newline in constant	PIMETextService	C:\Users\Microsoft\PIME\libIME\TextService.h	26		
Error	C2001	newline in constant	PIMETextService	C:\Users\Microsoft\PIME\LibIME\TextService.h	26		
Error (active)	E0070	incomplete type is not allowed	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	249		
Error (active)	E0013	expected a file name	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	26		
Error	C2039	'wstring': is not a member of 'std'	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	128		
Error	C2039	'wstring': is not a member of 'std'	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	128		
Error	C2039	'wstring': is not a member of 'std'	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	128		
Error	C2039	'wstring': is not a member of 'std'	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	128		
Error	C2039	'wstring': is not a member of 'std'	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	128		
Error	C2039	'wstring': is not a member of 'std'	PIMETextService	C:\Users\Microsoft\PIME\LibIME\TextService.h	128		
Error	C2039	'wstring': is not a member of 'std'	PIMETextService	C:\Users\Microsoft\PIME\libIME\TextService.h	128		
Warning	C4005	'WIN32_LEAN_AND_MEAN': macro redefinition	libIME_static	C:\Users\Microsoft\PIME\libIME\libIME.h	35		
Warning	C4005	'WIN32_LEAN_AND_MEAN': macro redefinition	libIME_static	C:\Users\Microsoft\PIME\libIME\libIME.h	35		
Warning	C4005	'WIN32_LEAN_AND_MEAN': macro redefinition	libIME_static	C:\Users\Microsoft\PIME\libIME\libIME.h	35		
Warning	C4005	'WIN32_LEAN_AND_MEAN': macro redefinition	libIME_static	C:\Users\Microsoft\PIME\libIME\libIME.h	35		
Warning	C4005	'WIN32_LEAN_AND_MEAN': macro redefinition	libIME_static	C:\Users\Microsoft\PIME\libIME\libIME.h	35		
Warning	C4005	'WIN32_LEAN_AND_MEAN': macro redefinition	libIME_static	C:\Users\Microsoft\PIME\libIME\libIME.h	35		
Warning	C4005	'WIN32_LEAN_AND_MEAN': macro redefinition	libIME_static	C:\Users\Microsoft\PIME\libIME\libIME.h	35		
Warning	C4005	'WIN32_LEAN_AND_MEAN': macro redefinition	libIME_static	C:\Users\Microsoft\PIME\libIME\libIME.h	35		
Warning	C4005	'WIN32_LEAN_AND_MEAN': macro redefinition	PIMETextService	C:\Users\Microsoft\PIME\LibIME\libIME.h	35		
Warning	C4005	'WIN32_LEAN_AND_MEAN': macro redefinition	PIMETextService	C:\Users\Microsoft\PIME\LibIME\libIME.h	35		
Warning	C4005	'WIN32_LEAN_AND_MEAN': macro redefinition	PIMETextService	C:\Users\Microsoft\PIME\libIME\libIME.h	35		
Warning	C4005	'WIN32_LEAN_AND_MEAN': macro redefinition	PIMETextService	C:\Users\Microsoft\PIME\LibIME\libIME.h	35		
Warning	C4312	'type cast': conversion from 'UINT' to 'LPCTSTR' of greater size	libIME_static	C:\Users\Microsoft\PIME\libIME\LangBarButton.cpp	121		
Warning	C4996	'stricmp': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _stricmp. See online help for details.	PIMETextService	C:\Users\Microsoft\PIME\PIMETextService\PIMEImeModule.cpp	98		
Warning	C4996	'Json::ValueIteratorBase::memberName': Use `key = name();` instead.	PIMETextService	C:\Users\Microsoft\PIME\PIMETextService\PIMEClient.cpp	93		
Warning	C4996	'Json::Reader::Reader': Use CharReader and CharReaderBuilder instead	PIMETextService	C:\Users\Microsoft\PIME\PIMETextService\PIMEClient.cpp	675		
Warning	C4996	'Json::Reader::parse': Use CharReader and CharReaderBuilder instead	PIMETextService	C:\Users\Microsoft\PIME\PIMETextService\PIMEClient.cpp	676		
Warning	C4996	'Json::Reader': Use CharReader and CharReaderBuilder instead	PIMETextService	C:\Users\Microsoft\PIME\PIMETextService\PIMEClient.cpp	675		
Warning	C4996	'Json::FastWriter::write': Use StreamWriterBuilder instead	PIMETextService	C:\Users\Microsoft\PIME\PIMETextService\PIMEClient.cpp	652		
Warning	C4996	'Json::FastWriter::FastWriter': Use StreamWriterBuilder instead	PIMETextService	C:\Users\Microsoft\PIME\PIMETextService\PIMEClient.cpp	651		
Warning	C4996	'Json::FastWriter': Use StreamWriterBuilder instead	PIMETextService	C:\Users\Microsoft\PIME\PIMETextService\PIMEClient.cpp	651		
Warning	C4244	'initializing': conversion from 'WPARAM' to 'UINT', possible loss of data	libIME_static	C:\Users\Microsoft\PIME\libIME\KeyEvent.cpp	26		
Warning	C4267	'initializing': conversion from 'size_t' to 'int', possible loss of data	libIME_static	C:\Users\Microsoft\PIME\libIME\MessageWindow.cpp	75		
Warning	C4267	'initializing': conversion from 'size_t' to 'int', possible loss of data	libIME_static	C:\Users\Microsoft\PIME\libIME\CandidateWindow.cpp	255		
Warning	C4267	'initializing': conversion from 'size_t' to 'int', possible loss of data	libIME_static	C:\Users\Microsoft\PIME\libIME\CandidateWindow.cpp	285		
Warning	C4267	'initializing': conversion from 'size_t' to 'int', possible loss of data	libIME_static	C:\Users\Microsoft\PIME\libIME\CandidateWindow.cpp	318		
Warning	C4267	'initializing': conversion from 'size_t' to 'int', possible loss of data	PIMETextService	C:\Users\Microsoft\PIME\PIMETextService\DllEntry.cpp	60		
Warning	C4996	'GetVersion': was declared deprecated	libIME_static	C:\Users\Microsoft\PIME\libIME\WindowsVersion.h	15		
Warning	C4996	'GetVersion': was declared deprecated	libIME_static	C:\Users\Microsoft\PIME\libIME\WindowsVersion.h	15		
Warning	C4996	'GetVersion': was declared deprecated	libIME_static	C:\Users\Microsoft\PIME\libIME\WindowsVersion.h	15		
Warning	C4996	'GetVersion': was declared deprecated	libIME_static	C:\Users\Microsoft\PIME\libIME\WindowsVersion.h	15		
Warning	C4996	'GetVersion': was declared deprecated	libIME_static	C:\Users\Microsoft\PIME\libIME\WindowsVersion.h	15		
Warning	C4996	'GetVersion': was declared deprecated	PIMETextService	C:\Users\Microsoft\PIME\LibIME\WindowsVersion.h	15		
Warning	C4996	'GetVersion': was declared deprecated	PIMETextService	C:\Users\Microsoft\PIME\LibIME\WindowsVersion.h	15		
Warning	C4996	'GetVersion': was declared deprecated	PIMETextService	C:\Users\Microsoft\PIME\LibIME\WindowsVersion.h	15		
Warning	C4996	'GetVersion': was declared deprecated	PIMETextService	C:\Users\Microsoft\PIME\LibIME\WindowsVersion.h	15		
Warning	C4996	'GetVersion': was declared deprecated	PIMETextService	C:\Users\Microsoft\PIME\LibIME\WindowsVersion.h	15		
Error	C2065	'composition_': undeclared identifier	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.cpp	234		
Error	C2065	'composition_': undeclared identifier	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.cpp	236		
Error	C3646	'compositionString': unknown override specifier	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	128		
Error	C3646	'compositionString': unknown override specifier	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	128		
Error	C3646	'compositionString': unknown override specifier	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	128		
Error	C3646	'compositionString': unknown override specifier	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	128		
Error	C3646	'compositionString': unknown override specifier	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.h	128		
Error	C3646	'compositionString': unknown override specifier	PIMETextService	C:\Users\Microsoft\PIME\LibIME\TextService.h	128		
Error	C3646	'compositionString': unknown override specifier	PIMETextService	C:\Users\Microsoft\PIME\libIME\TextService.h	128		
Error	C2039	'compositionString': is not a member of 'PIME::TextService'	PIMETextService	C:\Users\Microsoft\PIME\PIMETextService\PIMEClient.cpp	245		
Error	C2039	'compositionString': is not a member of 'Ime::TextService'	libIME_static	C:\Users\Microsoft\PIME\libIME\TextService.cpp	233		
Warning	C4267	'argument': conversion from 'size_t' to 'ULONG', possible loss of data	libIME_static	C:\Users\Microsoft\PIME\libIME\ImeModule.cpp	161		
Warning	C4267	'argument': conversion from 'size_t' to 'ULONG', possible loss of data	PIMETextService	C:\Users\Microsoft\PIME\PIMETextService\PIMEClient.cpp	496		
Warning	C4267	'argument': conversion from 'size_t' to 'UINT', possible loss of data	libIME_static	C:\Users\Microsoft\PIME\libIME\CandidateWindow.cpp	412		
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	libIME_static	C:\Users\Microsoft\PIME\libIME\Utils.cpp	47		
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	libIME_static	C:\Users\Microsoft\PIME\libIME\Utils.cpp	50		
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	libIME_static	C:\Users\Microsoft\PIME\libIME\MessageWindow.cpp	41		
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	libIME_static	C:\Users\Microsoft\PIME\libIME\CandidateWindow.cpp	298		
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	PIMETextService	C:\Users\Microsoft\PIME\PIMETextService\PIMEClient.cpp	187		
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	PIMETextService	C:\Users\Microsoft\PIME\PIMETextService\PIMEClient.cpp	219		
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	PIMETextService	C:\Users\Microsoft\PIME\PIMETextService\PIMEClient.cpp	674		
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data	PIMETextService	C:\Users\Microsoft\PIME\PIMETextService\DllEntry.cpp	114		
Warning	C4267	'argument': conversion from 'size_t' to 'DWORD', possible loss of data	libIME_static	C:\Users\Microsoft\PIME\libIME\ImeModule.cpp	276		
Warning	C4267	'argument': conversion from 'size_t' to 'const _Ty', possible loss of data
        with
        [
            _Ty=UINT
        ]	libIME_static	C:\Users\Microsoft\PIME\libIME\CandidateWindow.cpp	147		
Warning	C4244	'=': conversion from 'UINT_PTR' to 'UINT', possible loss of data	PIMETextService	C:\Users\Microsoft\PIME\PIMETextService\PIMETextService.cpp	370		
Warning	C4244	'=': conversion from 'UINT_PTR' to 'UINT', possible loss of data	PIMETextService	C:\Users\Microsoft\PIME\PIMETextService\PIMEClient.cpp	538		
Warning	C4244	'=': conversion from 'UINT_PTR' to 'UINT', possible loss of data	PIMETextService	C:\Users\Microsoft\PIME\PIMETextService\PIMEClient.cpp	659		
Warning	C4267	'=': conversion from 'size_t' to 'int', possible loss of data	libIME_static	C:\Users\Microsoft\PIME\libIME\CandidateWindow.cpp	309		
Warning	C4267	'+=': conversion from 'size_t' to 'int', possible loss of data	libIME_static	C:\Users\Microsoft\PIME\libIME\CandidateWindow.cpp	310

**Comment by PCMan** [comment]
已經修正了，現在最新版本是用 VC++ build
https://github.com/EasyIME/PIME/releases/tag/v1.3.0-alpha1

README 我有更新了一下，您可以再拉最新的 master branch 試試，
如果還不行請提供錯誤訊息 re-open 這張謝謝
