### ISSUE TITLE
微軟最新更新災情回報

### ISSUE THREAD

**Issue by cjykey** [EasyIME/PIME#555]
通報微軟最新更新災情：日前微軟更新至1903版（OS組建 18362.449）、NET Framework 4.8版（528040）之後，酷倉輸入法無法使用。

問題回報：第一次鍵入酷倉輸入碼＋space bar之後，只會顯示拆碼，然後輸入欄就一直顯示英文狀態，無法再輸入中文。將pime輸入法移除再重灌beta版＋重開機，問題仍未獲解決。

麻煩各位大大！謝謝！

**Comment by jhhg** [comment]
我也是家用版win10升級成 1903(KB4522355)後，PIME連安裝都無法了（有先關掉防毒軟體）。求解。感謝！！！

**Comment by cjykey** [comment]
今天早上發現微軟又更新至1903版（OS組建 18362.476），但是pime輸入法還是無法使用。

問題描述：
1.shift鍵無法啟動中英文切換，必須用滑鼠點選中英文切換。
2.進入word後，在 插入 狀態下，輸入的字碼會變成黑色：在 取代 狀態下，會顯示輸入的字碼，但沒有底線，按了space bar後，字碼就消失了：接下來會進入英文狀態，無法再使用滑鼠進入中文狀態，即使重新啟動PIMELauncher.exe，又會回到前面的輪迴。
3.chrome及IE的搜尋列也無法使用pime輸入法。

再麻煩各位大大！謝謝！

**Comment by ottokang** [comment]
我這邊沒有遇到相關的問題，1903 跟 1909 都正常使用，有試過 1.2 Beta 嗎？

**Comment by cjykey** [comment]
兩個版本都重灌過，結果pime輸入法還是都無法使用。我今天回家再試試看移除pime，再重灌1.2 Beta版一次。

**Comment by cjykey** [comment]
昨天回家重灌pime以後，結果還是令人失望。首先是無法使用shift鍵進行中英文切換，必須用滑鼠點選進入中文狀態。輸入的字碼雖然會出現，但是按了空白鍵後就變不見，直接進入英文狀態，也無法再用滑鼠點選進入中文狀態。word無論是插入或取代的狀態都是如此。

重新執行PIMELauncher.exe，又重複前面的狀態。

**Comment by pankpan** [comment]
1903 使用 1.2 Beta 正常

**Comment by cjykey** [comment]
1909版無法使用1.2 Beta

**Comment by cjykey** [comment]
向各位大大報告：我好像找到解決的方法了。連日來在網路上爬文，發現有人建議把「觸控鍵盤及手寫辨識板服務」（預設為手動）關閉，就可以解決很多win10的卡卡問題。不過我發現我家的電腦並沒有這個選項，比較相近的選項是「改進手寫筆跡與鍵入」，抱著姑且一試的心理，我把這個選項關閉，沒想到～奇蹟出現了～，酷倉輸入法在重新設定之後（包括詞庫及相關的設定），居然可以正常輸入了！ 
![辨識關閉2](https://user-images.githubusercontent.com/53204387/71329675-cb890a00-2562-11ea-8156-3d8a4c167c0a.jpg)
