### ISSUE TITLE
大大，您辛苦了！新酷音真的很棒，這裡有個小小建議....

### ISSUE THREAD

**Issue by GitHuberRich** [EasyIME/PIME#562]
不知道是否可以加上快速切換簡繁輸出的功能？
如果可以的話，那新酷音就可以完全取代新注音了！
懇切希望您採納我的建議~
感恩！

**Comment by ottokang** [comment]
軟體熱鍵眾多，目前先設定 Ctrl + F12 作為切換的熱鍵，可以在選項中打開這個設定，已經發PR #564

**Comment by GitHuberRich** [comment]
感謝您！辛苦了！新酷音萬歲~~~

**Comment by GitHuberRich** [comment]
> 目前先設定 Ctrl + F12 作為切換簡體/繁體的熱鍵，可以在選項中打開這個設定，已經發PR #564

大佬~簡繁切換的部分跟您回報一下，目前使用上還沒發現問題，不過有個小建議您請參考一下，不知道可否顯示簡繁的狀態呢？因為有時候視窗換來換去，雖然都同樣使用新酷音，但看不出當下是簡體或繁體，

**Comment by ottokang** [comment]
右下角圖示應該可以，就中文繁體、中文簡體、英文這樣顯示

**Comment by ottokang** [comment]
已發 #575

**Comment by GitHuberRich** [comment]
> 右下角圖示應該可以，就中文繁體、中文簡體、英文這樣顯示

感謝大大，如果"中文簡體" "中文繁體" 字太多，可顯示 "簡" "繁" "EN" 即可，您辛苦了！
