### ISSUE TITLE
新酷音輸入結果異常

### ISSUE THREAD

**Issue by m9025019** [EasyIME/PIME#57]
1.使用新酷音輸入法，明明是選取中文輸入區分，但卻只能打出英文字。
2.再切換多次輸入法後，顯示「中」的圖示變為空白。
3.有將過程錄製起來，請查看錄影檔。
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/17918437/13867532/c7e89f86-ecfa-11e5-8ff2-568e12792e36.gif)

**Comment by KenLuoTW** [comment]
設定裡頭要將『使用 CapsLock 切換中英文』取消

![2016-03-19](https://cloud.githubusercontent.com/assets/12954277/13883810/29a25a62-ed66-11e5-92cf-2c4a9daa4471.png)

此功能應該不是 bug,我猜應該是暫時在中文輸入模式下強制輸入英文的功能。

**Comment by m9025019** [comment]
收到～我在試用看看～
