### ISSUE TITLE
Windows Defender 把1.3.0 alpha 的PIMELauncher.exe視為病毒

### ISSUE THREAD

**Issue by hsuth** [EasyIME/PIME#573]
看了舊的Issue，應該是老問題。只是提醒一下，如果開機後PIME不能執行，要去Windows Defender設定一下不要隔離PIMELauncher.exe。
![擷取](https://user-images.githubusercontent.com/19405399/79050443-9cef8600-7c5c-11ea-9fc4-fd7ecbc5f036.PNG)

**Comment by Nick838** [comment]
剛巧也遇到bug.
Cap圖: https://i.imgur.com/ufAMYTz.jpg

**Comment by ADeeeee** [comment]
不只有 Windows Denfender，公司電腦裝的防毒好像也直接把 PIMELauncher.exe 給砍了，刪除重裝 1.3.0 alpha 版好像都不行，退回 1.2.0 beta1 就沒問題

**Comment by PCMan** [comment]
![圖片](https://user-images.githubusercontent.com/46543/80117550-e70c2c00-85b9-11ea-9aa9-e02776fe2507.png)
確實是微軟誤判啊，回報很多次了但是他們都還沒有回，一直在處理中

**Comment by PCMan** [comment]
Fixed in 1.3.0 beta:
https://github.com/EasyIME/PIME/releases/tag/v1.3.0-beta
