### ISSUE TITLE
pime 110版 可以在win7 64棋間版完美使用 不會出現鎖死中文打不出的問題！

### ISSUE THREAD

**Issue by wsxcom** [EasyIME/PIME#578]
pime 110版 可以在win7 64棋間版完美使用 不會出現鎖死中文打不出的問題！

**Comment by rongggengli** [comment]
pime 110 also works perfectly on win10 64.

**Comment by littlesoda** [comment]
win10 64 110版在office會有黑底的問題

**Comment by PCMan** [comment]
Fixed in 1.3.0 beta:
https://github.com/EasyIME/PIME/releases/tag/v1.3.0-beta
