### ISSUE TITLE
被 Windows Defender 視為特洛伊木馬病毒

### ISSUE THREAD

**Issue by lonnyshoal** [EasyIME/PIME#580]
被 Windows Defender 視為特洛伊木馬病毒

![image](https://user-images.githubusercontent.com/64345299/80298721-e0e89c00-87c1-11ea-90ee-d70ef6e4949b.png)
![image](https://user-images.githubusercontent.com/64345299/80298740-fc53a700-87c1-11ea-99be-20c986833473.png)

**Comment by PCMan** [comment]
Fixed in 1.3.0 beta:
https://github.com/EasyIME/PIME/releases/tag/v1.3.0-beta
