### ISSUE TITLE
無法打開"編輯使用者詞庫" 另外跳出launch_user_phrase_editor.html

### ISSUE THREAD

**Issue by zero11995** [EasyIME/PIME#587]
重新安裝也沒用
按下編輯使用者詞庫只會跳出這個檔案

![新酷音-編輯使用者詞庫](https://user-images.githubusercontent.com/23001155/83106386-f61d5700-a0ee-11ea-85ed-8d3c84b2bf2b.PNG)

新酷音版本: 1.2.0-beta1
Windows 10 專業版
版本1909

**Comment by PCMan** [comment]
原因是你系統上預設開啟 html 檔案的是編輯器，不是瀏覽器。
調整系統設定讓 html 檔案預設游 瀏覽器開啟即可
