### ISSUE TITLE
想問下作者，如果要讀懂這個程序需要學習py到什麼程度？

### ISSUE THREAD

**Issue by shenkuantipang** [EasyIME/PIME#59]
想問下作者，如果要讀懂這個程序需要學習py到什麼程度？

**Comment by PCMan** [comment]
初學到稍微進階即可，因為主要會讀不懂的部分其實是 C++ 寫的

**Comment by jessy1092** [comment]
@shenkuantipang 其實蠻好懂的，可以先從喵喵輸入法開始 https://github.com/EasyIME/PIME/tree/master/server/input_methods/meow

**Comment by lyenliang** [comment]
搭配 [PyCharm](https://www.jetbrains.com/pycharm/) 的 debug 模式來看 code 蠻方便的。

**Comment by shenkuantipang** [comment]
那c++要学习哪些不需要学习哪些呢？
