### ISSUE TITLE
無法進入設定輸入法模組

### ISSUE THREAD

**Issue by leafar0401** [EasyIME/PIME#591]
我的系統是Win8.1,JAVA已經更新到最新版本,預計安裝的是酷倉輸入法,安裝後想要進去設定頁去更改為自由大新
在嘗試安裝完V1.3.0-beta以後發現無法設定輸入法,後來就下了其他版本,發現V1.1.0/V1.0.0下依然無法進入設定網頁,只有在V0.16.1下可以設定輸入法
在按下**設定酷倉輸入法**或右鍵點擊右下**中**字圖標進入**設定輸入法模組**時,都會跳出一個命名為**launch_config.html**的記事本,內容為:
**< html>
    < form id="auth" action="http://127.0.0.1:27408/login/config" method="POST">
        < input type="hidden" name="token" value="8f4786e01e784549960c0df5c31a7e8c">
    < /form>
    < script type="text/javascript">
        document.getElementById("auth").submit();
    < /script>
    < /html>** (去除 **<** 後空格)
已經試過在安全模式底下安裝,然而也是一樣的情形
請問有人遇過類似情況嗎? 求解... m(_ _)m

**Comment by HPEACE** [comment]
跟這個一樣 https://github.com/EasyIME/PIME/issues/531#issue-434148970 對吧
不知是什麼原因.....

**Comment by leafar0401** [comment]
有點不一樣，因為不會跳出頁籤，只會出現記事本和類似主題裡的內文

**Comment by HPEACE** [comment]
依擄您的描述，應該是.html的檔案關聯被關聯在notepad了
而也依此思考方向，我把我的 .html檔關聯回去給ie就正常了

**Comment by leafar0401** [comment]
真的！十分感謝您！
我居然沒有想到這個可能
真的是重新關聯回去就正常了！！
