### ISSUE TITLE
按下「`」呼叫特殊符號輸入視窗，有出現選字游標，但是不能使用方向鍵

### ISSUE THREAD

**Issue by ottokang** [EasyIME/PIME#6]
按下「`」呼叫特殊符號輸入視窗，有出現選字游標，但是不能使用方向鍵，也不能使用NumPad區的按鈕選字，只能使用數字鍵選字，找了一下似乎不是libchewing的問題，TSF版本可以正常運作，但是PIME不行

**Comment by ottokang** [comment]
按下「`」呼叫特殊符號輸入視窗，有出現選字游標，但是不能使用方向鍵，也不能使用NumPad區的按鈕選字，只能使用數字鍵選字，找了一下似乎不是libchewing的問題，TSF版本可以正常運作，但是PIME不行

**Comment by lyenliang** [comment]
我發現必須在還沒把字選好時，才能用方向鍵選字。字選完後，如果再按「`」的話，就會無法用方向鍵選字，不曉得ottokang跟我電腦上看到的情況是否一樣？我是在Windows 7專業版上用PIME的。

**Comment by ottokang** [comment]
我也是 Windows 7 專業版，測試了一下：
1. 輸入區有字，先打字後按下「`」：所有功能正常作用
2. 輸入區沒字，第一個按下「`」：上下左右、Enter、NumPad 區數字鍵都不能使用，只能使用數字鍵選字

看來應該是 PIME 過濾按鍵的問題，明天再來研究看看

**Comment by PCMan** [comment]
it's already fixed in git HEAD.
https://github.com/EasyIME/PIME/commit/e518c8eff8ac52616d3a4d756bfd19f4c5f8abbf
