### ISSUE TITLE
在部份程式，無法輸入中文僅能輸入英數

### ISSUE THREAD

**Issue by tomoewcc** [EasyIME/PIME#60]
目前是使用win10，使用google chrome, evernote等程式時，會忽然無法輸入中文。
以shift切換亦無反應。切回微軟新注音時，會顯示英數模式，但無論是在新注音按shift
或回到新酷音按shift，都無法輸入中文。

有時候在其他程式會忽然可以輸入。

**Comment by KenLuoTW** [comment]
請將微軟新注音移除，因為問題是它引起的，不是 PIME 下的輸入法。

**Comment by PCMan** [comment]
目前版本已經無法重現此問題。
