### ISSUE TITLE
請問新酷音可以在MAC上使用嗎？！

### ISSUE THREAD

**Issue by sccool-Shih** [EasyIME/PIME#606]
您好～
請問新酷音可以在MAC上使用嗎？！因為這個輸入法用習慣了～
謝謝喔 
PS: 我有爬文可是沒有找到所以才來這裡詢問 謝謝喔

**Comment by ottokang** [comment]
目前沒有，Mac 上類似的注音輸入法建議可以用小麥輸入法 [https://mcbopomofo.openvanilla.org/](url)
