### ISSUE TITLE
在 Facebook 下無法輸入

### ISSUE THREAD

**Issue by markwu** [EasyIME/PIME#616]
最近才開始發生，原因不明。在Facebook 下輸入後，無法再行輸入，游標會跑到 input/texarea 的最前面。必須重整頁面後才有辦法繼續輸入。

不確定是 Facebook 問題或是 PIME 問題，但是現在的確只在 Facebook 發生。

瀏覽器為 Chrome 和 Firefox 最新版。

**Comment by NedLin9527** [comment]
一樣的問題
不過瀏覽器使用的是新版 Windows Edge ft. Chromium
