### ISSUE TITLE
快速鍵刪除詞彙功能建議

### ISSUE THREAD

**Issue by tottoko99** [EasyIME/PIME#617]
原本就是因為新注音的自動加入詞彙功能，以及記數錯誤導致常用詞置底，才更換使用新酷音的。

當時非常喜歡ctrl+數字的記憶詞彙熱鍵，因為不需要甚至不常用的詞彙並不會想要紀錄。

雖然自動學習功能對於預選詞有幫助，但是像是 #341 提到的，打錯的詞彙會進入到選字裡面。
無法快速刪除錯誤的詞彙，詞庫又過度膨脹，總是覺得有點遺憾。

不知道能不能拆分自動學習的詞彙，以及手動紀錄的詞彙，至少讓自動學習的詞彙不會出現在手選詞彙內。
或是手選詞彙的時候，可以用類似alt+del的熱鍵刪除詞彙。

**Comment by ottokang** [comment]
已經提交新的 PR #655 ，使用者現在可以在選字視窗中用 Ctrl + Delete 刪除詞彙
