### ISSUE TITLE
Please update taskbar icon for win10 light theme

### ISSUE THREAD

**Issue by sugigu** [EasyIME/PIME#619]
when using win10 light theme, all taskbar icon turns black, but chewing tsf remain white, please update.
<a href="https://ibb.co/ySMcQyf"><img src="https://i.ibb.co/ySMcQyf/tsf.png" alt="tsf" border="0"></a>

**Comment by ottokang** [comment]
Windows 的輸入法圖示設計準則就是白色底色，內建的注音、倉頡圖示也都維持白色底
