### ISSUE TITLE
Selecting character makes page disappear in Windows7 Chrome

### ISSUE THREAD

**Issue by ShengYenPeng** [EasyIME/PIME#62]
Hi,

when I download and rename my file in "save as" page,

selecting character makes "save as" page disappear, like:
![image](https://cloud.githubusercontent.com/assets/16522555/13944135/76b79b94-f03d-11e5-8f6a-f3f9c041b7f1.png)

it seems that selecting character makes browser page pop out, like
![image](https://cloud.githubusercontent.com/assets/16522555/13944153/8dbf9756-f03d-11e5-8855-b756bd678f7c.png)

and I find 新注音 also have some problem,but it will make "save as" page appear in front again(you may feel a little flash, that is what it does)

**Comment by PCMan** [comment]
目前版本已經無此問題。
