### ISSUE TITLE
此掃毒軟體一直跳狀態 還排除不掉....

### ISSUE THREAD

**Issue by rut9999999999** [EasyIME/PIME#624]
加入排除還是一直狂跳  不知為何 ...

<a href="https://imgur.com/ULqTaVa"><img src="https://i.imgur.com/ULqTaVa.png" title="source: imgur.com" /></a>

**Comment by HPEACE** [comment]
怎麼排的？貼一下圖吧
（貼圖時解析度注意一下，太糊了，看不太清楚）

**Comment by rut9999999999** [comment]
> 怎麼排的？貼一下圖吧
> （貼圖時解析度注意一下，太糊了，看不太清楚


https://upload.cc/i1/2021/05/28/SsgvRt.png
https://upload.cc/i1/2021/05/28/3OytNX.png
https://upload.cc/i1/2021/05/28/AExeQj.png)

**Comment by ottokang** [comment]
安裝檔都有買簽章，應該是防毒軟體誤判，就等防毒軟體更新吧
