### ISSUE TITLE
建議功能 以組合鍵快速刪除自訂詞庫中的 數個字

### ISSUE THREAD

**Issue by PICAPICAP** [EasyIME/PIME#630]
您們好，不知道是不是個人沒有熟悉使用方法，
目前了解可以使用 CTRL + 數字鍵可以快速的把數個字加入自訂詞庫，
但是反過來想要管理某些不想要的詞彙時，
需要進入設定頁面，
看到上千個詞彙時，總覺得難以管理。

不知道是否可以請求以 組合鍵 快速 刪除 在自訂詞庫中的 數個字 的功能呢？

附註：不知道是否有方法可以把自己的EMAIL地址加入特殊符號表，
或是某種組合鍵，因為個人使用的EMAIL地址很長，碼字的速度又慢....。

**Comment by leorlf2h** [comment]
不好意思，剛才發現 #617 有類似的請求
