### ISSUE TITLE
輸入法無法在HackMD使用搜尋

### ISSUE THREAD

**Issue by LambertWSJ** [EasyIME/PIME#631]
在HackMD中用新酷音輸入完關鍵字按Enter後只會重整頁面不會搜尋，但換成漢語就可以搜尋

OS: Ubuntu 20.04
Browser: 1.22.71 Chromium: 89.0.4389.114 (正式版本) (64 位元)

**Comment by ottokang** [comment]
應該是瀏覽器的問題，偶爾會這樣
