### ISSUE TITLE
Python 3有漏洞，有考慮更新版本嗎

### ISSUE THREAD

**Issue by HPEACE** [EasyIME/PIME#635]
最近Python暴有漏洞
https://www.bleepingcomputer.com/news/security/python-also-impacted-by-critical-ip-address-validation-vulnerability/
有考慮更新版本嗎？
另，如果要自行從Python官網下載更新的話可以嗎？應該怎麼做

**Comment by ottokang** [comment]
下一個版本會更新，近期在測試更新的 Python 版本

**Comment by ottokang** [comment]
已經更新 Python 版本
