### ISSUE TITLE
長期以來選字邏輯問題未改善

### ISSUE THREAD

**Issue by morganpan1203** [EasyIME/PIME#636]
新酷音輸入法相當好用，我支持了大約6年。
但是有一個顯而易見的選字邏輯，有待加強卻一直沒有改動。
就是當我從句子的最末往前移動，修改第n個字，沒想到第n-1個之前的字卻會改變。理論上，自句末移動到第n個字修改，代表從第1至第n-1個字都是正確的（不然我應該繼續往左移動選字），但程式長期以來仍然因為我改了第n個字，有可能改變第1至第、n-1個字，因而增加選字次數。

**Comment by morganpan1203** [comment]
我自己補充說明好了，比如我現在要打酒駕這個詞。
新酷音本來出現的詞是「酒架」，因為第一個字是對的，第二個字是錯的，所以只需要改第二個字。
但是當我把第二個字從架改成駕，軟體居然自動把第一個自也從酒改成久。
邏輯上我只改第二個字（架）就代表第一個字（酒）是對的，不應允許軟體自行修改第一個字（酒變久）。

**Comment by Hthrh** [comment]
Same here! 而且有時改來改去甚至突然當掉不能輸入中文，要把應用程式關掉重開

**Comment by yijr22** [comment]
對啊，這個智慧選字功能真的超級爛
反而用舊注音的輸入方式才更好

**Comment by RJHsiao** [comment]
> 對啊，這個智慧選字功能真的超級爛
> 反而用舊注音的輸入方式才更好

這跟選字邏輯有關係嗎？因為選字邏輯不好乾脆放棄選字？
你還是回到你原本的 Issue #645 去討論吧...或著說你回去用「舊」注音輸入法就好了吧
