### ISSUE TITLE
新酷音輸入法PIME在LINE對話視窗中無法正確學習字詞

### ISSUE THREAD

**Issue by howlmcastle** [EasyIME/PIME#637]
新酷音輸入法PIME 1.3.0-beta在LINE WINDOWS電腦版對話視窗中無法正確學習字詞
學習3個字以下 使用 CTRL+1, 2, 3 的方式
但剛好與LINE WINDOWS電腦版內建的快捷鍵一樣
導致被切換到LINE預設的動作（好友、聊天、加入好友 頁籤）
且沒有學習到 文字也沒有輸入成功
謝謝

**Comment by ottokang** [comment]
這個沒辦法解決，Windows 版 Line 他快速鍵就是這樣，除非之後 Line 有提供快速鍵更改功能
