### ISSUE TITLE
Windows 20H2有時注音輸入無反應

### ISSUE THREAD

**Issue by AlexOuO** [EasyIME/PIME#644]
OS: Windows 20H2
狀況：
切換到新酷音注音輸入法
打不出字
要關閉程式，並且Restart PIME Launcher 才解決

軟體：微軟記事本Notepad 以及Office 2016 standard ( Word, Powerpoint )

**Comment by ottokang** [comment]
偶發性會這樣，目前還沒找到原因，可能是底層 libIME2 的問題。

**Comment by AlexOuO** [comment]
> 偶發性會這樣，目前還沒找到原因，可能是底層 libIME2 的問題。

是的，偶而會發生。
但最近已有一段時間沒發生了。2021年12月 回想記憶應該沒發生過
我在2021/12/29 安裝新版1.3.0 beta2 後到今天2022/1/10也沒發生。
Windows 10 20H2 更新都有安裝
Office 2016 Standard 更新都有安裝
