### ISSUE TITLE
要求新酷音增加舊注音輸入方式

### ISSUE THREAD

**Issue by yijr22** [EasyIME/PIME#645]

**Comment by RJHsiao** [comment]
那你怎麼不用「舊」注音輸入法就好？
你會要求讓 Gogoro 可以加汽油作燃料嗎？

**Comment by yijr22** [comment]
> 那你怎麼不用「舊」注音輸入法？
> 你會要求讓 Gogoro 可以加汽油作燃料嗎？
> 你怎麼不去要求嘸蝦米輸入法要增加「舊」注音輸入方式？

通通都你對，只有你是絕頂天才

**Comment by RJHsiao** [comment]
@yijr22 
看來這個例子太深奧了你看不懂，雖然大部分的人應該都能看懂才是
我換個更淺顯的例子好了：
你會要求原子筆能跟鉛筆一樣用普通橡皮擦就能輕鬆擦除而不會嚴重傷害書寫面？那你怎麼不直接用鉛筆寫就好？
希望這個有助於降低你去理解你最根本的問題在哪裡

當然，如果 PCMan 願意多此一舉的為你加一個其實 Windows 內建就有的輸入法那真是再好不過了
不過我相信大部分的人應該寧可他把經歷用在改善輸入法的體驗及穩定度，例如你也回過得那個 Issue #636

**Comment by yijr22** [comment]
> 看來這兩個用來類比所舉的例子太深奧了你看不懂，雖然大部分的人應該都能看懂才是
> 我換個更淺顯的例子好了：
> 你會要求原子筆能跟鉛筆一樣用普通橡皮擦就能輕鬆擦除而不會嚴重傷害書寫面？那你怎麼不直接用鉛筆寫就好？
> 希望這個有助於降低你去理解你最根本的問題在哪裡

看來這用來類比所舉的例子太深奧了你看不懂，雖然大部分的人應該都能看懂才是
我換個更淺顯的例子好了：
你認為硬體原子筆不能跟硬體鉛筆一樣用普通橡皮擦就能輕鬆擦除而不會嚴重傷害書寫面
我認為軟體可以比硬體更能設計出用普通橡皮擦就能輕鬆擦除兩者而不會嚴重傷害書寫面
既然你對硬體這麼瞭解，那你怎麼不直接用實體筆寫就好，幹麻還用虛擬的軟體
希望這個有助於降低你這位天才去理解你最根本的問題在哪裡

**Comment by RJHsiao** [comment]
XDD
這類比不行啦...
感謝你認定我是比你厲害的天才，不過就客觀層面來說我只是一個比你厲害的普通人XD
