### ISSUE TITLE
希望可改善詞庫的UI

### ISSUE THREAD

**Issue by kuroutaakatsuki** [EasyIME/PIME#647]
目前新酷音輸入法開啟「編輯使用者詞庫」遇到的最大問題，就是需要仰賴瀏覽器開啟。
且開啟時間大約15～20秒，甚至容易遇到載入不成功的狀況。

以前曾經希望可以增加刪除詞彙的快捷鍵。
但用久了才發現希望這功能出現，根本的問題就是因為詞庫的開啟問題，影響到刪除錯詞的便利性。

最近為了解決這問題，直接找程式開sqlite3檔，再Restart PIME會更快速方便。
也更加感受到詞庫開啟問題現狀的遺憾。

還有，關於詞庫的部份，希望可以考慮有「使用者自訂」、「自然語言」等分類。
目前新酷音有強大的記憶功能，但也容易記錄到錯誤的詞彙。
覺得有個分類可能會比較方便編輯。
開sqlite3後可發現有user_freq、max_freq、orig_freq等參數，似乎有辦法直接對應分類？

以上一點使用上的淺見。
再次非常感謝團隊更新新酷音。
雖然不懂寫程式，但詞庫有點像在養自己的數據庫，覺得非常有趣。

**Comment by ottokang** [comment]
開啟緩慢主要是因為瀏覽器要把SQLite檔案讀取後繪製出來，上萬個表格列要繪製加減都要一點時間

**Comment by kuroutaakatsuki** [comment]
感謝解說。
解決這問題可能不仰賴瀏覽器獨立出來比較好。
不然就是先用編輯軟體代替了。

**Comment by ottokang** [comment]
好的，我再看看能否最佳化，目前時間花最多的都是在繪製部份

**Comment by kuroutaakatsuki** [comment]
感謝更新。

目前測試的狀況↓

環境：
AMD Ryzen 5 3600
Vivaldi
47267 個詞彙

user_phrase_editor.html 、 js/user_phrase.js 、 css/user_phrase.css
只編輯or複製這三個檔案，有看到UI變動，但沒辦法正常載入及點選選項。

user_phrase_editor.html 、 js 、 css
把js、css兩個資料夾全部丟過去，有動作。
讀取速度從平均16秒減少到10秒。
不過「刪除選擇詞彙」跟「匯入詞彙」等選項點選會有嚴重延遲的況狀。

**Comment by ottokang** [comment]
抱歉應該是替換 js、css 目錄，跟 user_phrase_editor.html 檔案。

剛測試一下，Blink 基礎的瀏覽器的確反應比較慢，初步調查是 Sweetalert2 緩慢的問題，我再看看能不能解決，不能解決就是換回原本瀏覽器內建的警告訊息來處理效能問題。

**Comment by ottokang** [comment]
> 「刪除選取詞彙（3）」 ← 選取的數字好像偶爾會有不正確的情況。

這個找到原因了，近期會修復

**Comment by markwu** [comment]
請問會 build 新的 release 嗎？

**Comment by ottokang** [comment]
> 
> 
> 請問會 build 新的 release 嗎？

有請 @PCMan  幫忙了，之後應該會有
