### ISSUE TITLE
無法在數字鍵台輸入全形字

### ISSUE THREAD

**Issue by 1abcd** [EasyIME/PIME#65]
輸入法使用全形字輸入，在鍵盤右方數字鍵台只能輸入半形字
像是　0.123456789/*-+
新注音可打出 ０．１２３４５６７８９／＊－＋

![default](https://cloud.githubusercontent.com/assets/1331388/14070447/2ceb3cf0-f4d9-11e5-8774-5d71a8d69416.png)

**Comment by KenLuoTW** [comment]
鍵盤右方數字鍵盤，新酷音目前預設不處理。

**Comment by PCMan** [comment]
這是故意設計的
