### ISSUE TITLE
舊注音與酷音注音排序問題?

### ISSUE THREAD

**Issue by YWH-magura** [EasyIME/PIME#657]
輸入都這字時在舊注音會是第一個字,但用酷音注音第一個會是"兜",第二個才是"都"
這是哪邊需要調整嗎?

**Comment by ottokang** [comment]
可以到使用者詞庫，把「兜」刪掉，應該就會回到預設的順序

**Comment by YWH-magura** [comment]
您好
後來我在碼表設定中將輸入法碼表中改成傳統注音,看來排序問題就正常了
