### ISSUE TITLE
執行安裝檔時，無法成功「自動下載並安裝微軟 VC++ 2015 runtime」

### ISSUE THREAD

**Issue by jonz94** [EasyIME/PIME#669]
### 描述錯誤

安裝檔有一個步驟是「自動下載並安裝微軟 VC++ 2015 runtime」的功能，但目前此功能似乎無法正常運作

### 重現步驟

1. 在剛灌完的全新 Windows 環境下，執行安裝檔，安裝過程能確實偵測到當前環境缺少「微軟 VC++ 2015 runtime」

![vc-bug-1](https://user-images.githubusercontent.com/16042676/147387099-76eb0436-03ef-4ae0-9eea-8a850e786868.png)

2. 點擊步驟一對話框中的「是」後，畫面會一直停留在「Connecting...」

![vc-bug-2](https://user-images.githubusercontent.com/16042676/147387273-6e3614fc-8430-48cd-bbe2-d067caa0d14c.png)

3. 最後會跳出以下安裝失敗的錯誤訊息

![vc-bug-3](https://user-images.githubusercontent.com/16042676/147387313-444bd34d-e242-4253-83cf-a9e7b1c707e4.png)

### 預期行為

安裝檔能成功「自動下載並安裝微軟 VC++ 2015 runtime」，最後順利成功安裝 PIME

### 作業系統

Windows 10 21H2

### PIME 版本

1.3.0-beta.2

**Comment by sppmg** [comment]
手動安裝 `latest-supported-vc-redist` 也是無法偵測到 runtime library

https://docs.microsoft.com/zh-tw/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by jonz94** [comment]
> 手動安裝 `latest-supported-vc-redist` 也是無法偵測到 runtime library
> 
> https://docs.microsoft.com/zh-tw/cpp/windows/latest-supported-vc-redist?view=msvc-170

@sppmg 我剛剛測試了一下，結果還蠻玄的＠＠

如果安裝的是 x86 版本的 VC++ 2015-2022 Redistributable，PIME 安裝檔會符合預期、正確偵測到 runtime library、並且成功完成安裝；但是如果安裝的是 x64 版本的 VC++ 2015-2022 Redistributable，就會遇到跟你一樣的情況，似乎是因為 PIME 安裝檔無法偵測到 x64 版本的 runtime library...

你那邊電腦上所安裝的 VC++ 2015-2022 Redistributable 版本應該是 x64 版本吧？

**Comment by sppmg** [comment]
沒錯，我是裝 x64 版本。
（竟然有這樣差別！或許是 PIME 偵測方式的問題？）

jonz94 ***@***.***> 於 2021年12月26日 週日 下午6:05 寫道：

**Comment by sppmg** [comment]
latest-supported-vc-redist  x64 OL/&�>0�� issue?
