### ISSUE TITLE
0.12版導致excel 2013 x64開啟緩慢

### ISSUE THREAD

**Issue by Aaron9999** [EasyIME/PIME#67]
裝了0.12版後，點excel文件直接開啟，會停頓很久才開啟
先開啟excel，再開啟其他excel就正常

**Comment by THEOLIN** [comment]
我這邊也有發現同樣的問題。
win7 64bit，excel是2010版32bit。
感覺是按下excel按鈕啟動時的啟動畫面變成延遲很久才出現，但是啟動畫面一出現的瞬間，試算表就會跑出來變成可用狀態。
已經有一個excel視窗存在的情況下，開啟第二個以後的excel視窗就沒這種情形。

**Comment by Angus45** [comment]
我也是同樣狀況
環境如下
Windows 10 x64
Office 2016 x64

**Comment by ottokang** [comment]
有這個問題+1，Windows 7 x64 + Office 2016 x64 or Office 2013 x64 皆然

**Comment by THEOLIN** [comment]
類似問題發生在Office 2007的**Word 2007**和Excel 2007
OS: Win7 64bit

**Comment by PCMan** [comment]
請問是有設定成預設輸入法嗎？

**Comment by ottokang** [comment]
沒有，只要安裝PIME就會有這個狀況，Windows 10跟Windows 7都有這個情形，開啟Excel異常的慢，用TSF版本就沒這個問題

**Comment by PCMan** [comment]
confirmed.
看起來跟 PIME Launcher 有關，詳細原因待查

**Comment by PCMan** [comment]
找到問題並且已經在 git 修正，下一版就會好了
但我懷疑這是 Windows 系統核心的 bug
MsgWaitForMultipleObjects() API 沒有實作正確
