### ISSUE TITLE
PIME-1.3.0-beta2的設定畫面無法正常顯現

### ISSUE THREAD

**Issue by scju** [EasyIME/PIME#678]
PIME-1.3.0-beta2安裝好了之後，進入設定畫面，但內容卻無法完整顯示。

對比PIME-1.1.0-setup的安裝過程，發現1.1.0版一開始有提醒是否關閉「IE保護模式」，選擇關閉之後，安裝完成，設定畫面是正常的。因此我推測是不是這裡有影響？因為PIME-1.3.0-beta2沒跳出讓我們可以關閉「IE保護模式」的提示。

系統：Windows 10 21H2

**Comment by jonz94** [comment]
關於安裝過程中沒有關閉「IE 保護模式」的提示，其實是因為在 [測試版本 v1.3.0-alpha2](https://github.com/EasyIME/PIME/releases/tag/v1.3.0-alpha2) 時（2020年四月），PIME 輸入法已經可以在「不須關閉保護模式」的情況下正常使用了～所以往後的版本在安裝過程中，沒跳出關閉「IE 保護模式」的提示是屬於正常情形。

不過我自己在開發測試時，確實偶爾會遇到「在剛安裝好 PIME 輸入法時，**第一次** 進入設定畫面，選項是空白的」情況發生，但是我這邊的情況是只有 **第一次** 進入設定畫面才會有問題，如果用 <kbd>F5</kbd> 重新整理頁面或是關掉設定畫面再重新進入，就又恢復正常了。

不知道我遇到的情況跟你遇到的是不是相同？
另外想知道一下你有安裝了哪些輸入法？

**Comment by scju** [comment]
> 關於安裝過程中沒有關閉「IE 保護模式」的提示，其實是因為在 [測試版本 v1.3.0-alpha2](https://github.com/EasyIME/PIME/releases/tag/v1.3.0-alpha2) 時（2020年四月），PIME 輸入法已經可以在「不須關閉保護模式」的情況下正常使用了～所以往後的版本在安裝過程中，沒跳出關閉「IE 保護模式」的提示是屬於正常情形。
> 
> 不過我自己在開發測試時，確實偶爾會遇到「在剛安裝好 PIME 輸入法時，**第一次** 進入設定畫面，選項是空白的」情況發生，但是我這邊的情況是只有 **第一次** 進入設定畫面才會有問題，如果用 F5 重新整理頁面或是關掉設定畫面再重新進入，就又恢復正常了。
> 
您好，後來找到問題原因了，是因為網頁瀏覽器的預設程式。我之前是預設為IE10，設定畫面就無法正常顯示，現在改成Edge或Chrome，設定畫面就正常了。

**Comment by jonz94** [comment]
原來是 IE 的部份 😂

**Comment by ottokang** [comment]
目前設定、詞庫編輯已經不支援 IE，請改用其他瀏覽器
