### ISSUE TITLE
刪除詞彙後還是存在

### ISSUE THREAD

**Issue by Akira0196** [EasyIME/PIME#692]
不管是使用ctrl+del或是直接去使用者圖庫刪除
刪完後的單字都還是會存在 只有偶爾才會消失在選字處
![image](https://user-images.githubusercontent.com/97196486/153124405-572af56f-f5f0-48a1-a2da-3c0ad6b98a17.png)
![image](https://user-images.githubusercontent.com/97196486/153124471-230d0c4f-d2f1-4a2f-968c-28959d8e9a87.png)
![image](https://user-images.githubusercontent.com/97196486/153124504-caa47caf-ae4a-459e-99a1-ccb5903f8910.png)
![image](https://user-images.githubusercontent.com/97196486/153124524-930feaf9-3611-4941-9e00-14c45f3294a5.png)
請問這個有辦法處理嗎？
感謝！

**Comment by kuroutaakatsuki** [comment]
因為這是內建的基本詞庫。
刪除可以重製優先順序參數，但沒辦法刪掉。

**Comment by ottokang** [comment]
內建的詞庫無法用 Ctrl + Del 刪除
