### ISSUE TITLE
已設定按住Shift輸出英文大寫字母，但仍然出現標點符號。

### ISSUE THREAD

**Issue by usagi75** [EasyIME/PIME#693]
似乎PIME從0.12以來就一直有這樣的問題，所以之前都還在用win32-chewing-0.3.4.8，
但升級win11後0.3.4.8就不能用了，現在裝PIME-1.3.0-beta2一樣有這種情況。

另外希望按下無法組字的注音符號時（如 ˇ ˊ ˋ ㄎ）按空白鍵可跟微軟注音一樣能直接輸入空格（不必先確認選字後才得以鍵入）。

![image](https://user-images.githubusercontent.com/22858621/154787906-c7cf2b0d-c2c0-40a8-9c15-68967d5dafdd.png)

**Comment by ottokang** [comment]
測試不出來有這樣的狀況，可以的話提供測試步驟

**Comment by Fred00231** [comment]
我也有遇到這個問題(1.3.0-beta2)，在中文輸入的情況下，無論「按住Shift輸出全形標點符號」和「按住Shift輸出英文大寫字母」兩個選項如何勾選，按住Shift都只會輸出全形標點符號。

**Comment by ottokang** [comment]
> 我也有遇到這個問題(1.3.0-beta2)，在中文輸入的情況下，無論「按住Shift輸出全形標點符號」和「按住Shift輸出英文大寫字母」兩個選項如何勾選，按住Shift都只會輸出全形標點符號。

如果重啟 PIME 後會正常作用嗎？

**Comment by Fred00231** [comment]
重起之後就可以順利在中文模式下按住Shift輸出英文大寫字母了，感謝。
