### ISSUE TITLE
Windows 7玩天堂2.70的時候PIME-1.1.0 大新倉頡打字的時候 會出現 要多按一次shift 再按enter才能正常出字

### ISSUE THREAD

**Issue by wsx710909** [EasyIME/PIME#694]
剛開始不會
可是使用一段期間之後就會出現這個情形
必須卸載PIME-1.1.0 重開機之後再安裝PIME-1.1.0
打字才能正常按enter出字
有誰知道怎麼解決嗎

**Comment by kuroutaakatsuki** [comment]
有問題時，先右下角找PIME Launcher右鍵Restart PIME試試看？
![スクショ 2022-02-22 09-03-36](https://user-images.githubusercontent.com/56618015/155044775-30d3326c-016f-4fe7-872e-26eea16cfb37.jpg)
![スクショ 2022-02-22 09-03-54](https://user-images.githubusercontent.com/56618015/155044790-7cd38a0a-e3c2-408f-894e-9a4ddfb105df.jpg)

**Comment by wsx710909** [comment]
> 有問題時，先右下角找PIME Launcher右鍵Restart PIME試試看？ ![スクショ 2022-02-22 09-03-36](https://user-images.githubusercontent.com/56618015/155044775-30d3326c-016f-4fe7-872e-26eea16cfb37.jpg) ![スクショ 2022-02-22 09-05-41](https://user-images.githubusercontent.com/56618015/155044844-816be937-a8b4-4755-bf25-8a66df9aa973.jpg) ![スクショ 2022-02-22 09-03-54](https://user-images.githubusercontent.com/56618015/155044790-7cd38a0a-e3c2-408f-894e-9a4ddfb105df.jpg)

請問圖中PIME輸入法版本是多少的？

**Comment by kuroutaakatsuki** [comment]
我現在是用最新的版本1.3.0-beta2。
可藉由Restart PIME Launcher來解決動作問題應該好幾個版本前就有了。

**Comment by wsx710909** [comment]
> 有問題時，先右下角找PIME Launcher右鍵Restart PIME試試看？ ![スクショ 2022-02-22 09-03-36](https://user-images.githubusercontent.com/56618015/155044775-30d3326c-016f-4fe7-872e-26eea16cfb37.jpg) ![スクショ 2022-02-22 09-05-41](https://user-images.githubusercontent.com/56618015/155044844-816be937-a8b4-4755-bf25-8a66df9aa973.jpg) ![スクショ 2022-02-22 09-03-54](https://user-images.githubusercontent.com/56618015/155044790-7cd38a0a-e3c2-408f-894e-9a4ddfb105df.jpg) 我是WIN7用戶 你說的解決方法 WIN7右下方沒有你說的畫面 我放棄PIME了

**Comment by wsx710909** [comment]
> > 有問題時，先右下角找PIME Launcher右鍵Restart PIME試試看？ ![スクショ 2022-02-22 09-03-36](https://user-images.githubusercontent.com/56618015/155044775-30d3326c-016f-4fe7-872e-26eea16cfb37.jpg) ![スクショ 2022-02-22 09-05-41](https://user-images.githubusercontent.com/56618015/155044844-816be937-a8b4-4755-bf25-8a66df9aa973.jpg) ![スクショ 2022-02-22 09-03-54](https://user-images.githubusercontent.com/56618015/155044790-7cd38a0a-e3c2-408f-894e-9a4ddfb105df.jpg) 我是WIN7用戶 你說的解決方法 WIN7右下方沒有你說的畫面 我放棄PIME了
而且之前我關了很了WIN7不必要的服務 才開始出現我說的問題(因為服務不關 硬碟常常會一直瘋狂讀取 玩天堂會卡頓) 可是我不想重來一次了 我好好使用奇摩輸入法吧




Offline Files
Peer Name Resolution Protocol
Peer Networking Grouping
Peer Networking Identity Manager
PnP-X IP Bus Enumerator
Problem Reports and Solutions Control Panel Support

PuranDefrag
Quality Windows Audio Video Experience
Remote Desktop Configuration
Remote Desktop Services
Remote Desktop Services UserMode Port Redirector
Remote Registry
Routing and Remote Access
Security Center
SNMP Trap
SSDP Discovery
Superfetch
Tablet PC Input Service
TCP/IP NetBIOS Helper

Virtual Disk
Volume Shadow Copy
Windows Backup
Windows Biometric Service
Windows Connect Now - Config Registrar
Windows Defender
Windows Error Reporting Service
Windows Image Acquisition (WIA)
Windows Media Center Receiver Service
Windows Media Center Scheduler Service


Windows Search
Windows Time
Windows Update
WinHTTP Web Proxy Auto-Discovery Service
WMI Performance Adapter
家長監護

**Comment by wsx710909** [comment]
> > > 有問題時，先右下角找PIME Launcher右鍵Restart PIME試試看？ ![スクショ 2022-02-22 09-03-36](https://user-images.githubusercontent.com/56618015/155044775-30d3326c-016f-4fe7-872e-26eea16cfb37.jpg) ![スクショ 2022-02-22 09-05-41](https://user-images.githubusercontent.com/56618015/155044844-816be937-a8b4-4755-bf25-8a66df9aa973.jpg) ![スクショ 2022-02-22 09-03-54](https://user-images.githubusercontent.com/56618015/155044790-7cd38a0a-e3c2-408f-894e-9a4ddfb105df.jpg) 我是WIN7用戶 你說的解決方法 WIN7右下方沒有你說的畫面 我放棄PIME了
> > > 而且之前我關了很了WIN7不必要的服務 才開始出現我說的問題(因為服務不關 硬碟常常會一直瘋狂讀取 玩天堂會卡頓) 可是我不想重來一次了 我好好使用奇摩輸入法吧
> 
> Offline Files Peer Name Resolution Protocol Peer Networking Grouping Peer Networking Identity Manager PnP-X IP Bus Enumerator Problem Reports and Solutions Control Panel Support
> 
> PuranDefrag Quality Windows Audio Video Experience Remote Desktop Configuration Remote Desktop Services Remote Desktop Services UserMode Port Redirector Remote Registry Routing and Remote Access Security Center SNMP Trap SSDP Discovery Superfetch Tablet PC Input Service TCP/IP NetBIOS Helper
> 
> Virtual Disk Volume Shadow Copy Windows Backup Windows Biometric Service Windows Connect Now - Config Registrar Windows Defender Windows Error Reporting Service Windows Image Acquisition (WIA) Windows Media Center Receiver Service Windows Media Center Scheduler Service
> 
> Windows Search Windows Time Windows Update WinHTTP Web Proxy Auto-Discovery Service WMI Performance Adapter 家長監護

這些是我研究出來可以關的服務

**Comment by kuroutaakatsuki** [comment]
我公司電腦也是用WIN7，一樣可以用同樣方法解決啊....。
而且截圖就是在公司截的，所以是WIN7。

**Comment by wsx710909** [comment]
> IME試試

我曾經叫出工作管理員 關了PIME 再重新打開 問題依舊存在 這些問題是我把大量WIN7服務關閉以後才開始這樣的
之前只會中文鎖死 叫出工作管理員 關了PIME 再重新打開 就可以了
可是PIME最麻煩的就是會不定時 無預警的出現這個問題 所以不用了
奇摩輸入法已經使用了好幾天 不會出現打不出中文 PIMEJ輸入法我放棄了

**Comment by RJHsiao** [comment]
好喔，感謝你特地註冊帳號回報 bug
你說的問題可能在 1.3.0-beta2 就解了，就算沒解也有樓上說的可以 Restart PIME 來處理
所以我沒辦法明白你遭遇了什麼問題必須停在已經釋出好幾年的 1.1.0 版，可能是非正式版不用吧
不過看來你已經找到你的最愛了，那就恭喜你了
我看你也不是真的有問題需要人家幫你解決，你實在不需要浪費時間一直在這邊亂開 issue 洗版

在開源軟體社群內，想要回報問題並讓開發者能迅速修復
首先你要清楚有邏輯的描述問題，交待一下你的電腦環境，列出能重現問題的操作步驟，並附上 log (如果有的話)
而且要把這些資訊稍微整理成具有可讀性，便於閱讀的形式，例如修正錯字、補上標點符號之類的
畢竟不是商業軟體，你沒付錢買軟體所以你當不成大爺，
開發者沒跟你收錢所以沒辦法靠這個養活自己，所以勢必還有其他會有錢拿的事情必須優先處理
開發者沒有時間跟你一一確認你的狀況、花時間去建構出你出問題時的相同環境並重現你的問題，
所以我們這些使用者必須自己先準備一些材料，開發者才有辦法在所剩不多的的零碎時間內快速的找出問題點並加以解決
不讓馬兒吃草又要讓馬兒跑得飛快是很不現實的一件事，你希望馬兒跑得飛快，把馬兒餵飽是基本的
以開源軟體來說，
你要不就是捐錢，甚至是付費讓開發者排除其他事情專心幫你修 bug 做 feature
你要不就是成為前期試用者，努力抓 bug 並提交詳盡報告
你要不就是直接加入開發，貢獻你的心力
要是都做不到，至少就是一般使用，發現 bug 後盡可能的附上問題發生時的使用情境及環境、再現操作流程，以及系統及/或軟體的 log，並注意內容的可讀性
你若沒辦法好好的回報 bug，就像現在這個樣子，大喊著「有 Bug 有 Bug！」但什麼資訊也沒提供，
人家跟你說有新版可以試試你也不試，
開發者根本不知道你的問題在哪，且看起來你完全有打算好好的配合調查，那就只好先把時間用在處理更有價值或是更有辦法處理的事情了

不過看起來 Yahoo!奇摩輸入法可能比較適合你，PIME 不太適合你，那就先恭喜你了
雖然 Yahoo!奇摩輸入法已經是10年前的產物且已經不維護了，有開源但後續似乎沒人接手改善，
不過畢竟是台灣雅虎當年花了人力物力打造，穩定性自然是不用多說的，當年可是有為數眾多的內外部測試者呢～
相信跟不維護的 Win7 一樣，可以再戰10年！

最後還是不免俗的附上兩篇文章給新進的開源專案參與者閱讀，大家共勉之
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way
https://blog.brownsugar.tw/the-art-of-asking/

P.S. 大量開 issue 洗版不會讓你的問題被重視，只會被當成到處撒野的小粉紅或是垃圾帳號
對於解決問題沒有任何幫助之外，還會對你帳號(在大家心中)的信用評分造成嚴重影響，
進而導致大家看到發問者是你就會直接略過
請知悉
