### ISSUE TITLE
套用符號設定會喪失原有設定

### ISSUE THREAD

**Issue by XDTZ** [EasyIME/PIME#695]
修改後一按下「套用設定」，原本的符號就全部不見了
![2022-02-28](https://user-images.githubusercontent.com/9079219/156180956-220e0d19-82c9-45de-a7ea-cd711b6cc2f6.png)

**Comment by ottokang** [comment]
重新貼上一次，再套用設定看看

**Comment by ottokang** [comment]
和 #706 重複
