### ISSUE TITLE
我已經改用奇摩輸入法 打 大新倉頡了 雖然打字框會亂飄 但是大問題幾乎是沒有

### ISSUE THREAD

**Issue by wsx710909** [EasyIME/PIME#697]
https://graysyu.pixnet.net/blog/post/295244148-win7%E5%B9%B3%E5%8F%B0%E4%B8%8A%EF%BC%8C%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E5%A4%A7%E6%96%B0%E5%80%89%E9%A0%A1sop%EF%BC%81part2-%28win10 常用字分號選字 不能分號選字的用右方數字鍵選字 不會出現一大堆不可預期的問題 玩天堂跟盟友打王時 PIME輸入法突然出現不能打字 無法好好配合盟友 被罵死了
奇摩輸入法在天堂無法正常顯示打字框 可是對 大新倉頡用戶 幾乎沒影響

**Comment by bitterysz** [comment]
大哥，大家都很願意協助你，也有一定的好奇心「想知道什麼狀況」？
但你這樣子表達，誰看的懂？

我來補充說明

我本人是「大新」的使用者，目前要在win7~win11
以及mac系統打「大新」（除了等開發商～良心發現更新）
不然就只能用PIME與Yahoo輸入。

Yahoo有輸入框跑到營幕外的問題（本人是資訊系的，知道怎麼解決）
PIME有死當的問題（這個要仰賴製作、協作者更改）

PIME的死當問題，最讓人困擾。
只能重新開機處理。

但很遺憾的是，Yahoo也會死當。
這二個輸入法會死當的原因，100%是因為系統過載。
在CPU與記憶體一樣使用量的情況下「切換輸入法」。
導致死當。

平常逛網頁、寫文書、打稿時都很「正常」
玩遊戲的人最常碰到這件事情。

死當還有分二種，但我認為原因是相當的。
1.小當：無法輸入，但PIME還在。
2.死當：整個PIME當掉，無法重啟。( 除非你去taskmgr.exe，強制K掉）

建議「製作者、協作者」
如果你們有能力，先照我說的實驗看看，看能不能解決。
當「使用者切換PIME輸入法」時，預載時間「大於2秒」
或「CPU、記憶體使用量處於高峰」時。

1.延緩切換 
( 十十人十 ni Mother！！Microsft有個職業工程師都知道的問題！不
能在2秒內執行超過5個以上的程式，
他們作業系統與硬體CPU、記憶體架構的溝通SOP很不友善。
我以前學生時代學VisualBasic就很常碰到，
明明程式就沒打錯字，還一直出BUG，搞到我TIMER都是0.1秒去延著跑。
 十十人十 ni Mother！！講十遍！）

#怪不得3D設計師都要往MAC跑，誰能接受跑圖跑一半死當。
用Microsoft跑高負載率的東西，根本自找苦吃。

2. 判斷後自動重啟
（我認為這個不太可能，我沒聽說過在輸入法裡
鑲一個「獨立於程式」外的監控程式，監控PIME是否正常執行。

我沒有學C++、Python
所以我也不知道有哪些函式可以用
哪些函式可以調用微軟DLL
這3個合計要看超過2000頁原文書的
偉大任務就交給其它人處理了。

**Comment by wsx710909** [comment]
> 大哥，大家都很願意協助你，也有一定的好奇心「想知道什麼狀況」？ 但你這樣子表達，誰看的懂？
> 
> 我來補充說明
> 
> 我本人是「大新」的使用者，目前要在win7~win11 以及mac系統打「大新」（除了等開發商～良心發現更新） 不然就只能用PIME與Yahoo輸入。
> 
> Yahoo有輸入框跑到營幕外的問題（本人是資訊系的，知道怎麼解決） PIME有死當的問題（這個要仰賴製作、協作者更改）
> 
> PIME的死當問題，最讓人困擾。 只能重新開機處理。
> 
> 但很遺憾的是，Yahoo也會死當。 這二個輸入法會死當的原因，100%是因為系統過載。 在CPU與記憶體一樣使用量的情況下「切換輸入法」。 導致死當。
> 
> 平常逛網頁、寫文書、打稿時都很「正常」 玩遊戲的人最常碰到這件事情。
> 
> 死當還有分二種，但我認為原因是相當的。 1.小當：無法輸入，但PIME還在。 2.死當：整個PIME當掉，無法重啟。( 除非你去taskmgr.exe，強制K掉）
> 
> 建議「製作者、協作者」 如果你們有能力，先照我說的實驗看看，看能不能解決。 當「使用者切換PIME輸入法」時，預載時間「大於2秒」 或「CPU、記憶體使用量處於高峰」時。
> 
> 1.延緩切換 ( 十十人十 ni Mother！！Microsft有個職業工程師都知道的問題！ 不能在2秒內執行超過5個以上的程式， 他們作業系統與硬體CPU、記憶體架構的溝通SOP很不友善。 20年來~ 他們內部工程師，從來就沒有人去解決。 我以前學生時代學VisualBasic就很常碰到， 明明程式就沒打錯字，還一直出BUG，搞到我TIMER都是0.1秒去延著跑。 然後就全部都很順，一切正常！眼精都要翻到外太空了。 十十人十 ni Mother！！講十遍！）
> 
> #怪不得3D設計師都要往MAC跑，誰能接受跑圖跑一半死當。 用Microsoft跑高負載率的東西，根本自找苦吃。
> 
> 2. 判斷後自動重啟
>    （我認為這個不太可能，我沒聽說過在輸入法裡
>    鑲一個「獨立於程式」外的監控程式，監控PIME是否正常執行。
> 
> 我沒有學C++、Python 所以我也不知道有哪些函式可以用 哪些函式可以調用微軟DLL 這3個合計要看超過2000頁原文書的 偉大任務就交給其它人處理了。

我把win7不必要的服務全關了 現在使用奇摩輸入法 完全不會死當 玩天堂私服 就是一個字 爽

**Comment by wsx710909** [comment]
> > 大哥，大家都很願意協助你，也有一定的好奇心「想知道什麼狀況」？ 但你這樣子表達，誰看的懂？
> > 我來補充說明
> > 我本人是「大新」的使用者，目前要在win7~win11 以及mac系統打「大新」（除了等開發商～良心發現更新） 不然就只能用PIME與Yahoo輸入。
> > Yahoo有輸入框跑到營幕外的問題（本人是資訊系的，知道怎麼解決） PIME有死當的問題（這個要仰賴製作、協作者更改）
> > PIME的死當問題，最讓人困擾。 只能重新開機處理。
> > 但很遺憾的是，Yahoo也會死當。 這二個輸入法會死當的原因，100%是因為系統過載。 在CPU與記憶體一樣使用量的情況下「切換輸入法」。 導致死當。
> > 平常逛網頁、寫文書、打稿時都很「正常」 玩遊戲的人最常碰到這件事情。
> > 死當還有分二種，但我認為原因是相當的。 1.小當：無法輸入，但PIME還在。 2.死當：整個PIME當掉，無法重啟。( 除非你去taskmgr.exe，強制K掉）
> > 建議「製作者、協作者」 如果你們有能力，先照我說的實驗看看，看能不能解決。 當「使用者切換PIME輸入法」時，預載時間「大於2秒」 或「CPU、記憶體使用量處於高峰」時。
> > 1.延緩切換 ( 十十人十 ni Mother！！Microsft有個職業工程師都知道的問題！ 不能在2秒內執行超過5個以上的程式， 他們作業系統與硬體CPU、記憶體架構的溝通SOP很不友善。 20年來~ 他們內部工程師，從來就沒有人去解決。 我以前學生時代學VisualBasic就很常碰到， 明明程式就沒打錯字，還一直出BUG，搞到我TIMER都是0.1秒去延著跑。 然後就全部都很順，一切正常！眼精都要翻到外太空了。 十十人十 ni Mother！！講十遍！）
> > #怪不得3D設計師都要往MAC跑，誰能接受跑圖跑一半死當。 用Microsoft跑高負載率的東西，根本自找苦吃。
> > 
> > 2. 判斷後自動重啟
> >    （我認為這個不太可能，我沒聽說過在輸入法裡
> >    鑲一個「獨立於程式」外的監控程式，監控PIME是否正常執行。
> > 
> > 我沒有學C++、Python 所以我也不知道有哪些函式可以用 哪些函式可以調用微軟DLL 這3個合計要看超過2000頁原文書的 偉大任務就交給其它人處理了。
> 
> 我把win7不必要的服務全關了 現在使用奇摩輸入法 完全不會死當 玩天堂私服 就是一個字 爽
xp vista時代 我自己買大新倉頡在使用 也不會出現死當情況
