### ISSUE TITLE
特殊符號最後一行沒留空白會被清空

### ISSUE THREAD

**Issue by Mike-WengCM** [EasyIME/PIME#706]
一開始特殊符號都正常
後來調整完順序，不知道是不是最後一行沒有留空白的關係，按下套用設定就跳出$("#symbols").val() 
再來就算刪掉$("#symbols").val() 這行，然後重新新增特殊符號，但按下`還是沒有任何符號，只有兩個空白可以選
如果這時候再次把剛剛新增的特殊符號全刪了並按下套用設定，那就會又看到$("#symbols").val() 
也不知道要怎麼重置或修正，等於是完全沒辦法使用特殊符號表的功能

作業系統是win10，開PIME設定的瀏覽器是Firefox，版本是PIME 1.3.0-beta2

_**6/6更新_
後來重裝新酷音+系統還原，總算可以新增標點符號並正常使用
只是一開始預設的特殊符號都沒了，進特殊符號設定那邊是從一片空白開始新增

**Comment by ottokang** [comment]
這邊測試的確是這樣，最後一行沒有空白會導致特殊符號整個被清空，會再修正這個問題

**Comment by ottokang** [comment]
Fix #708
