### ISSUE TITLE
可以修改 麼 的輸入模式嗎？

### ISSUE THREAD

**Issue by MotoChu** [EasyIME/PIME#712]
謝謝您們辛苦開發、維護與更新這麼好用的輸入法，但有一個問題是一直都困擾我，這麼多年了還是不習慣：
「可以把 『麼』 加入 ㄇㄛ. 這個注音裡嗎？」
什麼，已經講習慣 ㄇㄛ. ，但這麼多年下來，每次打什麼，都還是會因為打成 ㄇㄛ. 而停留在 蛇_
必須要重打成 ㄇㄜ. 才能順利輸入。
自然注音、奇摩注音、微軟注音，都有提供 ㄇㄛ. 可順利輸入 麼 這個字
真心期待這麼棒的酷音輸入法也能早日提供 麼ㄇㄛ. 的選項！！
謝謝您！

**Comment by yan12125** [comment]
新酷音字詞的讀音是由 libchewing 管理。之前有人提過類似問題，但沒有下文 https://github.com/chewing/libchewing/issues/227

**Comment by ottokang** [comment]
目前繁體「[麼](https://dict.mini.moe.edu.tw/SearchIndex/word_detail?wordID=D0000209&breadcrumbs=Search_%E9%BA%BC_one&dictSearchField=%E9%BA%BC)」標準注音就三種，ㄇㄛˊ、ㄇㄜ.、ㄇㄚˊ，基本上還是會照著官方注音去設定
