### ISSUE TITLE
關於安裝程式封裝與靜默安裝建議

### ISSUE THREAD

**Issue by syman888** [EasyIME/PIME#724]
HI 大家好

PIME這個輸入法程式真的很棒，尤其是可裝取代嘸蝦米輸入法的蝦米輸入法

在公司或是學校等單位應該都會很需要用到，在我們資訊單位的角度下

可能較常會需要用到大量部署或派送安裝，所以會有自動安裝(靜默安裝)的需求

目前NSIS封裝的安裝檔我查是有支援參數 /S  Silent installation，在此1.1.0與1.3.0-beta的版本安裝應該是沒有加入自動安裝(靜默安裝)該功能，在加參數 /S 或 /s 是沒有作用的

想建議未來是否可以加入自動安裝(靜默安裝)該功能，或改其他封裝安裝檔成msi檔，在自動安裝的指令下可以搭配下參數例如  /A 是安裝新酷音; /B 是安裝酷倉; /C 是安裝蝦米，蝦米若自備正版表格檔可用 /C file:c:\temp\liu.tab 指定檔案位置，之類的，停用IE受保護模式就 /DisableIEProtect  …等參數，達到可大量佈署安裝或自動化安裝的方法，讓更多有需要PIME輸入法的人可以更方便的安裝使用，謝謝大家！辛苦了

Ken Luo notifications@github.com 於 2016年3月21日 下午3:18 寫道：

> 我有弄了一個新的安裝程式，預設就是僅安裝新酷音，並且安裝後在語言選項裡即會顯示所裝的輸入法，如果須要的話，可以向我索取。
> 
> 修改後的 NSIS 腳本
> https://github.com/KenLuoTW/PIME/blob/thcj/installer/installer.nsi
> 
> [image: 2016-03-21]
> https://cloud.githubusercontent.com/assets/12954277/13912369/5170a928-ef77-11e5-82cf-72159951365d.png
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/EasyIME/PIME/issues/50#issuecomment-199152503

## 

Dark‧淡藍
http://www.dark.idv.tw
E-mail：darkakia@gmail.com
MSN：darkakia@hotmail.com

_Originally posted by @darkakia in https://github.com/EasyIME/PIME/issues/50#issuecomment-199304982_

**Comment by syman888** [comment]
了解，辛苦了！
目前自動安裝蝦米輸入法的部份我用AUTOIT是可以做到，未來希望有機會看到功能更強大的PIME輸入法
加油~  謝謝！

**Comment by ottokang** [comment]
PR 已經 Merge

**Comment by ottokang** [comment]
> > 目前NSIS封裝的安裝檔我查是有支援參數 /S Silent installation，在此1.1.0與1.3.0-beta的版本安裝應該是沒有加入自動安裝(靜默安裝)該功能，在加參數 /S 或 /s 是沒有作用的
> 
> 目前的安裝檔幾乎支援靜默安裝了。只要稍做修改，讓一些對話框不要出現，就達成靜默安裝了。我之前做了一個半成品，剛剛把他完成，提交到了 #726 。
> 
> > 在自動安裝的指令下可以搭配下參數例如 /A 是安裝新酷音; /B 是安裝酷倉; /C 是安裝蝦米，蝦米若自備正版表格檔可用 /C file:c:\temp\liu.tab 指定檔案位置，之類的，停用IE受保護模式就 /DisableIEProtect …等參數
> 
> 這一類功能似乎需要加上不少 code。我目前沒有這個需求，可能短期之內不會去實做。

已合併 PR，感謝
