### ISSUE TITLE
特殊符號設定無法正常反應

### ISSUE THREAD

**Issue by kuroutaakatsuki** [EasyIME/PIME#747]
想自訂設定但完全沒有反應，
有時候會出現「$("#symbols").val()」。

有試過完整刪除重灌，也沒辦法改善。
![スクショ 2022 12 11 13-44-07](https://user-images.githubusercontent.com/56618015/206887256-0c2c4b2b-7be7-4151-a711-acee8000e6b4.png)
![スクショ 2022 12 11 13-48-35](https://user-images.githubusercontent.com/56618015/206887259-5fe294af-7be1-4bff-833a-d730af847265.png)

**Comment by ottokang** [comment]
已經修正 #708 ，目前最後一行請記得留空白

**Comment by kuroutaakatsuki** [comment]
最後一行有空白也仍然無法套用內容。
![スクショ 2022 12 15 19-52-12](https://user-images.githubusercontent.com/56618015/207841088-1710e88d-aa6e-40f3-b583-df3868ece722.png)

**Comment by ottokang** [comment]
檢查一下 %APPDATA% \PIME\chewing\symbols.dat 這個檔案有沒有正確寫入，可以用記事本開啟

**Comment by kuroutaakatsuki** [comment]
symbols.dat檔案沒有問題。

界面會顯示套用成功，而實際使用是原始的狀態。

家用跟公司用電腦是用同一個symbols.dat檔案下去套用，
目前只有家中電腦遇到這個情況。
![Snipaste_2022-12-16_10-36-06](https://user-images.githubusercontent.com/56618015/208001895-366bff0c-90ea-482d-a566-4455498a491b.png)
