### ISSUE TITLE
希望能提高新增詞彙時的freq值跟手動調高的方式

### ISSUE THREAD

**Issue by kuroutaakatsuki** [EasyIME/PIME#754]
還是老問題，常常遇到新詞彙的freq值低過既有的少用詞彙，使得優先度要重複個8～9次才能排第一，甚至仍然改不過來。
主要原因還是因為新增詞彙時的freq值只有1而已。
「●●及●●」「●●和●●」等中間夾雜連接詞，「●●了」等語詞接「了」的情況，3～4個字的詞彙優先度遠低於2個字的詞彙的情況，
都會造成自動選字不理想的問題。

例如：
「世界盃」跟「世界」
由於「世界」的使用頻率通常高出很多，造成freq值較高，
而使得打整行字時，「世界盃」容易變成「世界背」、「運動員」變成「運動元」之類的。

「●●了」的優先度常常會低於「●了」，所以我都直接把freq設成5000。

自動學習的詞彙覺得還行，但主動加入的詞彙比較重要，應該初始值可以設個50甚至5000，
在「設定」那邊可以選擇這個值的大小可能也不錯。

另外，為了方便調整優先度，以「Crtl+數字」加入既有詞彙時，大幅提升freq值似乎也不錯。
利用刪除可以重製freq值的設定，就可以很方便的調整優先度。

用久了之後偶爾需要開sqlite3，把常用的詞彙直接調成20000左右，一些選字才不容易出錯，
覺得freq值的參數設計還有可以調校的空間。

**Comment by yan12125** [comment]
新酷音目前沒有提供指定頻率的方式，需要修改 libchewing 加入新的 API，或是修改 libchewing 的頻率更新邏輯。無論是哪種方式，都需要修改 libchewing。建議可以到 https://github.com/chewing/libchewing/ 討論。

https://github.com/EasyIME/PIME/issues/690, https://github.com/EasyIME/PIME/issues/713 也是類似的情況，需要修改 libchewing。
