### ISSUE TITLE
1.3.0-stable版的Ctrl+1似乎變成「特殊符號」

### ISSUE THREAD

**Issue by kuroutaakatsuki** [EasyIME/PIME#755]
原本Ctrl+1應該是「加入游標 前方/後方的字」，
1.3.0-stable版本變成「呼叫出符號表」。

**Comment by ottokang** [comment]
Ctrl + 1 本來就是呼叫符號表，可以參考 libchewing 的 README，設定的說明會再修正。

![圖片](https://user-images.githubusercontent.com/5523656/216754713-0098300b-d40f-420e-b78c-4c4e1bf302fc.png)

**Comment by ottokang** [comment]
Fix in #757
