### ISSUE TITLE
安裝程式協助變更 IE 的登錄選項，否則無法運作

### ISSUE THREAD

**Issue by PCMan** [EasyIME/PIME#76]
IE 預設有開啟防止 IPC 連線的保護機制，導致 PIME 無法運作
可在安裝程式提供選項，自動幫使用者解開此設定
否則在 IE 內無法使用所有 PIME 輸入法

**Comment by PCMan** [comment]
IE 設定裡面有個 「啟用受保護模式」
這個一旦開啟，則 PIME 所有的 IPC 訊息都會被阻擋
無法送給 python server，所以就無法運作，需要關掉這個選項
不知道這個設定值在登錄檔的哪裡
@KenLuoTW 有興趣幫一起研究嗎？
可以加入到安裝程式裡面，若使用者同意，就把它關了

**Comment by KenLuoTW** [comment]
加入一個自訂頁面，預設為不核取，這樣子如何？
![default](https://cloud.githubusercontent.com/assets/12954277/14410646/b1e39820-ff66-11e5-93a2-a848d1979efa.png)

**Comment by KenLuoTW** [comment]
安裝測試影片，停用 IE 受保護模式，會依 IE 的設定自動變更。
並且安裝後，確定不用再調整設定即可直接輸入。
https://youtu.be/tHdnUylHQeI
