### ISSUE TITLE
現有架構是否可能支援「輸入詞裡的字的第一個音自動選詞」

### ISSUE THREAD

**Issue by DeNT15T** [EasyIME/PIME#764]
如題，不太確定這個功能的名字叫什麼，現在的拼音輸入法或手機注音輸入法大多數都能支援此功能
譬如輸入「ㄈㄐ」輸出「飛機」
唯獨電腦上的注音輸入法似乎都還不支援，做為新酷音的長年用戶，我常常在想如果新酷音能夠支援這個功能的話就好了

如果現有架構有可能支援但缺人力的話，也想請教一下可能能著手修改的地方，我想研究看看能不能做點貢獻。

**Comment by ottokang** [comment]
這個要新酷音的 libchewing 那邊去修改
