### ISSUE TITLE
酷倉輸入法首次使用時的組字視窗位置不正確

### ISSUE THREAD

**Issue by PCMan** [EasyIME/PIME#77]
剛開啟酷倉輸入法，開始打字的時候，
組字視窗會固定在畫面左上角，
原因不明，待查

**Comment by PCMan** [comment]
@KenLuoTW 這可能是 PIME 本身的 bug，我需要查一查

**Comment by KenLuoTW** [comment]
@PCMan 部份軟體，例如 wxMEdit，組字視窗會至畫面左上角，候選清單會至畫面右下角。
![default](https://cloud.githubusercontent.com/assets/12954277/14410753/fc856064-ff68-11e5-836d-15adc0bddd19.png)

**Comment by hsuyh** [comment]
我也發生類似問題，
但我是使用酷音輸入法，
當開啟chrome瀏覽器，在搜尋列打字時，選字匡跑到右下角，
![default](https://cloud.githubusercontent.com/assets/5622631/14890835/a2e976a8-0d96-11e6-9b54-e17d88eece68.JPG)

![image](https://cloud.githubusercontent.com/assets/5622631/14890779/83fa29fe-0d96-11e6-89f7-a64795e5f4f4.png)

但很奇怪的是，當我這頁搜尋完畢後，其他分頁就恢復正常，
每次都是第一次開啟chrome並且在第一個分頁搜尋時有這個錯誤。

電腦版本 windows 8.1 64bit
PIME版本 v0.12

**Comment by PCMan** [comment]
Fixed.
