### ISSUE TITLE
请问如何修改默认python的目录

### ISSUE THREAD

**Issue by ShiningorDying** [EasyIME/PIME#774]
请问如何修改默认python的目录，或者请问一下代码里给的python似乎不能使用PIP，该如何解决呢

**Comment by dongyuwei** [comment]
可以使用virtualenv 创建一个独立的python环境，然后把backends.json在的python.exe路径更新一下。

具体步骤参考：https://gist.github.com/dongyuwei/42626b4bded6ac16fccb4234154a0a05?permalink_comment_id=4717099#gistcomment-4717099

我把步骤复制如下：

## how to use virtualenv to setup a custom python env(so we can use pip packages)

```bash
pip3 install virtualenv ## 此处的pip3是系统python3 提供的
virtualenv -V
virtualenv -h

virtualenv --python=./python/python3/python.exe --always-copy python/python3/virtualenv
python/python3/virtualenv/Scripts/python.exe -V
```

## use pip to install  marisa-trie
`python/python3/virtualenv/Scripts/python.exe -m pip install -U marisa-trie`

Then we can use the `marisa-trie` package in `python/python3/virtualenv/Scripts/python.exe`:
```python
import marisa_trie
trie = marisa_trie.Trie([u'key1', u'key2', u'key12'])
trie.keys(u'key1')
```

## tips
1. Remove `python\python3\virtualenv\.gitignore`
2. update python.exe path in `backends.json`
3. update python.exe path in `installer\installer.nsi`
4. update all `python3\\pythonw.exe` path to `python3\\virtualenv\\Scripts\\pythonw.exe`

重新构建安装文件并且安装后，在任务管理器中查看python进程，可以打开文件所在位置，即 `C:\Program Files (x86)\PIME\python\python3\virtualenv\Scripts\python.exe`.

**Comment by dongyuwei** [comment]
@ottokang 我想知道PIME内置的python为什么不支持pip？这个有什么特殊考虑吗？我试过几种办法都行不通，所以才探索了上面virtualenv的方案。

**Comment by ottokang** [comment]
內置的 Python 是 Windows embeddable package (32-bit)，是沒有 PIP 的，你可以在 python 目錄中安裝 PIP，可以參考：[https://dev.to/codemee/windows-xia-zhi-zuo-ke-xi-shi-python-de-fang-fa-1m05](https://dev.to/codemee/windows-xia-zhi-zuo-ke-xi-shi-python-de-fang-fa-1m05)

**Comment by dongyuwei** [comment]
感谢，又学到新东西了。
