### ISSUE TITLE
windows emoji搜尋功能

### ISSUE THREAD

**Issue by q120144178** [EasyIME/PIME#775]
現在windows鍵+；鍵叫出的多功能符號表可以拿來找EMOJI或是GIF謎因圖，但是目前上方的搜尋功能似乎只有內建的輸入法能夠使用，不知道PIME輸入法有沒有辦法突破這個限制呢？那麼將會方便許多，謝謝！

![image](https://github.com/EasyIME/PIME/assets/21129193/7e23b4ff-9296-4ed1-b110-83835749c915)

**Comment by ottokang** [comment]
目前看起來沒辦法，這是 Windows 內建的功能
