### ISSUE TITLE
關閉 Shift 中英切換，但在未知的狀況下會自動變成英文模式且無法切換

### ISSUE THREAD

**Issue by 104bertchen** [EasyIME/PIME#776]
原本的單按 Shift 切換中/英模式蠻好用的，但因為有時候會誤按所以關閉。目前發現在某些情境  (猜測是 Ctrl + Space 開關輸入法速度快且頻繁一點) 英文模式會忽然自己啟動。只能到新酷音設定重新啟用 Shift 切換中英文，然後用 Shift 關閉，但有時候會關不掉一直卡在英文模式而且按鍵盤英文也出不來，只能重新開機

**Comment by ottokang** [comment]
可以用 PIME Launcher 在工具列的選單，重新啟動 PIME，再用 Ctrl + Shift 切換輸入法回新酷音，應該可以解決
