### ISSUE TITLE
已解決 「自由大新倉頡」開啟「標點符號自動確認輸入」後，無法輸出部分「；」開頭的字，例如「黏」

### ISSUE THREAD

**Issue by Yie0610** [EasyIME/PIME#777]
問題簡介：
「自由大新倉頡」開啟「標點符號自動確認輸入」後，無法輸出部分「；」開頭的字，例如「黏」

問題說明：
自由大新倉頡預設「，」「。」「、」這三個符號會直接出字，而不需要按空白鍵。
為了達成類似效果，在酷倉中需開啟「標點符號自動確認輸入」的功能。
**然而自由大新倉頡的「；」為字根「禾」，而「；」也同時被當作符號，因此會有部分以「；」為開頭的字無法順利出字。**
例如「黏」，其拆碼為「；水卜口」，但在開啟「標點符號自動確認輸入」的功能的情況下，「；」會被當成符號，因此當輸入「；水卜口」時，並會不會出字「黏」，反而會變成「；沾」。
但「，」與「。」仍會作為二碼字的簡碼使用，例如「尸。」會出字「房」，因此「，」與「。」也不能「直接出字」。
不知道目前的PIME，是否有解決辦法呢？

參考建議：
如果目前沒有解決辦法的話，以下方法提供參考：
讓使用者可決定哪些符號要列入「標點符號自動確認輸入」，這樣就可以排除「；」，但又不會影響「，」與「。」接在字根後的出字。

PIME版本：
PIME 輸入法平台版本：1.3.0-stable

後記：
PIME是很棒的輸入法平台，希望能愈來愈好，感謝。

**Comment by q120144178** [comment]
你好：
雖然設定頁沒有，但可以透過編輯py檔實現。

step1：找到安裝PIME的位置 通常是：C:\Program Files (x86)\PIME
step2：到C:\Program Files (x86)\PIME\python\cinbase 找到 「__init__.py」
step3：以記事本開啟
step4：找到 cbTS.directCommitSymbolList = ["，", "。", "、", "；", "？", "！"]
step5：把, "；"去除後另存新檔至桌面或其他位置 (我這邊試沒辦法直接存檔覆蓋)
step6：將原來的檔案另外備份後覆蓋，到右下角PIME launcher右鍵重新啟動，應該就可以生效

**Comment by Yie0610** [comment]
您好：

太好了，已解決問題，非常感謝您。

如果PIME launcher無法右鍵重新啟動的話，重開機後即可生效。

**Comment by Yie0610** [comment]
您好：

太好了，已解決問題，非常感謝您。

如果找不到PIME launcher無法右鍵重新啟動的話，重開機後即可生效。

**Comment by Yie0610** [comment]
您好：

太好了，已解決問題，非常感謝您。

如果找不到PIME launcher無法右鍵重新啟動的話，重開機後即可生效。

**Comment by Yie0610** [comment]
太好了，已解決問題，非常感謝您。

如果找不到PIME launcher無法右鍵重新啟動的話，重開機後即可生效。
