### ISSUE TITLE
關於 ctrl + delete 功能，在1.3.0 stable 版本是否失效？

### ISSUE THREAD

**Issue by jmillerhc** [EasyIME/PIME#779]
先前的1.3.0 beta 2版本有一個 ctrl + delete 的快速鍵功能

「新酷音選字時 Ctrl + Delete 可刪除使用者自定詞」

此快速鍵是對應ctrl + 1-9 ，快速建立詞組的反向操作
在1.3.0 stable 版本中似乎沒作用，煩請開發團隊確認，感謝。

我的系統環境是 Windows 11 家用版 22H2

**Comment by ottokang** [comment]
要呼叫出選字列表才能作用
![螢幕擷取畫面 2023-09-05 173539](https://github.com/EasyIME/PIME/assets/5523656/8047e53e-a939-409d-946a-7a0fe98df5ec)
