### ISSUE TITLE
user_freq值會跳成負數的問題

### ISSUE THREAD

**Issue by kuroutaakatsuki** [EasyIME/PIME#781]
我的詞庫目前有8.1萬筆單字數據。

新酷音（PIME）在選擇單字優先度的user_freq值設定的相當細，偶爾會產生常用單字總是沒辦法被優先選擇的問題。
可能也是因為各單字參數相衝的關係，會發生有單字的user_freq值甚至變成負數，以至於相關詞彙一定會選錯。

對於懂得參數機制、甚至開程式修改的人還好，一般用戶對於無法記住常用字的疑慮時有耳聞。

較長的單字優先度高於較短的單字、各單字的優先度調整方式，覺得設計上可以再考量一下。

![Snipaste_2023-08-25_18-55-03](https://github.com/EasyIME/PIME/assets/56618015/a85ef5d7-8a6b-412e-983e-3984c4fd498a)
最下面兩筆是錯誤發音單字，刻意改成負值，讓它不會優先被選擇。

**Comment by yan12125** [comment]
和 https://github.com/EasyIME/PIME/issues/768 討論的似乎是同一個議題？

**Comment by kuroutaakatsuki** [comment]
對，同一個議題。
久久忘記自己有問過。

算是目前遇到PIME注音輸入部分比較顯著的問題吧。
1. 單字優先度的問題（常用字優先度難以推前、長單字優先度比短單字低等等）
2. 使用者詞庫無法開啟

謝謝團隊持續更新。
