### ISSUE TITLE
沒辦法在 Minecraft 中輸入

### ISSUE THREAD

**Issue by Tsaitou7361** [EasyIME/PIME#785]
我已經在Windows和Linux中測試過
我沒辦法在 Minecraft 中輸入中文 會出現英文
但是 Windows 的微軟注音很難用，Linux也必須要用新酷音
有辦法改善或是教我可以在 Minecraft 中輸入中文嗎

**Comment by Top4nk** [comment]
我也是一樣

**Comment by Top4nk** [comment]
跟據我測試,1.19.4無法打字,1.12.2是正常的

**Comment by davidhcefx** [comment]
這樣應該可以把這張 issue close 囉？
