### ISSUE TITLE
Shift無法鎖定大寫（Linux gnome45）

### ISSUE THREAD

**Issue by stevenhuang226** [EasyIME/PIME#787]
在更新到gnome45以後，如果使用shift來切換中英輸入法，會出現沒有辦法使用按住shift來大寫的情況，不過改成Cap Lock就正常
剛剛跟新完arch
更：目前好像只有純英文輸入的時候會這樣，如果一開始有打一點中文，下面有底線就不會出現這種問題
更：好像與Gnome新增的無障礙功能有關
更：全形英文是正常的，只有半形有此現象
我安裝的是ibus-chewing

**Comment by yan12125** [comment]
目前 PIME 只能在 Windows 上用 (https://github.com/EasyIME/PIME/issues/769), 我猜這邊 ibus 的使用者不多，https://github.com/ibus/ibus 或 https://github.com/definite/ibus-chewing 可能比較有人能回答。

**Comment by stevenhuang226** [comment]
對不起，我走錯地方了
因為找到一大ibus-chewing的庫，不知道該去哪個問，而且每個感覺都放置很久了
