### ISSUE TITLE
希望可以有橫式的固定組字列

### ISSUE THREAD

**Issue by weison905** [EasyIME/PIME#788]
就跟以前輸入法一樣
橫式一條，可以移動固定在視窗某一位置，不隨輸入遊標而自行移動
然後有組字時才顯示

**Comment by ottokang** [comment]
可以改橫式，但是固定輸入位置目前沒有辦法設定

![Screenshot 2023-12-11 at 08-39-39 設定新酷音輸入法](https://github.com/EasyIME/PIME/assets/5523656/20a909a7-58a8-4f0a-8cb0-50a7b28ea043)
