### ISSUE TITLE
The toolbar under Win7 x64 becomes longer and longer

### ISSUE THREAD

**Issue by PeterDaveHello** [EasyIME/PIME#79]
Sorry that I'm not sure the trigger of this bug, it just becomes longer and longer like this:

![pime-toolbar-normal](https://cloud.githubusercontent.com/assets/3691490/14408918/0f3d7efa-ff3a-11e5-85cc-97893e471087.png)

They are all invisible "中英文切換" button, though they are invisible, they work as normal when I click it.

The normal one:
![pime-toolbar-becomes-longer](https://cloud.githubusercontent.com/assets/3691490/14408917/0f36968a-ff3a-11e5-8038-a44d727a4022.png)

My PIME version: v0.12 (official build)
My OS version: Windows 7 SP1 Pro x64

Thanks!

**Comment by taichunmin** [comment]
目前用 win10、PIME v0.12 好像沒遇過這問題

**Comment by PeterDaveHello** [comment]
hmmm ... I haven't find a method to reproduce this problem, that's stange, and it's longer than the first time I report this problem now.
![pime-toolbar-becomes-longer-2](https://cloud.githubusercontent.com/assets/3691490/14450820/629d4c26-00b4-11e6-9c13-cf31a53547ba.png)

**Comment by taichunmin** [comment]
不知道為什麼 看到越長越長就很想笑XD

**Comment by PCMan** [comment]
Fixed in 775eb43ae0e679a645f315b2e8d72f5261f66299

**Comment by PeterDaveHello** [comment]
Thanks.
