### ISSUE TITLE
中文輸入狀態下判斷為英文輸入

### ISSUE THREAD

**Issue by yu2chuan** [EasyIME/PIME#790]
常遇到一種狀況就是中英文交錯的在輸入
常常在中文輸入狀態下打了英文，此時必須清掉打錯的注音，切換到英文，再重新打一次
期待新酷音為來的智慧功能，能
中文輸入狀態下判斷為英文輸入，就自動轉換為英文
英文輸入狀態下判斷為注音輸入，就自動轉換為注音
如果打字的順序，很巧的，可能為某個英文字，也可能為某個中文注音，以當下的輸入狀態為英文或是中文做選擇。
(其實微軟注音好像有這樣的能力，但效果不好)

**Comment by davidhcefx** [comment]
關於微軟的自動切換為英文: https://blog.longwin.com.tw/2005/01/%E6%99%BA%E6%85%A7%E8%BC%B8%E5%85%A5%E5%88%87%E6%8F%9B%EF%BC%9F/

**Comment by yu2chuan** [comment]
我發現華碩智慧輸入，某種程度解決我的困擾。華碩已經開放給非華碩的機器使用了
