### ISSUE TITLE
向後詞彙選詞模式 的選字邏輯

### ISSUE THREAD

**Issue by kuroutaakatsuki** [EasyIME/PIME#799]
不知道是不是最近增加的功能，覺得有助加詞等相關功能而嘗試使用。
發覺選字上會有障礙。

以句子「這個功能是否好用」為例，
我的段落為「這個 | 功能 | 是否 | 好用」。

若以「功能」作為選字目標。

選字位置「功能 | 」　→　開啟「是」的選字欄 【問題】
![Snipaste_2023-12-14_17-54-12](https://github.com/EasyIME/PIME/assets/56618015/2e06c92e-6108-43bc-b972-456e57fcbca1)

選字位置「功 | 能」　→　開啟「功能」的選字欄
![Snipaste_2023-12-14_17-54-39](https://github.com/EasyIME/PIME/assets/56618015/28d3d335-246f-49dc-b3df-2f373b165a28)

選字位置「 | 功能」　→　開啟「功」的選字欄 【問題】
![Snipaste_2023-12-14_17-54-55](https://github.com/EasyIME/PIME/assets/56618015/a309ca95-9f3e-48eb-ab5f-3d3038284f30)

文句裡面，只有找到單字中間的那個字，才能選擇。
目前的狀態似乎選字不易、難以確認詞彙斷在哪。

**Comment by ottokang** [comment]
向後選字是新酷音內建的模式，邏輯的確有點怪，如果游標停留在尾端，是可以直接叫出選字視窗的，這必須要 libchewing 那邊修正了
