### ISSUE TITLE
無法使用Ctrl+A, Ctrl+C, Ctrl+V

### ISSUE THREAD

**Issue by lyenliang** [EasyIME/PIME#8]
在新酷音輸入法模式底下沒辦用Ctrl+A把字全選，想要用Ctrl+C複製、Ctrl+V貼上也不行。

**Comment by lyenliang** [comment]
初步測試發現只要chewing_ime.py的
`if keyEvent.isKeyDown(VK_CONTROL):`
回傳`False`
就可以使用這些功能。

**Comment by ottokang** [comment]
測試一下，開啟「按住 Ctrl 輸入快速符號」的功能，Ctrl +A等等功能會失效，沒有開的話可以正常運作

**Comment by lyenliang** [comment]
那麼「按住 Ctrl 輸入快速符號」該怎麼用呢？   我目前用Ctrl+其它鍵，都還能沒按出任何符號

**Comment by ottokang** [comment]
我目前快速符號也是都測試不出來，另外發現開啟「按住 Shift 輸入快速符號」的功能，Shift 的功能也會失效，無法使用像 Shift + Home的選擇功能；如果開啟「 空白鍵選字」，則是空白鍵會失效

**Comment by lyenliang** [comment]
「按住 Ctrl 輸入快速符號」測出來了，請參考[這邊](http://blog.xuite.net/yh96301/blog/41229803-%E6%A8%99%E9%BB%9E%E7%AC%A6%E8%99%9F%E5%BF%AB%E9%80%9F%E9%8D%B5+)。
「Ctrl」+「,」= ， 逗號

「Ctrl」+「.」= 。 句號

「Ctrl」+「'」= 、 頓號

「Ctrl」+「;」= ； 分號

「Ctrl」+「Shift」+「:」= ： 冒號

「Ctrl」+「Shift」+「?」= ？ 問號

「Ctrl」+「Shift」+「!」= ！ 驚嘆號

**Comment by lyenliang** [comment]
是否可以透過調整`chewing_ime.py`的
`if cfg.easySymbolsWithCtrl and keyEvent.isPrintableChar() and self.langMode == CHINESE_MODE:`
的 `keyEvent.isPrintableChar()`
來修正這個問題呢？

`keyEvent.isPrintableChar()`包含所有可見的符號，如果換成一個只包含「,」、「.」、「'」、「;」符號的function是否可行？

**Comment by lyenliang** [comment]
我發現[最新版](https://github.com/EasyIME/PIME/commit/0e63fafd835b7b801bdf2233372dfc9e214be5d1)開啟「按住 Ctrl 輸入快速符號」後，按Ctrl+A ~ Ctrl+Z都有對應的符號會產生；關閉「按住 Ctrl 輸入快速符號」就可以正常使用Ctrl+A, Ctrl+C, Ctrl+V。
Ctrl+A, Ctrl+C, Ctrl+V被賦予新功能了

**Comment by jessy1092** [comment]
@lyenliang 看起來是設定問題，需要 document XD
