### ISSUE TITLE
未輸入/選詞完畢就切換視窗造成選字/詞畫面搶佔最上層顯示

### ISSUE THREAD

**Issue by PeterDaveHello** [EasyIME/PIME#80]
環境： Win7 SP1 Pro x64 + PIME 0.12
問題：未選字(自由大新輸入法)/詞(新酷音輸入法)完成就切換到其他視窗，則選字/詞視窗會佔用螢幕的最上層顯示，直到使用者自行切換回去關閉或完成選字/詞

**Comment by KenLuoTW** [comment]
切換視窗問題應同 #62

**Comment by PeterDaveHello** [comment]
Thanks @KenLuoTW , so I should close this one, right?
