### ISSUE TITLE
PIMELauncher.log失去紀錄功能

### ISSUE THREAD

**Issue by kuroutaakatsuki** [EasyIME/PIME#800]
最近發現家中電腦Windows10環境下，C:\Users\使用者\AppData\Local\PIME\Log這邊的PIMELauncher.log檔案完全不會紀錄。

將PIMELauncher.log的內容刪除成空白，整個PIME輸入法刪除重灌後，
只會出現一個空白的PIMELauncher.log檔案，不會紀錄任何東西。

印象中最後編輯前看到的最後更新時間好像是2023/01的時候，有紀錄了十數比後就再也沒動靜了。
應該是灌1.3.0-stable版過一陣子後。

公司的Windows10環境則很正常有紀錄。
不清楚原因。

**Comment by kuroutaakatsuki** [comment]
剛剛再試著刪除、重安裝過，還是沒有改善。
![Snipaste_2024-01-02_22-00-45](https://github.com/EasyIME/PIME/assets/56618015/b3372437-9d00-47b2-820e-c68f1fc5f201)

**Comment by f88083** [comment]
請問是否開啟了debug功能呢
![image](https://github.com/EasyIME/PIME/assets/56676355/98893167-3ac1-4a2a-90be-cca2289038d8)

**Comment by kuroutaakatsuki** [comment]
謝謝...。
可能是不小心點到，完全沒發現。
真是太蠢了。_(┐「ε:)_
