### ISSUE TITLE
建議實裝選字新增詞彙

### ISSUE THREAD

**Issue by kuroutaakatsuki** [EasyIME/PIME#805]
如IME注音輸入法的那種「打字中選字+ENTER」新增詞彙的方式。

目前「Crtl+數字」的方式已相當完善，只是偶爾會遇到LINE這類與程式快捷鍵相衝的困擾。

**Comment by ottokang** [comment]
打字中在緩衝區應該是不能選字的，用滑鼠會直接輸出，鍵盤也不能用 Shift 選字
