### ISSUE TITLE
在 PIME 輸入法間切換，選字/詞選單不會自動關閉

### ISSUE THREAD

**Issue by PeterDaveHello** [EasyIME/PIME#81]
環境： Win7 SP1 Pro x64 + PIME 0.12
問題：從 **自由大新** 輸入法跟 **新酷音** 輸入法之間切換時，如果選字、選詞沒有完成，則切換輸入法之後選單會繼續殘留，直到下一次進行選字/詞，此時也同時有 #80 搶佔螢幕最上層顯示的問題。若是切換到 PIME 以外的輸入法則無此問題，例如微軟新注音輸入法。

**Comment by KenLuoTW** [comment]
#79 、 #80 、 #81
應該解決 #73 的問題，就能一併解決。
暫時只保留一種 PIME 平台下的輸入法，可以避免此問題。

**Comment by PCMan** [comment]
#73 已經修復，目前測試正常
如還有問題請再次開啟 issue

**Comment by PeterDaveHello** [comment]
Thanks.
