### ISSUE TITLE
新酷音符號選字框在左上

### ISSUE THREAD

**Issue by taichunmin** [EasyIME/PIME#84]
@PCMan 我發現我在還沒有輸入任何預覽文字的情況下
按下 ``` ` ``` 後，選字框會在左上方
我目前的環境在 Win10、PIME v0.12
我在 `Chrome` 和 `notepad.exe` 試過都是同樣狀況
但是如果打了一些預覽文字再按 ``` ` ``` 後
選字框位置就會正常

* 沒有預覽文字直接按下  ``` ` ``` 
![2016-04-12_101047](https://cloud.githubusercontent.com/assets/2192626/14448012/83861002-0097-11e6-80f2-0963f0dae010.png)

* 有預覽文字時按下  ``` ` ``` 
![2016-04-12_101017](https://cloud.githubusercontent.com/assets/2192626/14448022/8ee03fea-0097-11e6-99ed-124766715634.png)

**Comment by KenLuoTW** [comment]
請參考 #77

**Comment by taichunmin** [comment]
這兩個問題不知道能不能算一樣的
因為是不同的東西

**Comment by ottokang** [comment]
應該是一樣的問題，就是有部份軟體選字框不會出現在打字區

**Comment by PCMan** [comment]
和 #35 可能是一樣的 bug

**Comment by PCMan** [comment]
Fixed.
