### ISSUE TITLE
[Feature] 橫向選字視窗

### ISSUE THREAD

**Issue by jlhg** [EasyIME/PIME#85]
希望能提供像 Mac OS X 系統輸入法一樣的橫向選字視窗的選項。

**Comment by InSb** [comment]
應可以在設定的「介面外觀」中調整。
![default](https://cloud.githubusercontent.com/assets/8103265/14708360/f638e9dc-07fc-11e6-84a5-27eb8e9db297.PNG)

**Comment by jlhg** [comment]
感謝!

**Comment by InSb** [comment]
@jlhg 抱歉，截圖時大意了，才發現做錯。
即是說：
「**每列**顯示候選字個數」若為**每頁**顯示候選字個數，便顯作橫向；而若為 1，便為縱向。
「**每頁**顯示候選字個數」則指每頁總共顯示的候選個數。

這樣設計的好處，個人理解是擺脫了非縱即橫的佈侷，能靈活利用顯示空間。
