### ISSUE TITLE
設定新酷音輸入法視窗中的連結錯誤

### ISSUE THREAD

**Issue by hsuyh** [EasyIME/PIME#87]
在 設定新酷音輸入法視窗，關於新酷音選項 頁面中，有以下兩個連結錯誤:

1. 詳情可參閱龔律全所撰寫的[技術報告(PDF)](url)
2. [2004國際開放源碼研討會(ICOS 2004)上的[簡報](url)(Adobe Flash格式)。]

點選這兩個連結，都會出現下圖找不到的錯誤視窗

![image](https://cloud.githubusercontent.com/assets/5622631/14847853/6d6ff3fc-0c9d-11e6-9b9c-265e839a7278.png)

電腦版本 windows 8.1 64bit
PIME版本 v0.12

**Comment by LinJoy888** [comment]
以前設定是送出 *.hta 類型 (), 最近改為 *.py
所以最近版本都無法設定 （還是可以自己指定 Python 執行）

**Comment by hsuyh** [comment]
請問有沒有類似郵件論壇的地方可以討論開發或是發問的呢？

**Comment by hsuyh** [comment]
我看成程式碼 server/input_methods/chewing/config/config.hta中的程式碼中，
他的路徑在doc底下，但是config資料夾並沒有doc資料夾，應該是因為這樣才導致找不到路徑
是不是應該把檔案補上去呢？
