### ISSUE TITLE
build error on Windows7..

### ISSUE THREAD

**Issue by d84001235** [EasyIME/PIME#88]
![image](https://cloud.githubusercontent.com/assets/12559212/14886032/3c30a414-0d81-11e6-933f-f425ffe4eadc.png)
在libpipe.cpp檔中，build的時候出現一些error message如下，好像都是上面藍色部分出了問題，
且上面注解寫著 "FIXME: will this work under Windows 7 and Vista?" 請問這句話的意思是?

'SECURITY_APP_PACKAGE_AUTHORITY': undeclared identifier	
'SECURITY_BUILTIN_APP_PACKAGE_RID_COUNT': undeclared identifier
'SECURITY_APP_PACKAGE_BASE_RID': undeclared identifier
'SECURITY_BUILTIN_PACKAGE_ANY_PACKAGE': undeclared identifier

**Comment by alwayschoco** [comment]
I have built it successfully after paste it in libpipe.cpp 
and then I register both 32-bit and 64-bit PIMETextService.dll

But it still can't type Chinese word when I switch to 新酷音輸入法, 

I can only type in Chinese after run the server.py and only can link to the server successfully while using 記事本 and word.

Besides, the configure menu will not pop out after clicking the icon ( the server shows the onMenu handle message) 

I have no idea where did I go wrong. 

My OS is windows7 and the PIME version is 0.12

Thanks.

**Comment by lyenliang** [comment]
請問 windows 7 環境下有辦法解決 undeclared identifier 的問題嗎？

我最近想建立安裝檔，也遇到同樣的問題。

**Comment by alwayschoco** [comment]
follow this website: http://recxltd.blogspot.tw/2012/03/windows-8-app-container-security-notes.html

I copied and pasted the "App Container Tokens" part to libpipe.cpp and then solved the undeclared identifier problem : 
```
//
// Application Package Authority.
//
 
#define SECURITY_APP_PACKAGE_AUTHORITY              {0,0,0,0,0,15}
 
#define SECURITY_APP_PACKAGE_BASE_RID               (0x00000002L)
#define SECURITY_BUILTIN_APP_PACKAGE_RID_COUNT      (2L)
#define SECURITY_APP_PACKAGE_RID_COUNT              (8L)
#define SECURITY_CAPABILITY_BASE_RID                (0x00000003L)
#define SECURITY_BUILTIN_CAPABILITY_RID_COUNT       (2L)
#define SECURITY_CAPABILITY_RID_COUNT               (5L)
 
//
// Built-in Packages.
//
 
#define SECURITY_BUILTIN_PACKAGE_ANY_PACKAGE        (0x00000001L)
 
//
// Built-in Capabilities.
//
 
#define SECURITY_CAPABILITY_INTERNET_CLIENT                     (0x00000001L)
#define SECURITY_CAPABILITY_INTERNET_CLIENT_SERVER              (0x00000002L)
#define SECURITY_CAPABILITY_PRIVATE_NETWORK_CLIENT_SERVER       (0x00000003L)
#define SECURITY_CAPABILITY_PICTURES_LIBRARY                    (0x00000004L)
#define SECURITY_CAPABILITY_VIDEOS_LIBRARY                      (0x00000005L)
#define SECURITY_CAPABILITY_MUSIC_LIBRARY                       (0x00000006L)
#define SECURITY_CAPABILITY_DOCUMENTS_LIBRARY                   (0x00000007L)
#define SECURITY_CAPABILITY_ENTERPRISE_AUTHENTICATION           (0x00000008L)
#define SECURITY_CAPABILITY_SHARED_USER_CERTIFICATES            (0x00000009L)
#define SECURITY_CAPABILITY_REMOVABLE_STORAGE                   (0x0000000AL)
 
#define SECURITY_CAPABILITY_INTERNET_EXPLORER                   (0x00001000L)
```

Hope this will help you =)

**Comment by lyenliang** [comment]
感謝 @alwayschoco，問題解決了
