### ISSUE TITLE
判斷滑鼠左右鍵

### ISSUE THREAD

**Issue by alwayschoco** [EasyIME/PIME#89]
大家好： 

因為剛接觸這個專案，想由簡單的地方開始做些貢獻但還不太清楚這個專案的一些設計想法，trace code的時候發現有個fix me是要判斷使用者是用左鍵還右鍵按下語言列按鈕

請問，是所有功能都只限定用左鍵還是只限定某些功能？目前是指針對中英切換跟全半形切換去判斷commandType，不知道這樣是否合適。 

如果可以的話就要嘗試人生第一次pull request了！！！

謝謝。

**Comment by KenLuoTW** [comment]
應該是中英切換和全半形切換,兩個有指定就可以了。
因為我剛在 Win7 下測試,酷倉也是有右鍵會呼叫出功能的問題,感謝提供回報。
