### ISSUE TITLE
輸入注音但沒有對應的字的時候，會直接消失注音

### ISSUE THREAD

**Issue by hsuyh** [EasyIME/PIME#91]
輸入注音但沒有對應的字的時候，會直接消失注音。

例如我們輸入 ㄋ一 空白(一聲)，國字上並沒有這個音所對應的字，
這時候我們剛剛打的 ㄋ一 就會整個被刪除掉。

我覺得可以發出警告聲，但是保留輸入的注音符號，
讓使用者可以了解到是沒有這個注音所對應的字，而不是整個注音直接消失掉。

**Comment by PCMan** [comment]
這個是上游 libchewing 的限制，無法在 PIME 裡面處理
https://github.com/chewing/libchewing
