### ISSUE TITLE
chewing_ime.py fixme修改選單的註解

### ISSUE THREAD

**Issue by henry10039980** [EasyIME/PIME#94]
想請問一下這邊的fixme是還有需要改什麼嘛 ？
因為我原本是自己用source code build起來的,發現選單按了沒反應,所以本來嘗試要去把選單實做出來,改到一半去下載最新release的0.12版發現選單按了有反應,有把OnMenu function的東西實做出來了,是還有什麼地方需要改進的嘛？ 如果已經修好了是不是把這邊的fixme註解刪掉比較好?
![fiiii](https://cloud.githubusercontent.com/assets/13612724/15317271/55f1ceba-1c53-11e6-91f2-bbd140c25353.png)

**Comment by PCMan** [comment]
喔對，應該可以刪掉了
