### ISSUE TITLE
win7下，office2016 word 及excel程式中，輸入法均無反應

### ISSUE THREAD

**Issue by vernan42** [EasyIME/PIME#96]
在win7下，office2016 word 及excel程式中，新酷音0.12均無反應，不論是設定為預設的輸入法，或是切換別的輸入法後在切回，都沒有反應，無法切換中英，也無法輸入任何中英文字。

**Comment by kalapontsai** [comment]
+1
移除微軟新注音 無效
Win7 Sp1 64bit , IE11無法操作, 狀態列只有顯示"酷"icon, 未出現[半形/全形], 以及 [中英文切換]
Chrome 版本 50.0.2661.102 可用

**Comment by PCMan** [comment]
剛在 windows 7 + word/excel 2016 下測試過
git 內最新版本無此問題
