### ISSUE TITLE
Debug模式下的自由大新輸入法無法輸入

### ISSUE THREAD

**Issue by alwayschoco** [EasyIME/PIME#97]
大家好：　
按照PCman's blog 的Debug模式下，啟用自由大新輸入法，只要一按下文字鍵，就會產生UnicodeEncodeError : illegal multibyte sequence 且整個輸入法當掉，必須將開啟的server,py關掉否則會發生正在輸入的應用程式錯誤或無回應

使用的是win7, release 12的新酷音，以提供的PIME-0.12-setup.exe安裝

謝謝。

**Comment by KenLuoTW** [comment]
我目前沒有安裝大新模組,不過我在除錯時通常都是開 CMD 或 POWERSHELL 先切換字碼頁
```
chcp 65001
```
然後再執行 server.py, 你看看這樣能不能解決你的問題。
![2016-05-29](https://cloud.githubusercontent.com/assets/12954277/15632386/18b4b44a-25c2-11e6-8132-ea870ac07017.png)

**Comment by alwayschoco** [comment]
您好：

謝謝您提供的方法=)
使用這個方法是可以正常輸入，只是顯示的candidates編碼怪怪的 

![1](https://cloud.githubusercontent.com/assets/17408932/15708095/2b687d14-282f-11e6-8653-2038a2e345b2.PNG)

但新酷音直接開server.py debug沒有這個問題，不知道為什麼自由大新倉頡輸入法會這樣？

**Comment by KenLuoTW** [comment]
因為 CMD 預設字碼頁為 950 (繁體系統),所以不能顯示 Unicode 裡的中文。
新酷音應該沒把中字輸出到 Console 裡,所以不會有錯誤。

將大新倉頡下面這行去除,以後就不用再切字碼頁
```
print("candidates are {}".format(",".join(candidates)))
```

**Comment by KenLuoTW** [comment]
中字亂碼或顯示不正確的問題,我不知道 Windows 的 Console 要如何解決,
但是你可以參考 ConEmu,這個就能正確顯示 UTF-8 中字,但是同樣要切字碼頁(chcp 65001)
http://conemu.github.io/en/UnicodeSupport.html

![2016-06-02](https://cloud.githubusercontent.com/assets/12954277/15732793/a74bf824-28b2-11e6-9cc5-75693b90002d.png)

**Comment by alwayschoco** [comment]
我目前是暫時encode成utf-8，但就只是讓他不要炸掉
不知道這個問題有什麼其他的解決辦法可以達到顯示那些字元QQ

**Comment by KenLuoTW** [comment]
上面所提的 ConEmu 就是在 Console 裡顯示 utf-8 字元的方法,
你應該可以看到上圖中那些 utf-8 字元顯示都是正確的。
這個是在 Windows 裡使用的,用法跟 Windows 的 cmd 沒什麼不同。
其實一般除錯時, 主要看 handle message 的部份。

另外大新倉頡現已合併至酷倉,主要使用 CinBase Class 來處理輸入法的事件。
