### ISSUE TITLE
輸入法模組安裝程式測試

### ISSUE THREAD

**Issue by KenLuoTW** [EasyIME/PIME#98]
為方便各輸入法模組作者簡單套用,故從 PIME 原本的設定環境分離出來,
輸入法模組作者只須簡單幾個動作,即可套用在自己的輸入法模組上。

使用此輸入法模組安裝程式的好處是不須解除安裝 PIME 輸入法主程式,
也不須解除安裝先前版本的輸入法模組,即可直接安裝新版或是測試版的輸入法模組。
安裝完後也不用重新開機,只須以「CTRL + SHIFT」切換一下輸入法,即可開始使用。

腳本檔案:
https://github.com/KenLuoTW/PIME_IMEmodule_Installer/releases/download/v1.1/PIME_IMEmodule_Installer.7z

腳本原始碼位址:
https://github.com/KenLuoTW/PIME_IMEmodule_Installer

以下是酷倉輸入法模組採用此安裝腳本所製作而成的安裝程式。
https://drive.google.com/file/d/0B0FygkS7MtvXRmIyUE5jRlBmaDQ/view?usp=sharing

輸入法模組套用步驟:

1. 下載 PIME_IMEmodule_Installer.7z 並解壓。
2. 將你的輸入法模組整個資料夾拷貝至 PIME_IMEmodule_Installer\include 資料夾裡。
3. 修改 IMEmodule.nsi 檔案裡的以下內容:
```
!define PRODUCT_NAME "酷倉"
!define PRODUCT_ENAME "CheCJ"
!define PRODUCT_FOLDERNAME "checj"
!define PRODUCT_GUID "{F828D2DC-81BE-466E-9CFE-24BB03172693}"
!define PRODUCT_VERSION "1.07"
!define PRODUCT_CONFIGTOOL "old"
```
PRODUCT_NAME: 你的輸入法名稱
PRODUCT_ENAME: 你的輸入法英文名稱 (主要供安裝檔的檔名使用)
PRODUCT_FOLDERNAME: 你的輸入法資料夾名稱 (建議統一小寫)
PRODUCT_GUID: 你的輸入法 GUID
PRODUCT_VERSION: 你的輸入法版本
PRODUCT_CONFIGTOOL: 如果設定方式沒有用到 Tornado,就不用改。

最後執行 NSIS 編譯 IMEmodule.nsi 腳本檔案。

**Comment by InSb** [comment]
事先卸載了PIME，嘗試安裝採用本腳本製成的酷倉輸入法，發現安裝程式雖告知【已安裝】，但並沒有真正完成：輸入法不可用，也沒建立Uninstall程式。

或許用法是先安裝好PIME主程式再使用這裡的安裝程式。
我這就再去試一次。

附圖：
![default](https://cloud.githubusercontent.com/assets/8103265/15646141/bfa8b1da-268e-11e6-8f73-52ceb9fda803.PNG)
![default](https://cloud.githubusercontent.com/assets/8103265/15646184/ea5a4f7e-268e-11e6-8df1-ec2c8154d4f8.PNG)

**Comment by KenLuoTW** [comment]
輸入法模組安裝程式僅在 PIME 已安裝好的狀況下使用,
並不是作為安裝整個 PIME 輸入法使用。

**Comment by InSb** [comment]
@KenLuoTW 是我考慮不周。
剛才只安裝了PIME主程式，未選用任何方案，後安裝了剛才提供的酷倉模組安裝程式，如此酷倉就可用了。

這樣的辦法使主程式與方案分開，能發揮PIME的靈活特性，確會成為PIME發展的里程碑。
只是若想移除方案，或許非要執行PIME的Uninstall程式才好。

**Comment by KenLuoTW** [comment]
好吧,那就輸入法模組也加入解除安裝程式好了~

**Comment by KenLuoTW** [comment]
酷倉輸入法模組的安裝檔案已經更新,以下為變更內容:
* 安裝之前會先偵測 PIME 輸入法平台是否已安裝於系統裡
* 模組已加入獨立的解除安裝程式,可各別移除各輸入法模組

如果沒問題,我就把源碼更新至 GITHUB 上了。

**Comment by InSb** [comment]
已測，可用。
當未安裝PIME主程式時：
![default](https://cloud.githubusercontent.com/assets/8103265/15649543/ee947ea0-26a4-11e6-93d2-17e217541604.PNG)

模組的安裝與卸載：
![default](https://cloud.githubusercontent.com/assets/8103265/15649555/09fb65dc-26a5-11e6-821c-41ec1c7b29ea.PNG)
![default](https://cloud.githubusercontent.com/assets/8103265/15649557/0ee7fb78-26a5-11e6-9118-b6aef65aeaba.PNG)

如此就確實成為了「模組」，為開發和使用都提供了極大便利。

**Comment by KenLuoTW** [comment]
總算把一個月前就說要弄的東西完成了~~

**Comment by jessy1092** [comment]
@KenLuoTW 

Awesome!!!!  這樣也可以把輸入法模組拆開到其他 repo.

方便的話可否把 `PIME_IMEmodule_Installer` 移至 `EasyIME` 底下呢? 
還有加上個 LICENSE

大感謝~  :100:

**Comment by KenLuoTW** [comment]
@jessy1092 我覺得這個模組安裝方式應該不是很理想吧?
最多只是方便讓模組作者包裝起來,讓一般用戶能夠比較簡單地就能參與測試。
畢竟若只有模組作者一個人測試,不僅很多問題會沒發現到,進而延長輸入法模組完成的時間。

我覺得採用 WEB 線上更新程式的方式,直接從 GITHUB 上讀取模組版本,
然後再依用戶選擇,自動從 GITHUB 更新並下載須要更新的輸入法模組,這樣才會比較理想。

**Comment by InSb** [comment]
總之迭代是感人至深的：
![test](https://cloud.githubusercontent.com/assets/8103265/15707975/49ba9258-282e-11e6-83c4-887aa83af76e.PNG)
測試的方便程度恐怕很重要。

**Comment by KenLuoTW** [comment]
@InSb 對於酷倉的貢獻非常大,沒有 @InSb 熱心幫忙測試,
酷倉可能還只是在初步、堪用的狀態下~
