### ISSUE TITLE
酷倉輸入法模組測試版本

### ISSUE THREAD

**Issue by KenLuoTW** [EasyIME/PIME#99]
雖然是測試版本,但酷倉基本上已是功能完備且沒什麼大問題的輸入法模組,大家可以在使用後,於此處建議新功能或使用問題及建議。

會有此測試版本的原因是,一來可讓大家在 PIME 釋出新的正式版前,就能使用或測試到酷倉最新的功能及修正,一來也可確保酷倉在正式釋出時,是個完善的輸入法模組。

酷倉輸入法模組測試版本下載位址:
https://drive.google.com/open?id=0B0FygkS7MtvXRmIyUE5jRlBmaDQ

安裝檔採用 #98 的輸入法模組安裝腳本所製作:
```
使用此輸入法模組安裝程式的好處是不須解除安裝 PIME 輸入法主程式,
也不須解除安裝先前版本的輸入法模組,即可直接安裝新版或是測試版的輸入法模組。
安裝完後也不用重新開機,只須以「CTRL + SHIFT」切換一下輸入法,即可開始使用。
```

測試版難免有不完善的地方,有時改版可能會因為疏忽,而照成輸入法當掉、卡程式的問題。
在測試輸入法前,你可以建立一個批次檔放在桌面上,當程式無回應時,就執行這個批次檔,
即可釋放掉輸入法,以下為批次檔所要寫入的內容:

KillPIME.cmd
```
TASKKILL /F /IM PIMELauncher.exe
TASKKILL /F /IM pythonw.exe
```

要再次啟動輸入法,你只須要在開始功能表裡的「執行」輸入:
```
"C:\Program Files (x86)\PIME\PIMELauncher.exe"
```
即可再次啟動 PIME 輸入法。

-

酷倉輸入法模組 v1.08 更新內容:
* 修正「*」字元只能輸入一次的問題。

2016/06/01 更新1:
* 修正萬用字元查詢不準確的問題。

**Comment by InSb** [comment]
先將萬用字元設為「＊」後測試，可用。例如下（泰瑞倉頡）：
![default](https://cloud.githubusercontent.com/assets/8103265/15672228/f1dfee38-2761-11e6-924c-3989d5e00748.png)
![default](https://cloud.githubusercontent.com/assets/8103265/15672233/f98ec730-2761-11e6-9c5c-7f1268893849.png)
在用亂倉打鳥時也暫未發現問題（亂倉打鳥）：
![default](https://cloud.githubusercontent.com/assets/8103265/15672346/b80f0af8-2762-11e6-9ccb-852484a15e61.png)

**Comment by InSb** [comment]
奇怪的是：
「＊**手**＊日」的結果不僅有「藉（廿**手**木日）」這樣確實匹配到第二碼是「手」的情況，肯定沒問題；
卻也有「摺（**手**尸一日）」，匹配到了第一碼是「手」的情況，感覺像是包含了「手＊＊日」的匹配情況。

不清楚是怎樣的設計考量。

**Comment by KenLuoTW** [comment]
@InSb 是 bug,不是設計考量...

因為先前是不依字數查詢,所以之前萬用字元所占字位,是可有可無的。

修改新的方式後,我忘了將這個給改掉,所以現在輸入「＊手＊日」時,
只要碼表裡有符合4個字,字根裡又有「手」跟「日」即符合查詢。

一會兒即放上新的測試版,這其實只要去掉程式碼裡2個字元,就修正了...

**Comment by InSb** [comment]
@KenLuoTW 現在應沒問題了：
![_2](https://cloud.githubusercontent.com/assets/8103265/15706322/999e2284-2825-11e6-9937-4d5c4806d86b.png)

**Comment by seantw** [comment]
太棒了,謝大大！我的 Windows10 終於有一個較習慣的倉頡輸入法了。

建議多個「半型標點對映」的功能。
讓使用者決定是否在中文模式下` -=\[];',./` 這些按鍵直接輸出全型符號。
像新酷音 [] 就輸出 「」
我希望酷倉也可有 ;',. 輸出中文裡常用的標點符號；、，。、，的
而不需要按 Shift 或切到全型或加 Ctrl。

此外，我覺得設定功能中的「全型標點輸入」與「簡易符號輸入」可合而為一。
命名為「Shift按鍵對映」較易理解。

**Comment by KenLuoTW** [comment]
@seantw 你可以將碼表換成「泰瑞倉頡」,按符號鍵就會自動輸出全形標點了。

至於「全型標點輸入」與「簡易符號輸入」合而為一是有缺點的,
大多數人頂多只會啟用「全型標點輸入」,SHIFT + 字母鍵通常都是拿來輸入英文字母用。

基本上這些便利的符號輸入功能,我自己是全部都關掉不使用,
因為我自己已習慣了微軟 CTRL + 符號鍵的輸入方式。

**Comment by InSb** [comment]
不確定是哪裡的問題，就暫且在這裡回報：
在使用新釋出的 PIME 0.13 中的酷倉模組時，在某些程式中（如記事本`notepad`）使用「‵」選單時，彈出選單後不能選擇；除非再按一次「‵」鍵，不然無法操作選單。奇怪的是，在有些程式中（如 Firefox ）卻是正常的，不清楚原因。

**Comment by KenLuoTW** [comment]
@InSb 我剛更新,已確認有此問題,晚點再來看看是什麼原因所導致。

**Comment by KenLuoTW** [comment]
@InSb 已經修正「‵」鍵選單在 PIME v0.13 須多按一次「‵」鍵才能選擇項目的問題。

**Comment by InSb** [comment]
@KenLuoTW 剛才安裝了 PIME 0.13.1 （未裝任何輸入法模組）和 CheCJ 1.10 來測試，問題仍存在：
剛才測試，雖然在 Edge 和 Firefox 中用「‵」鍵選單很正常，但在 notepad 、 Notepad++ 和 Chrome 中使用時，還是要多按一下「‵」鍵的。

**Comment by KenLuoTW** [comment]
@InSb 
我忘了將裡頭的檔案換成新版的,所以你測試到的還是上個版本的,現已重新包裝。

**Comment by InSb** [comment]
@KenLuoTW 現在正常了。

**Comment by InSb** [comment]
剛才心血來潮，按照[#111](https://github.com/EasyIME/PIME/commit/e1d29dd8f566902504acf9553a7d4bc31c8f942f)的辦法，將快速倉頡輸入法第六代（碼表在[此](https://github.com/chinese-opendesktop/cin-tables/blob/master/scj6.cin)）添加了進來，可以使用。
個人其實不清楚「快速倉頡輸入法第六代」（可稱為快倉六）是甚麼，應是香港開發的一個改版，可能有香港用戶需要吧。
可以看一下。

另，看到有自由大新倉頡加入了進來，不過尚且沒有相應簡介，加一下會比較好。

**Comment by KenLuoTW** [comment]
@InSb 
基本上不用測試喔,只要沒有使用到以鍵盤上方數字鍵作為字根的 cin-based 輸入法,
皆可直接套用這個模組使用,之前加入數種倉頡碼表,實際上是用來排除各種狀況的。

而不支援鍵盤上方數字鍵作為字根的原因是:
目前酷倉是採直接秀出候選字的方式,所以只要一按鍵盤上方數字鍵,就是用來選擇候選字。

可參考 https://github.com/EasyIME/PIME/pull/111

裡頭提到的 2、3階段,目前我沒有時間,也沒動力做較大變動的修改。

不過暫時也有簡單的解決:
1、如果你使用的輸入法碼表,沒有使用到鍵盤上方的數字鍵作為字根,例如速成、無蝦米:
```
你可以直接將該輸入法的碼表拷貝至酷倉的碼表資料夾裡,取代酷倉的 checj.cin,
那麼就可以直接變成以該輸入法編碼的輸入法。

例如在64位元系統,就取代掉:
C:\Program Files (x86)\PIME\server\input_methods\checj\cin\checj.cin
```

2、以 checj 重建新的輸入法模組,工作量其實不大,頂多替換一些字元而已。

**Comment by InSb** [comment]
@KenLuoTW 我剛才的辦法是：
先用最上面的方法 kill 掉 PIME。
將碼表`scj6.cin`放入`server/input_methods/checj/cin`中。
把`server/input_methods/checj/checj_config.py`備份，再在
```
        elif self.selCinType == 7: 
            self.selCinFile = "cin/newcj.cin"
```
之後回車，添加
```
        elif self.selCinType == 8:
            self.selCinFile = "cin/scj6.cin"
```
將`server/input_methods/checj/config/js/config.js`備份，再在
```
var selCins=[
        "酷倉",
        "倉頡",
        "雅虎倉頡",
        "中標倉頡",
        "泰瑞倉頡",
        "亂倉打鳥",
        "倉五",
        "自由大新倉頡"
    ];
```
這裡為`"自由大新倉頡"`這行後添加逗號，回車，添加
```
        "快倉六"
```
最後啟動`"C:\Program Files (x86)\PIME\PIMELauncher.exe"`就可以了。

個人方法，比較麻煩一些，僅作備忘。

**Comment by InSb** [comment]
@KenLuoTW 至於以後（可能）擴充到所有 cin-based 輸入法：
個人也感覺工作量可觀，畢竟恐怕設計思想都要變動不少，急不得。

至於數字鍵參與編碼的輸入法，有代表性的是：

1. 佔用上排數字鍵的大易、行列40等。
其中，記得大易要用`Shift + 上排數字鍵`選字。
2. 主要使用右側小數字鍵盤的縱橫、行列10等。
其中，現在的縱橫要先按小鍵盤上的`/`（選字）或`*`（選詞）後再按數字鍵來選字或詞。

僅作參考，有道聽途說的成分。

**Comment by KenLuoTW** [comment]
考慮了許久,還是決定把 #111 第二階段先完成。
不過可能到時要麻煩大家多多幫忙測試了,因為要改動很多東西。

**Comment by KenLuoTW** [comment]
已經將核心分離出來,請幫忙測試看看原有功能是否都正常。
稍後也將新增幾個採用 CinBase 核心的新輸入法。

**Comment by InSb** [comment]
@KenLuoTW 剛獲悉消息，總之先簡單測一下看看（酷倉模組 1.11）。

能發現的是，「`鍵選單」中「外語文字」雖然能打出假名，而那些假名卻不在設置中出現，而是空白：
![_ _](https://cloud.githubusercontent.com/assets/8103265/16567231/b68f83a4-424e-11e6-93c1-93f87d85a14a.PNG)
若要添加自己定義的外語文字列表，那麼原有的那些假名就會不復存在。
總之，需要檢查一下「外語文字」這邊的行為才好。

「`鍵選單」中「注音符號」很貼心，不過缺少了聲調符號，需要添加。

**Comment by KenLuoTW** [comment]
這個問題,我已經修復,今天晚點會釋出一個比較沒有 BUG 的版本出來測試,連同無蝦米輸入法。

且因為已支援按下空白鍵才秀出候選字的特性,所以也可以支援有用到鍵盤上方數字鍵的輸入法,
只不過不知道為什麼,我覺得按下空白鍵才秀出候選字的方式好難用,所以這部份會弄選項~~

**Comment by KenLuoTW** [comment]
酷倉已不須要再更新,未來都只須要更新 CIN 通用核心,就能運用在各輸入法上使用。

**Comment by xmacghost** [comment]
你好，我是最近才使用酷倉輸入法的使用者
非常感謝終於不用再使用WIN10下內建的倉頡  非常不好用
但是使用酷倉之後，發現在全螢幕下，或是在遊戲中
都沒辨法輸入中文  只能輸入英文
(按Shift也不能切換回中文)
目前測試到的有 鬥陣特攻、英雄聯盟(遊戲內不行)
感謝您
